package com.example.model

/**
 * 40 Sacred Devotional, Temple Live Darshan & Bhakti Channels (Serial 361 - 400)
 * Covers:
 * - Shree Jagannath Dham Puri 24x7 Live Darshan & Aarti
 * - Ram Mandir Ayodhya Janmabhoomi Aarti Live
 * - Tirupati Venkateswara Swamy Srivani Darshan Live
 * - Kashi Vishwanath Jyotirlinga Ganga Aarti Varanasi
 * - Somnath Jyotirlinga Temple Live
 * - Mahakaleshwar Bhasma Aarti Ujjain Live
 * - Shirdi Sai Baba Samadhi Live Darshan
 * - Vaishno Devi Katra Bhawan Live Aarti
 * - Radha Rani & Bankey Bihari Vrindavan Darshan
 * - Haridwar Har Ki Pauri Ganga Aarti Live
 * - Badrinath & Kedarnath Dham Himalayan Darshan
 * - Golden Temple Amritsar 24x7 Live Gurbani Kirtan
 * - Aastha TV, Sanskar TV, Sadhna TV, Arihant Jain TV, Peace of Mind Brahma Kumaris,
 *   Paras TV, Subhavaani TV, Disha TV, Vedic TV, Santan Dharma TV, etc.
 */
fun buildDevotionalChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "puri_jagannath_live",
        serialNumber = 361,
        name = "ଶ୍ରୀ ଜଗନ୍ନାଥ ଲାଇଭ ଦର୍ଶନ (Puri Jagannath)",
        logoText = "JAG",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "245.8K",
        resolution = "1080p FHD",
        currentShow = "ଶ୍ରୀମନ୍ଦିର ମହାପ୍ରଭୁଙ୍କ ମଙ୍ଗଳ ଆଳତି ଓ ବେଶ ଦର୍ଶନ (Mangala Alati)",
        currentShowCategory = "Live Darshan",
        progressPercent = 0.95f,
        language = "Odia / Sanskrit",
        isFeatured = true,
        description = "Live 24x7 sacred broadcast from Shree Jagannath Temple Puri: Mangala Alati, Sandhya Dhupa, Badasinghara Vesha and Jay Jagannath bhajans."
    ),
    RamChannel(
        id = "ayodhya_ram_mandir_live",
        serialNumber = 362,
        name = "ଶ୍ରୀରାମ ମନ୍ଦିର ଅଯୋଧ୍ୟା (Ram Mandir Live)",
        logoText = "RAM",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "312.4K",
        resolution = "1080p FHD",
        currentShow = "ରାମଲଲାଙ୍କ ଶୃଙ୍ଗାର ଆଳତି ଓ ଶ୍ରୀରାମ ସ୍ତୁତି (Shringar Aarti Live)",
        currentShowCategory = "Ram Mandir Darshan",
        progressPercent = 0.90f,
        language = "Hindi / Sanskrit",
        isFeatured = true,
        description = "Direct 24/7 telecast from the grand Shree Ram Janmabhoomi Mandir Ayodhya: Shringar Aarti, Bhog Aarti and Ramcharitmanas recitation."
    ),
    RamChannel(
        id = "tirupati_balaji_svbc",
        serialNumber = 363,
        name = "Tirupati Balaji SVBC (ତିରୁପତି ବାଲାଜୀ)",
        logoText = "TTD",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "188.7K",
        resolution = "1080p FHD",
        currentShow = "Suprabhatam, Tiruppavai & Kalyanotsavam Live",
        currentShowCategory = "Venkateswara Darshan",
        progressPercent = 0.85f,
        language = "Telugu / Sanskrit",
        isFeatured = true,
        description = "Official Sri Venkateswara Bhakti Channel (SVBC) live from Tirumala hills: Suprabhata Seva and Sahasra Deepalankara Seva."
    ),
    RamChannel(
        id = "kashi_vishwanath_live",
        serialNumber = 364,
        name = "Kashi Vishwanath Varanasi (କାଶୀ ବିଶ୍ୱନାଥ)",
        logoText = "KSH",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "165.2K",
        resolution = "1080p FHD",
        currentShow = "ଶ୍ରୀ କାଶୀ ବିଶ୍ୱନାଥ ମଙ୍ଗଳା ଆଳତି ଓ ଗଙ୍ଗା ପୂଜନ (Mangla Aarti)",
        currentShowCategory = "Jyotirlinga Darshan",
        progressPercent = 0.80f,
        language = "Hindi / Sanskrit",
        isFeatured = true,
        description = "Live sanctum sanctorum darshan from Varanasi Kashi Vishwanath Dham Jyotirlinga and evening Dashashwamedh Ghat Maha Ganga Aarti."
    ),
    RamChannel(
        id = "somnath_mahadev_live",
        serialNumber = 365,
        name = "Somnath Jyotirlinga (ସୋମନାଥ ମହାଦେବ)",
        logoText = "SOM",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "121.4K",
        resolution = "1080p FHD",
        currentShow = "ପ୍ରଥମ ଜ୍ୟୋତିର୍ଲିଙ୍ଗ ଶ୍ରୀ ସୋମନାଥ ମହାଦେବ ଆଳତି ଓ ଶୃଙ୍ଗାର",
        currentShowCategory = "First Jyotirlinga",
        progressPercent = 0.75f,
        language = "Gujarati / Sanskrit",
        isFeatured = false,
        description = "Live darshan of the eternal first Jyotirlinga on the shores of Saurashtra, Gujarat with Vedic Shiva Stotras."
    ),
    RamChannel(
        id = "mahakaleshwar_ujjain_live",
        serialNumber = 366,
        name = "Mahakaleshwar Ujjain (ମହାକାଳେଶ୍ୱର ଭସ୍ମ ଆଳତି)",
        logoText = "MHK",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "194.3K",
        resolution = "1080p FHD",
        currentShow = "ଦୈନିକ ପ୍ରାତଃ ଭସ୍ମ ଆଳତି ଓ ଶ୍ରୀ ମହାକାଳ ଦର୍ଶନ (Bhasma Aarti)",
        currentShowCategory = "Bhasma Aarti Ujjain",
        progressPercent = 0.95f,
        language = "Hindi / Sanskrit",
        isFeatured = true,
        description = "World famous daily early morning 4 AM Bhasma Aarti and Sandhya Aarti of Lord Mahakaleshwar Jyotirlinga in Ujjain."
    ),
    RamChannel(
        id = "shirdi_sai_live",
        serialNumber = 367,
        name = "Shirdi Sai Baba (ଶିରିଡ଼ି ସାଇବାବା ଲାଇଭ)",
        logoText = "SAI",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "156.8K",
        resolution = "1080p FHD",
        currentShow = "କାକଡ଼ ଆଳତି, ମଧ୍ୟାହ୍ନ ଆଳତି ଓ ସାଇ ସମାଧି ଦର୍ଶନ",
        currentShowCategory = "Sai Darshan",
        progressPercent = 0.85f,
        language = "Marathi / Hindi",
        isFeatured = true,
        description = "24/7 direct telecast from Shirdi Sai Baba Samadhi Mandir: Kakad Aarti, Dhoop Aarti and Shej Aarti."
    ),
    RamChannel(
        id = "vaishno_devi_live",
        serialNumber = 368,
        name = "Maa Vaishno Devi Katra (ମାତା ବୈଷ୍ଣୋ ଦେବୀ)",
        logoText = "MSV",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "147.2K",
        resolution = "1080p FHD",
        currentShow = "ପବିତ୍ର ଗୁମ୍ଫା ପ୍ରାତଃ ଆଳତି ଓ ପିଣ୍ଡି ଦର୍ଶନ (Holy Cave Aarti)",
        currentShowCategory = "Devi Darshan",
        progressPercent = 0.80f,
        language = "Hindi / Dogri",
        isFeatured = true,
        description = "Direct darshan from Mata Vaishno Devi Shrine Board Katra, Jammu: Morning and Evening Divine Aarti."
    ),
    RamChannel(
        id = "bankey_bihari_vrindavan",
        serialNumber = 369,
        name = "Bankey Bihari Vrindavan (ବାଙ୍କେ ବିହାରୀ)",
        logoText = "BBV",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "172.6K",
        resolution = "1080p FHD",
        currentShow = "ରାଧେ ରାଧେ ସଙ୍କୀର୍ତ୍ତନ ଓ ବାଙ୍କେ ବିହାରୀ ଦର୍ଶନ",
        currentShowCategory = "Krishna Vrindavan",
        progressPercent = 0.90f,
        language = "Braj / Hindi",
        isFeatured = true,
        description = "Divine Radha-Krishna love chants, Vrindavan Dham Bankey Bihari Darshan, Prem Mandir and Nidhivan mysteries."
    ),
    RamChannel(
        id = "haridwar_ganga_aarti",
        serialNumber = 370,
        name = "Har Ki Pauri Haridwar (ମା' ଗଙ୍ଗା ଆଳତି)",
        logoText = "GNG",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "138.9K",
        resolution = "1080p FHD",
        currentShow = "ହର କି ପୌରୀ ସନ୍ଧ୍ୟା ମହା ଗଙ୍ଗା ଆଳତି (Maha Ganga Aarti)",
        currentShowCategory = "Ganga Aarti",
        progressPercent = 0.85f,
        language = "Hindi / Sanskrit",
        isFeatured = true,
        description = "The enchanting sight of thousands of floating brass lamps and Vedic chants at Haridwar Har Ki Pauri ghats."
    ),
    RamChannel(
        id = "badrinath_kedarnath_live",
        serialNumber = 371,
        name = "Badrinath & Kedarnath (ବଦ୍ରିନାଥ-କେଦାରନାଥ)",
        logoText = "BKN",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "129.5K",
        resolution = "1080p FHD",
        currentShow = "ହିମାଳୟ ଚାରିଧାମ ଶ୍ରୀ ବଦ୍ରିବିଶାଳ ଓ ବାବା କେଦାର ଦର୍ଶନ",
        currentShowCategory = "Himalayan Chardham",
        progressPercent = 0.70f,
        language = "Hindi / Sanskrit",
        isFeatured = false,
        description = "Sacred Darshan from the snow-clad peaks of Kedarnath Jyotirlinga and Badrinath Narayan temple."
    ),
    RamChannel(
        id = "golden_temple_amritsar",
        serialNumber = 372,
        name = "Golden Temple Amritsar (ହରମନ୍ଦିର ସାହିବ)",
        logoText = "SGPC",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "162.1K",
        resolution = "1080p FHD",
        currentShow = "ପବିତ୍ର ଗୁରୁବାଣୀ କୀର୍ତ୍ତନ ୨୪x୭ (Live Gurbani Kirtan)",
        currentShowCategory = "Live Gurbani",
        progressPercent = 0.90f,
        language = "Punjabi / Gurmukhi",
        isFeatured = true,
        description = "Live 24x7 heavenly Gurbani Kirtan straight from Sachkhand Sri Harmandir Sahib (Golden Temple), Amritsar."
    ),
    RamChannel(
        id = "aastha_tv",
        serialNumber = 373,
        name = "Aastha TV (ଆସ୍ଥା ଭଜନ ୨୪x୭)",
        logoText = "AST",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "143.4K",
        resolution = "1080p FHD",
        currentShow = "ସ୍ୱାମୀ ରାମଦେବ ଯୋଗ ଓ ମୋରାରୀ ବାପୁ ରାମକଥା",
        currentShowCategory = "Spiritual Discourses",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "India's pioneer devotional channel broadcasting Baba Ramdev yoga, Morari Bapu, and Ramesh Bhai Oza katha."
    ),
    RamChannel(
        id = "sanskar_tv",
        serialNumber = 374,
        name = "Sanskar TV (ସଂସ୍କାର ଭକ୍ତି)",
        logoText = "SNS",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "135.8K",
        resolution = "1080p FHD",
        currentShow = "ଶ୍ରୀ ଅନିରୁଦ୍ଧାଚାର୍ଯ୍ୟ ଜୀ ଓ ଦେବକୀନନ୍ଦନ ଠାକୁର ଭାଗବତ",
        currentShowCategory = "Bhagwat Katha",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Sanatan values, discourses by revered spiritual masters, and melodious bhajan sandhyas."
    ),
    RamChannel(
        id = "sadhna_tv",
        serialNumber = 375,
        name = "Sadhna TV (ସାଧନା ଭକ୍ତି)",
        logoText = "SDH",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.2K",
        resolution = "1080p FHD",
        currentShow = "ଦୈନିକ ସତ୍ସଙ୍ଗ ଓ ସାଧୁ ସନ୍ଥ ପ୍ରବଚନ",
        currentShowCategory = "Satsang Live",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Daily spiritual talks, astrological guidance, and religious documentaries on ancient pilgrimage sites."
    ),
    // Additional 25 Devotional Channels (376 - 400)
    RamChannel(
        id = "arihant_tv_jain",
        serialNumber = 376,
        name = "Arihant TV Jain (ଅରିହନ୍ତ ଜୈନ ଧର୍ମ)",
        logoText = "ARH",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.7K",
        resolution = "1080p FHD",
        currentShow = "ଜୈନ ମୁନି ପ୍ରବଚନ, ନମୋକାର ମନ୍ତ୍ର ଜପ ଓ ଆଳତି",
        currentShowCategory = "Jain Philosophy",
        progressPercent = 0.70f,
        language = "Hindi / Prakrit",
        isFeatured = false,
        description = "Dedicated to Bhagwan Mahavira teachings, Ahimsa, Digambara & Shwetambara Muni Pravachans."
    ),
    RamChannel(
        id = "peace_of_mind_tv",
        serialNumber = 377,
        name = "Peace of Mind TV (ପିସ ଅଫ୍ ମାଇଣ୍ଡ)",
        logoText = "POM",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.4K",
        resolution = "1080p FHD",
        currentShow = "ବିକେ ଶିବାନୀ ଜୀଙ୍କ ଆତ୍ମିକ ପ୍ରବଚନ (Awakening with Brahma Kumaris)",
        currentShowCategory = "Meditation & Life",
        progressPercent = 0.85f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Sister Shivani and Brahma Kumaris guided Rajyoga meditation for inner calm and stress-free living."
    ),
    RamChannel(
        id = "paras_tv_bhakti",
        serialNumber = 378,
        name = "Paras TV Bhakti (ପାରସ ଟିଭି)",
        logoText = "PRS",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "42.1K",
        resolution = "720p HD",
        currentShow = "ଶ୍ରୀ ଶ୍ରୀ ରବିଶଙ୍କର ଆର୍ଟ ଅଫ୍ ଲିଭିଙ୍ଗ ଓ ସତ୍ସଙ୍ଗ",
        currentShowCategory = "Meditation & Peace",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Art of Living bhajans, Sudarshan Kriya insights, and wisdom talks by Sri Sri Ravi Shankar."
    ),
    RamChannel(
        id = "subhavaani_tv",
        serialNumber = 379,
        name = "Subhavaani TV (ଶୁଭବାଣୀ ଭକ୍ତି)",
        logoText = "SBV",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.8K",
        resolution = "1080p FHD",
        currentShow = "ଦୈନିକ ପଞ୍ଚାଙ୍ଗ, ରାଶିଫଳ ଓ ଶ୍ରୀ ସତ୍ୟନାରାୟଣ ପୂଜା",
        currentShowCategory = "Panchang & Puja",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Daily auspicious Muhurats, planetary transits, and traditional Hindu rituals."
    ),
    RamChannel(
        id = "disha_tv",
        serialNumber = 380,
        name = "Disha TV (ଦିଶା ଟିଭି ଧାର୍ମିକ)",
        logoText = "DSH",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "46.3K",
        resolution = "720p HD",
        currentShow = "ଆଧ୍ୟାତ୍ମିକ ଦିଶା ଓ ଭାରତୀୟ ସଂସ୍କୃତି",
        currentShowCategory = "Spiritual Guidance",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Guidance on positive thinking, moral conduct, and philosophical Upanishad interpretations."
    ),
    RamChannel(
        id = "vedic_tv_india",
        serialNumber = 381,
        name = "Vedic TV India (ବୈଦିକ ଟିଭି)",
        logoText = "VDC",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.6K",
        resolution = "1080p FHD",
        currentShow = "ବେଦ ମନ୍ତ୍ରୋଚ୍ଚାରଣ, ଯଜ୍ଞ ଓ ହବନ (Vedic Mantras)",
        currentShowCategory = "Vedic Wisdom",
        progressPercent = 0.75f,
        language = "Sanskrit / Hindi",
        isFeatured = false,
        description = "Rigveda, Samaveda, Yajurveda and Atharvaveda pure recitations and daily Vedic fire rituals."
    ),
    RamChannel(
        id = "sanatan_dharma_tv",
        serialNumber = 382,
        name = "Sanatan Dharma TV (ସନାତନ ଧର୍ମ)",
        logoText = "SNT",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.2K",
        resolution = "1080p FHD",
        currentShow = "ଭାଗବତ ଗୀତା ଜ୍ଞାନ ଓ ହିନ୍ଦୁ ପରମ୍ପରା",
        currentShowCategory = "Sanatan Wisdom",
        progressPercent = 0.80f,
        language = "Hindi / Sanskrit",
        isFeatured = true,
        description = "Srimad Bhagavad Gita shlokas and explanations of ancient rituals and sacred symbols."
    ),
    RamChannel(
        id = "hanuman_chalisa_247",
        serialNumber = 383,
        name = "Hanuman Chalisa 24x7 (ହନୁମାନ ଚାଳିଶା)",
        logoText = "HNM",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "112.5K",
        resolution = "1080p FHD",
        currentShow = "ଅଖଣ୍ଡ ହନୁମାନ ଚାଳିଶା, ସୁନ୍ଦରକାଣ୍ଡ ଓ ବଜରଙ୍ଗବାଣ",
        currentShowCategory = "Akhand Hanuman Recitation",
        progressPercent = 0.90f,
        language = "Awadhi / Hindi",
        isFeatured = true,
        description = "Continuous auspicious 108 recitations of Hanuman Chalisa by Gulshan Kumar, Hariharan and Shankar Mahadevan."
    ),
    RamChannel(
        id = "shiva_mahadev_bhakti",
        serialNumber = 384,
        name = "Shiva Mahadev Bhakti (ହର ହର ମହାଦେବ)",
        logoText = "SHV",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.7K",
        resolution = "1080p FHD",
        currentShow = "ଶିବ ତାଣ୍ଡବ ସ୍ତୋତ୍ରମ, ରୁଦ୍ରାଭିଷେକ ଓ ମହାମୃତ୍ୟୁଞ୍ଜୟ",
        currentShowCategory = "Shiva Stotram",
        progressPercent = 0.85f,
        language = "Sanskrit / Hindi",
        isFeatured = true,
        description = "Shiva Tandava Stotram, Mahamrityunjaya Mantra 108 times, and 12 Jyotirlinga Abhishekams."
    ),
    RamChannel(
        id = "krishna_sankirtan_live",
        serialNumber = 385,
        name = "Krishna Sankirtan ISKCON (ଇସକନ କୃଷ୍ଣ)",
        logoText = "ISK",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "104.2K",
        resolution = "1080p FHD",
        currentShow = "ହରେ କୃଷ୍ଣ ମହାମନ୍ତ୍ର ସଙ୍କୀର୍ତ୍ତନ ଓ ମାୟାପୁର ଆଳତି",
        currentShowCategory = "Hare Krishna Kirtan",
        progressPercent = 0.90f,
        language = "Bengali / Hindi",
        isFeatured = true,
        description = "Mayapur and Vrindavan ISKCON live darshan, Srila Prabhupada lectures and ecstatic chanting."
    ),
    RamChannel(
        id = "ganesh_bhakti_live",
        serialNumber = 386,
        name = "Siddhi Vinayak Mumbai (ସିଦ୍ଧି ବିନାୟକ)",
        logoText = "GAN",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "91.6K",
        resolution = "1080p FHD",
        currentShow = "ମୁମ୍ବାଇ ସିଦ୍ଧି ବିନାୟକ ଆଳତି ଓ ସଙ୍କଟନାଶନ ସ୍ତୋତ୍ର",
        currentShowCategory = "Ganesha Darshan",
        progressPercent = 0.80f,
        language = "Marathi / Sanskrit",
        isFeatured = false,
        description = "Prabhadevi Mumbai Shree Siddhivinayak Ganapati live Aarti and Atharvashirsha recitation."
    ),
    RamChannel(
        id = "durga_bhakti_tv",
        serialNumber = 387,
        name = "Maa Durga Bhakti (ମା' ଦୁର୍ଗା ଭକ୍ତି)",
        logoText = "DRG",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "85.4K",
        resolution = "1080p FHD",
        currentShow = "ଦୁର୍ଗା ସପ୍ତଶତୀ ପାଠ, ମହିଷାସୁର ମର୍ଦ୍ଦିନୀ ସ୍ତୋତ୍ରମ",
        currentShowCategory = "Shakti Upasana",
        progressPercent = 0.75f,
        language = "Hindi / Sanskrit",
        isFeatured = false,
        description = "Navratri celebrations, 51 Shaktipeeth tours, and Durga Saptashati sacred chanting."
    ),
    RamChannel(
        id = "lakshmi_narayan_bhakti",
        serialNumber = 388,
        name = "Lakshmi Narayan Bhakti (ଲକ୍ଷ୍ମୀ ନାରାୟଣ)",
        logoText = "LXM",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "79.3K",
        resolution = "1080p FHD",
        currentShow = "କନକଧାରା ସ୍ତୋତ୍ରମ, ବିଷ୍ଣୁ ସହସ୍ରନାମ ପାଠ",
        currentShowCategory = "Lakshmi Stotram",
        progressPercent = 0.70f,
        language = "Sanskrit / Hindi",
        isFeatured = false,
        description = "Kanakadhara Stotram, Vishnu Sahasranama and Mahalakshmi Ashtakam chanting."
    ),
    RamChannel(
        id = "saraswati_veda_shloka",
        serialNumber = 389,
        name = "Maa Saraswati Vani (ମା' ସରସ୍ୱତୀ ବାଣୀ)",
        logoText = "SRW",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.2K",
        resolution = "1080p FHD",
        currentShow = "ବିଦ୍ୟା ଓ ବୁଦ୍ଧି ପ୍ରଦାୟିନୀ ସରସ୍ୱତୀ ବନ୍ଦନା",
        currentShowCategory = "Knowledge Stotram",
        progressPercent = 0.65f,
        language = "Sanskrit",
        isFeatured = false,
        description = "Prayers for students, memory enhancement mantras, and wisdom stotras."
    ),
    RamChannel(
        id = "ayyappa_swamy_sabarimala",
        serialNumber = 390,
        name = "Sabarimala Ayyappa (ସବରିମାଳା ଶ୍ରୀ ଆୟପ୍ପା)",
        logoText = "AYP",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.5K",
        resolution = "1080p FHD",
        currentShow = "ହରିବରାସନମ ଓ ମକରବିଲକ୍କୁ ଦର୍ଶନ (Harivarasanam)",
        currentShowCategory = "Ayyappa Bhakti",
        progressPercent = 0.85f,
        language = "Malayalam / Sanskrit",
        isFeatured = false,
        description = "Holy Harivarasanam lullaby and pilgrim walks through Kerala's sacred Sabarimala forests."
    ),
    RamChannel(
        id = "meenakshi_amman_madurai",
        serialNumber = 391,
        name = "Madurai Meenakshi (ମଦୁରାଇ ମୀନାକ୍ଷୀ)",
        logoText = "MNK",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.4K",
        resolution = "1080p FHD",
        currentShow = "ମୀନାକ୍ଷୀ ସୁନ୍ଦରେଶ୍ୱର ମହା ଆଳତି ଓ ଉତ୍ସବ",
        currentShowCategory = "Temple Darshan",
        progressPercent = 0.70f,
        language = "Tamil / Sanskrit",
        isFeatured = false,
        description = "Gopuram architectural marvel and goddess Meenakshi divine jewelry darshan in Madurai."
    ),
    RamChannel(
        id = "kamakhya_devi_guwahati",
        serialNumber = 392,
        name = "Maa Kamakhya Guwahati (ମାତା କାମାକ୍ଷା)",
        logoText = "KMK",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "74.8K",
        resolution = "1080p FHD",
        currentShow = "ନୀଳାଚଳ ପର୍ବତ କାମାକ୍ଷା ମହାପୀଠ ଆଳତି",
        currentShowCategory = "Shaktipeeth Live",
        progressPercent = 0.80f,
        language = "Assamese / Sanskrit",
        isFeatured = false,
        description = "Top Tantrik and spiritual Shaktipeeth atop Nilachal hill in Assam, Ambubachi Mela rituals."
    ),
    RamChannel(
        id = "ujjain_kal_bhairav",
        serialNumber = 393,
        name = "Kaal Bhairav Ujjain (କାଳ ଭୈରବ ଉଜ୍ଜୟିନୀ)",
        logoText = "KBL",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.3K",
        resolution = "1080p FHD",
        currentShow = "କାଳ ଭୈରବାଷ୍ଟକମ ଓ ଦୈନିକ ଭୈରବ ପୂଜା",
        currentShowCategory = "Bhairav Stotram",
        progressPercent = 0.65f,
        language = "Hindi / Sanskrit",
        isFeatured = false,
        description = "Adi Shankaracharya's Kaal Bhairav Ashtakam chanting and sacred temple traditions of Ujjain."
    ),
    RamChannel(
        id = "surya_dev_konark_bhakti",
        serialNumber = 394,
        name = "Surya Dev Bhakti (ସୂର୍ଯ୍ୟ ଦେବ କୋଣାର୍କ)",
        logoText = "SRY",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.7K",
        resolution = "1080p FHD",
        currentShow = "ଆଦିତ୍ୟ ହୃଦୟ ସ୍ତୋତ୍ରମ ଓ ସୂର୍ଯ୍ୟ ନମସ୍କାର ମନ୍ତ୍ର",
        currentShowCategory = "Surya Upasana",
        progressPercent = 0.70f,
        language = "Sanskrit / Odia",
        isFeatured = false,
        description = "Aditya Hridaya Stotra chanted by Agastya Rishi and solar healing blessings from Sun Temple legacy."
    ),
    RamChannel(
        id = "raghvendra_swamy_mantralayam",
        serialNumber = 395,
        name = "Guru Raghavendra (ଗୁରୁ ରାଘବେନ୍ଦ୍ର ସ୍ୱାମୀ)",
        logoText = "RGH",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.2K",
        resolution = "1080p FHD",
        currentShow = "ମନ୍ତ୍ରାଳୟମ୍ ବୃନ୍ଦାବନ ପୂଜା ଓ ଭକ୍ତି କୀର୍ତ୍ତନ",
        currentShowCategory = "Guru Darshan",
        progressPercent = 0.60f,
        language = "Kannada / Sanskrit",
        isFeatured = false,
        description = "Mantralayam Brindavan sacred darshan of 16th-century saint Sri Guru Raghavendra Swamy."
    ),
    RamChannel(
        id = "padmanabhaswamy_kerala",
        serialNumber = 396,
        name = "Padmanabhaswamy (ଅନନ୍ତ ପଦ୍ମନାଭ ସ୍ୱାମୀ)",
        logoText = "APN",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.9K",
        resolution = "1080p FHD",
        currentShow = "ଅନନ୍ତ ଶୟନ ଦର୍ଶନ ଓ ସୁପ୍ରଭାତମ୍ ଆଳତି",
        currentShowCategory = "Vishnu Ananta Darshan",
        progressPercent = 0.75f,
        language = "Malayalam / Sanskrit",
        isFeatured = false,
        description = "Thiruvananthapuram golden temple Anantha Padmanabha reclining posture darshan."
    ),
    RamChannel(
        id = "taratarini_odisha_live",
        serialNumber = 397,
        name = "Maa Tara Tarini (ମା' ତାରା ତାରିଣୀ ଗଞ୍ଜାମ)",
        logoText = "TTN",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "83.4K",
        resolution = "1080p FHD",
        currentShow = "ପବିତ୍ର ପୂର୍ଣ୍ଣଗିରି ସ୍ତନ ପୀଠ ମା'ଙ୍କ ମାଜଣା ଓ ସିନ୍ଦୂର ବେଶ",
        currentShowCategory = "Odisha Shaktipeeth",
        progressPercent = 0.85f,
        language = "Odia",
        isFeatured = true,
        description = "Sacred twin mother goddess shrine atop Rushikulya river hill in Purushottampur, Ganjam."
    ),
    RamChannel(
        id = "biraja_temple_jajpur",
        serialNumber = 398,
        name = "Maa Biraja Temple (ମା' ବିରଜା ଯାଜପୁର)",
        logoText = "BRJ",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "75.1K",
        resolution = "1080p FHD",
        currentShow = "ନାଭିଗୟା କ୍ଷେତ୍ର ଦ୍ୱିଭୁଜା ଦୁର୍ଗା ଦର୍ଶନ ଓ ଆଳତି",
        currentShowCategory = "Odisha Navigaya",
        progressPercent = 0.80f,
        language = "Odia",
        isFeatured = true,
        description = "Ancient Nabhi Gaya Kshetra in Jajpur, the two-handed Durga slaying Mahishasura."
    ),
    RamChannel(
        id = "samaleswari_sambalpur_live",
        serialNumber = 399,
        name = "Maa Samaleswari (ମା' ସମଲେଶ୍ୱରୀ ସମ୍ବଲପୁର)",
        logoText = "SML",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.6K",
        resolution = "1080p FHD",
        currentShow = "ମହାନଦୀ କୂଳ ମାତା ସମଲେଶ୍ୱରୀଙ୍କ ଧବଳମୁଖୀ ବେଶ",
        currentShowCategory = "Western Odisha Bhakti",
        progressPercent = 0.85f,
        language = "Sambalpuri / Odia",
        isFeatured = true,
        description = "Western Odisha's supreme presiding deity on the banks of Mahanadi River in Sambalpur."
    ),
    RamChannel(
        id = "chintpurni_himachal_live",
        serialNumber = 400,
        name = "Maa Chintpurni (ମାତା ଚିନ୍ତପୂର୍ଣ୍ଣୀ ହିମାଚଳ)",
        logoText = "CPN",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.3K",
        resolution = "1080p FHD",
        currentShow = "ଛନ୍ନମସ୍ତିକା ଧାମ ପ୍ରାତଃ ଆଳତି ଓ ଦର୍ଶନ",
        currentShowCategory = "Himachal Shaktipeeth",
        progressPercent = 0.70f,
        language = "Hindi / Punjabi",
        isFeatured = false,
        description = "Maa Chhinnamastika Shaktipeeth in Himachal Pradesh dispelling fears and granting prosperity."
    )
)
