package com.example.model

/**
 * Complete catalog of 47+ Odia Regional TV Channels
 * Covers:
 * - News (OTV, Kanak News, Kalinga TV, Prameya News7, Nandighosha, Argus, News18, Bada Khabar, MBC, Naxatra, etc.)
 * - Entertainment & Mega Serials (Tarang TV, Zee Sarthak, Colors Odia, Sidharth TV, Manjari TV, Star Kiran)
 * - Movies & Cinema (Alankar, Sidharth Gold, Tarang Cinema, Ollywood Prime, Puri Cinema)
 * - Music & Songs (Tarang Music, Sidharth Music, Odia Dhun, Akshaya Geeti, Odia Melodies)
 * - Devotional & Spiritual (Prarthana TV, Sidharth Bhakti, Puri Jagannath Temple Live Darshan, ISKCON Puri, Tulasi TV)
 * - Sports, Culture & Kids (Odisha Sports Kalinga Stadium, Odia Pathasala, Madhu Learning)
 */
val EXTENDED_RAM_CHANNELS: List<RamChannel> = listOf(
    RamChannel(
        id = "dd_odia",
        serialNumber = 101,
        name = "DD Odia (ଦୂରଦର୍ଶନ ଓଡ଼ିଆ)",
        logoText = "DDO",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "http://z5ams.akamaized.net/ddodia/tracks-v1a1/index.m3u8",
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "52.4K",
        resolution = "1080p FHD",
        currentShow = "ସମ୍ବାଦ ଓ ଓଡ଼ିଶା ସଂସ୍କୃତି (Khabar Sambad Live)",
        currentShowCategory = "News & Culture",
        progressPercent = 0.65f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Official public service broadcaster delivering authentic Odia news, Lord Jagannath rituals, and cultural festivals."
    ),
    RamChannel(
        id = "otv_odisha",
        serialNumber = 102,
        name = "OTV - Odisha TV (ଓଡ଼ିଶା ଟିଭି ୨୪x୭)",
        logoText = "OTV",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "98.7K",
        resolution = "1080p FHD",
        currentShow = "ଓଡ଼ିଶା ଟାଇମ୍ସ ଓ ବଡ଼ ଖବର (OTV News Express Live)",
        currentShowCategory = "24x7 Breaking News",
        progressPercent = 0.80f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Odisha's pioneer 24x7 news television channel providing fastest ground reporting, politics and public debates."
    ),
    RamChannel(
        id = "kanak_news",
        serialNumber = 103,
        name = "Kanak News (କନକ ନ୍ୟୁଜ ୨୪x୭)",
        logoText = "KNK",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://yuppftalive.akamaized.net/080823/kanaknews/playlist.m3u8",
            "https://d2e1asnsl7br7b.cloudfront.net/7782/master.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "68.9K",
        resolution = "1080p FHD",
        currentShow = "ମହାପଞ୍ଚାୟତ ମହାବିତର୍କ (Mahapanchayat Debate)",
        currentShowCategory = "Primetime News",
        progressPercent = 0.75f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Leading Odia 24x7 breaking news network with investigative coverage and prime debates."
    ),
    RamChannel(
        id = "kalinga_tv",
        serialNumber = 104,
        name = "Kalinga TV (କଳିଙ୍ଗ ଟିଭି ଲାଇଭ)",
        logoText = "KLG",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.mycast.in/kalingatv/d0dbe915091d400bd8ee7f27f0791303.sdp/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://server.thelegitpro.in/kalingatv/kalingatv/index.fmp4.m3u8",
            "https://live.argusnews.in/hls/argustv.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "41.3K",
        resolution = "720p HD",
        currentShow = "କଳିଙ୍ଗ ପ୍ରାଇମ ନ୍ୟୁଜ (Kalinga Prime Hour)",
        currentShowCategory = "State News",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Popular Odia infotainment and news network broadcasting continuous local news and human-interest stories."
    ),
    RamChannel(
        id = "prameya_news7",
        serialNumber = 105,
        name = "Prameya News7 (ପ୍ରମେୟ ନ୍ୟୁଜ ୭)",
        logoText = "NW7",
        category = ChannelCategory.ODIA,
        streamUrl = "https://n7live.akamaized.net/live/master.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "59.2K",
        resolution = "1080p FHD",
        currentShow = "୭ ଦିନ ୭ ଖବର ଓ ନ୍ୟୁଜ ରୁମ (News Room Live)",
        currentShowCategory = "Daily Prime",
        progressPercent = 0.70f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Credible Odia satellite news channel renowned for sharp analysis and rural-urban coverage across Odisha."
    ),
    RamChannel(
        id = "nandighosha_tv",
        serialNumber = 106,
        name = "Nandighosha TV (ନନ୍ଦିଘୋଷ ଟିଭି)",
        logoText = "NDG",
        category = ChannelCategory.ODIA,
        streamUrl = "https://nandighoshatv.akamaized.net/hls/live/2034789/nandighosha/master.m3u8",
        backupStreamUrls = listOf(
            "https://live.argusnews.in/hls/argustv.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "48.1K",
        resolution = "1080p FHD",
        currentShow = "ବଡ଼ ବାର୍ତ୍ତା ଓ ଓଡ଼ିଶା ଆଜିର ଘଟଣାବଳୀ",
        currentShowCategory = "Special Report",
        progressPercent = 0.60f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Modern Odia 24x7 news channel with dynamic infographics, special investigative reports and live updates."
    ),
    RamChannel(
        id = "argus_news",
        serialNumber = 107,
        name = "Argus News (ଅର୍ଗସ ନ୍ୟୁଜ ଲାଇଭ)",
        logoText = "ARG",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf(
            "https://keralive.com/yupp/tv.php?c=argus-news&e=.m3u8",
            "https://d2e1asnsl7br7b.cloudfront.net/7782/master.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "36.8K",
        resolution = "1080p FHD",
        currentShow = "ପ୍ରେକ୍ଷାପଟ ଓ ବିଚାର (Prekhyapata Live)",
        currentShowCategory = "Special Analysis",
        progressPercent = 0.40f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Trusted regional news channel known for grassroots reporting, citizen journalism, and cultural specials."
    ),
    RamChannel(
        id = "news18_odia",
        serialNumber = 108,
        name = "News18 Odia (ନ୍ୟୁଜ୧୮ ଓଡ଼ିଆ)",
        logoText = "N18",
        category = ChannelCategory.ODIA,
        streamUrl = "https://n18syndication.akamaized.net/bpk-tv/News18_Odia_NW18_MOB/output01/master.m3u8",
        backupStreamUrls = listOf(
            "https://nw18live.cdn.jio.com/bpk-tv/News18_Odia_NW18_MOB/output01/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "45.1K",
        resolution = "1080p FHD",
        currentShow = "ସପ୍ତାହର ବଡ଼ ଖବର (Odisha Big Headlines)",
        currentShowCategory = "Network News",
        progressPercent = 0.55f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Network18 regional channel covering national integration, sports, state governance, and lifestyle in Odia."
    ),
    RamChannel(
        id = "bada_khabar",
        serialNumber = 109,
        name = "Bada Khabar (ବଡ଼ ଖବର ଲାଇଭ)",
        logoText = "BDK",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://live.argusnews.in/hls/argustv.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "33.6K",
        resolution = "1080p FHD",
        currentShow = "ବଡ଼ ବିତର୍କ ଓ ଗ୍ରାଉଣ୍ଡ ରିପୋର୍ଟ (Ground Zero Live)",
        currentShowCategory = "News & Views",
        progressPercent = 0.45f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Fearless independent journalism highlighting corruption, public issues, and voices of common citizens."
    ),
    RamChannel(
        id = "mbc_tv",
        serialNumber = 110,
        name = "MBC TV Odia (ଏମବିସି ଟିଭି)",
        logoText = "MBC",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "29.4K",
        resolution = "720p HD",
        currentShow = "ସନ୍ଧ୍ୟା ୭ଟା ସମାଚାର (Evening Odia Express)",
        currentShowCategory = "Regional News",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Popular regional news broadcaster bringing hyper-local news from all 30 districts of Odisha."
    ),
    RamChannel(
        id = "naxatra_news",
        serialNumber = 111,
        name = "Naxatra News Odia (ନକ୍ଷତ୍ର ନ୍ୟୁଜ)",
        logoText = "NXT",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "27.8K",
        resolution = "720p HD",
        currentShow = "ନକ୍ଷତ୍ର ସ୍ପେଶାଲ ବୁଲେଟିନ୍ (Night Headlines)",
        currentShowCategory = "Late Edition",
        progressPercent = 0.40f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "One of Odisha's long-standing satellite news channels focusing on development, art, and regional identity."
    ),
    RamChannel(
        id = "zee_bharat_odia",
        serialNumber = 112,
        name = "Zee Bharat Odia (ଜୀ ଭାରତ ଓଡ଼ିଶା)",
        logoText = "ZBO",
        category = ChannelCategory.ODIA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "38.2K",
        resolution = "1080p FHD",
        currentShow = "ଜୀ ଦେଶ ବିଦେଶ ଓଡ଼ିଶା ନ୍ୟୁଜ୍ (Nation & State)",
        currentShowCategory = "National & State",
        progressPercent = 0.60f,
        language = "Odia / Hindi",
        isFeatured = false,
        description = "Zee Media group coverage in Odia connecting national developments with regional perspectives."
    ),
    RamChannel(
        id = "city_plus_odisha",
        serialNumber = 113,
        name = "City Plus Odisha (ସିଟି ପ୍ଲସ୍ ଓଡ଼ିଶା)",
        logoText = "CTP",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "21.5K",
        resolution = "720p HD",
        currentShow = "ଟୁଇନ ସିଟି ଲାଇଭ (Bhubaneswar-Cuttack Metro)",
        currentShowCategory = "Urban Lifestyle",
        progressPercent = 0.35f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Smart city updates, traffic, lifestyle, civic news, and entertainment from Odisha's major hubs."
    ),
    RamChannel(
        id = "etv_bharat_odia",
        serialNumber = 114,
        name = "ETV Bharat Odia (ଇଟିଭି ଭାରତ ଓଡ଼ିଆ)",
        logoText = "ETV",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "31.9K",
        resolution = "1080p FHD",
        currentShow = "ଇଟିଭି ଡିଜିଟାଲ ନ୍ୟୁଜ (ETV Odisha Live)",
        currentShowCategory = "Digital News",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "ETV network's comprehensive digital broadcast platform delivering Odia headlines and features."
    ),
    RamChannel(
        id = "sambad_tv",
        serialNumber = 115,
        name = "Sambad TV Live (ସମ୍ବାଦ ଲାଇଭ)",
        logoText = "SBD",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "35.2K",
        resolution = "720p HD",
        currentShow = "ଆଜିର ସମ୍ବାଦ ଓ ବିଶେଷ ସମ୍ପାଦକୀୟ",
        currentShowCategory = "Editorial News",
        progressPercent = 0.65f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Broadcasting Odisha's highest circulated daily's analytical voice on current affairs."
    ),
    RamChannel(
        id = "k_news_odisha",
        serialNumber = 116,
        name = "K News Odisha (କେ ନ୍ୟୁଜ ଓଡ଼ିଶା)",
        logoText = "KNW",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "19.8K",
        resolution = "720p HD",
        currentShow = "ଗ୍ରାମାଞ୍ଚଳ ସ୍ପେଶାଲ (Village Voice Odisha)",
        currentShowCategory = "Rural News",
        progressPercent = 0.45f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Focused on farmers, rural governance, block-level developments, and Odia folk traditions."
    ),
    RamChannel(
        id = "kamyaab_tv",
        serialNumber = 117,
        name = "Kamyaab TV Odisha (କାମୟାବ ଟିଭି)",
        logoText = "KMB",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "17.4K",
        resolution = "720p HD",
        currentShow = "କାମୟାବ ଓଡ଼ିଶା ସମ୍ବାଦ (Kamyaab Express)",
        currentShowCategory = "News",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Regional Odia news channel known for grassroots investigation and public grievances."
    ),
    RamChannel(
        id = "metro_tv_odia",
        serialNumber = 118,
        name = "Metro TV Bhubaneswar (ମେଟ୍ରୋ ଟିଭି)",
        logoText = "MTR",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "16.1K",
        resolution = "720p HD",
        currentShow = "ରାଜଧାନୀ ଭୁବନେଶ୍ବର ସମାଚାର (Capital Live)",
        currentShowCategory = "City News",
        progressPercent = 0.40f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Dedicated capital news channel covering assembly, secretariat, and civic developments."
    ),
    RamChannel(
        id = "berhampur_live",
        serialNumber = 119,
        name = "Berhampur Live TV (ବ୍ରହ୍ମପୁର ଲାଇଭ)",
        logoText = "BHM",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "15.3K",
        resolution = "720p HD",
        currentShow = "ଦକ୍ଷିଣ ଓଡ଼ିଶା ସମାଚାର (Ganjam & South Odisha)",
        currentShowCategory = "Southern Odisha",
        progressPercent = 0.55f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Local news coverage for Berhampur, Gopalpur, Ganjam, Gajapati, and southern Odisha."
    ),
    RamChannel(
        id = "rourkela_live",
        serialNumber = 120,
        name = "Rourkela Live TV (ରାଉରକେଲା ସମାଚାର)",
        logoText = "RKL",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "18.7K",
        resolution = "720p HD",
        currentShow = "ଷ୍ଟିଲ ସିଟି ଓ ସୁନ୍ଦରଗଡ଼ ସମାଚାର (Steel City News)",
        currentShowCategory = "Northern Odisha",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Steel city industrial, sports, tribal culture, and hockey capital news updates."
    ),
    RamChannel(
        id = "sambalpur_live",
        serialNumber = 121,
        name = "Sambalpur Express Live (ସମ୍ବଲପୁର ଟିଭି)",
        logoText = "SBP",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "22.6K",
        resolution = "720p HD",
        currentShow = "ପଶ୍ଚିମ ଓଡ଼ିଶା ଦର୍ପଣ ଓ ସମ୍ବଲପୁରୀ ସଂସ୍କୃତି",
        currentShowCategory = "Sambalpuri Culture",
        progressPercent = 0.60f,
        language = "Sambalpuri / Odia",
        isFeatured = true,
        description = "Western Odisha news, Nuakhai festivals, Sambalpuri folk music and cultural heritage."
    ),
    // Odia Entertainment & Serials
    RamChannel(
        id = "tarang_tv",
        serialNumber = 122,
        name = "Tarang TV (ତରଙ୍ଗ ଟିଭି ମନୋରଞ୍ଜନ)",
        logoText = "TRG",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "92.3K",
        resolution = "1080p FHD",
        currentShow = "ତାରା ତାରିଣୀ ଓ ମେଗା ଧାରାବାହିକ (Prime Serial)",
        currentShowCategory = "Odia Mega Serial",
        progressPercent = 0.65f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Odisha's premier entertainment channel featuring family drama serials, reality shows, and comedy."
    ),
    RamChannel(
        id = "zee_sarthak",
        serialNumber = 123,
        name = "Zee Sarthak (ଜୀ ସାର୍ଥକ ଲାଇଭ)",
        logoText = "ZST",
        category = ChannelCategory.ODIA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "89.4K",
        resolution = "1080p FHD",
        currentShow = "ସାର୍ଥକ ମହା ଧାରାବାହିକ ଓ ମନୋରଞ୍ଜନ ଉତ୍ସବ",
        currentShowCategory = "Family Drama",
        progressPercent = 0.70f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Top-rated Odia general entertainment channel offering dramatic serials, Sa Re Ga Ma Pa, and movies."
    ),
    RamChannel(
        id = "colors_odia",
        serialNumber = 124,
        name = "Colors Odia (କଲର୍ସ ଓଡ଼ିଆ)",
        logoText = "CLR",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.1K",
        resolution = "1080p FHD",
        currentShow = "କଲର୍ସ ଓଡ଼ିଆ ସ୍ପେଶାଲ ଧାରାବାହିକ (Evening GEC)",
        currentShowCategory = "Entertainment",
        progressPercent = 0.55f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Viacom18's Odia flagship channel providing heartwarming stories, mythology, and family programming."
    ),
    RamChannel(
        id = "sidharth_tv",
        serialNumber = 125,
        name = "Sidharth TV (ସିଦ୍ଧାର୍ଥ ଟିଭି)",
        logoText = "SDH",
        category = ChannelCategory.ODIA,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.5K",
        resolution = "1080p FHD",
        currentShow = "ସିଦ୍ଧାର୍ଥ ଲୋକପ୍ରିୟ ଯାତ୍ରା ଓ ମନୋରଞ୍ଜନ",
        currentShowCategory = "Odia Jatra & Drama",
        progressPercent = 0.80f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Popular channel from Sitaram Agrawal featuring famous Odia Jatra shows, family drama, and comedy."
    ),
    RamChannel(
        id = "manjari_tv",
        serialNumber = 126,
        name = "Manjari TV (ମଞ୍ଜରୀ ଟିଭି)",
        logoText = "MJR",
        category = ChannelCategory.ODIA,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "43.2K",
        resolution = "1080p FHD",
        currentShow = "ମଞ୍ଜରୀ ଓଡ଼ିଆ ନାଟକ ଓ ମନୋରଞ୍ଜନ (Odia GEC)",
        currentShowCategory = "Odia GEC",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Odisha's Free-to-Air entertainment television channel offering movies, lifestyle shows, and music."
    ),
    RamChannel(
        id = "star_kiran",
        serialNumber = 127,
        name = "Star Kiran Odia (ଷ୍ଟାର କିରଣ)",
        logoText = "KRN",
        category = ChannelCategory.ODIA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.8K",
        resolution = "1080p FHD",
        currentShow = "ଷ୍ଟାର କିରଣ ସୁପରହିଟ୍ ଧାରାବାହିକ (Superhit Primetime)",
        currentShowCategory = "High Budget Drama",
        progressPercent = 0.65f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Disney Star network's high-definition Odia general entertainment channel."
    ),
    // Odia Movies & Cinema
    RamChannel(
        id = "alankar_tv",
        serialNumber = 128,
        name = "Alankar TV (ଅଳଙ୍କାର ଓଡ଼ିଆ ସିନେମା)",
        logoText = "ALK",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "62.4K",
        resolution = "1080p FHD",
        currentShow = "ଓଲିଉଡ଼ ବ୍ଲକବଷ୍ଟର ସିନେମା (Ollywood Blockbuster)",
        currentShowCategory = "Odia Movies",
        progressPercent = 0.70f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "24x7 non-stop Odia cinema channel screening golden era classics and latest theatrical hits."
    ),
    RamChannel(
        id = "sidharth_gold",
        serialNumber = 129,
        name = "Sidharth Gold (ସିଦ୍ଧାର୍ଥ ଗୋଲ୍ଡ)",
        logoText = "SDG",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "55.8K",
        resolution = "1080p FHD",
        currentShow = "ଅନୁଭବ, ବାବୁଶାନ ଓ ସିଦ୍ଧାନ୍ତ ମୁଭିଜ ମାରାଥନ",
        currentShowCategory = "Superhit Movies",
        progressPercent = 0.75f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Action-packed Odia movies channel showcasing superstar blockbusters and family entertainers."
    ),
    RamChannel(
        id = "tarang_cinema",
        serialNumber = 130,
        name = "Tarang Cinema (ତରଙ୍ଗ ସିନେମା ୨୪x୭)",
        logoText = "TCN",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "49.6K",
        resolution = "1080p FHD",
        currentShow = "ଓଡ଼ିଆ ମେଗା ମୁଭି ଫେଷ୍ଟିଭାଲ (Festival Cinema)",
        currentShowCategory = "Odia Cinema",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Continuous round-the-clock Odia cinema channel bringing theater magic directly to your living room."
    ),
    RamChannel(
        id = "ollywood_prime",
        serialNumber = 131,
        name = "Ollywood Prime Cinema (ଓଲିଉଡ଼ ପ୍ରାଇମ)",
        logoText = "OPC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "37.2K",
        resolution = "720p HD",
        currentShow = "କ୍ଲାସିକ୍ ଓ ନୂତନ ଓଡ଼ିଆ ସିନେମା (Classic Cinema)",
        currentShowCategory = "Cinema Heritage",
        progressPercent = 0.60f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Archive of iconic Odia black-and-white and color classics remastered in high definition."
    ),
    RamChannel(
        id = "puri_cinema",
        serialNumber = 132,
        name = "Puri Super Cinema (ପୁରୀ ସିନେମା ଟିଭି)",
        logoText = "PSC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "28.4K",
        resolution = "720p HD",
        currentShow = "ଓଡ଼ିଆ କମେଡି ଓ ପାରିବାରିକ ସିନେମା",
        currentShowCategory = "Family Cinema",
        progressPercent = 0.40f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Family comedy and social drama movies from Odisha's celebrated filmmakers."
    ),
    // Odia Music Channels
    RamChannel(
        id = "tarang_music",
        serialNumber = 133,
        name = "Tarang Music (ତରଙ୍ଗ ମ୍ୟୁଜିକ୍ ୨୪x୭)",
        logoText = "TMS",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.9K",
        resolution = "1080p FHD",
        currentShow = "ନନ୍-ଷ୍ଟପ୍ ଓଡ଼ିଆ ଟପ୍ ଟ୍ରାକ୍ସ (Top 20 Countdown)",
        currentShowCategory = "Music Chartbuster",
        progressPercent = 0.65f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "The undisputed sound of young Odisha, featuring latest movie tracks, pop singles, and artist interviews."
    ),
    RamChannel(
        id = "sidharth_music",
        serialNumber = 134,
        name = "Sidharth Music (ସିଦ୍ଧାର୍ଥ ମ୍ୟୁଜିକ୍)",
        logoText = "SDM",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "44.5K",
        resolution = "1080p FHD",
        currentShow = "ସିଦ୍ଧାର୍ଥ ଓଡ଼ିଆ ରୋମାଣ୍ଟିକ୍ ହିଟ୍ସ (Romantic Beats)",
        currentShowCategory = "Hit Songs",
        progressPercent = 0.70f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Sarthak Music legacy channel delivering chart-topping Odia film and romantic album songs."
    ),
    RamChannel(
        id = "odia_dhun",
        serialNumber = 135,
        name = "Odia Dhun TV (ଓଡ଼ିଆ ଧୁନ୍ ସଙ୍ଗୀତ)",
        logoText = "ODH",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "31.2K",
        resolution = "720p HD",
        currentShow = "ସମ୍ବଲପୁରୀ ଢୋଲ ମାଦଳ ଓ ରସରକେଲି ଗୀତ",
        currentShowCategory = "Folk & Melodies",
        progressPercent = 0.50f,
        language = "Odia / Sambalpuri",
        isFeatured = false,
        description = "High-energy Sambalpuri folk beats, Rangabati mixes, and traditional musical celebrations."
    ),
    RamChannel(
        id = "akshaya_geeti",
        serialNumber = 136,
        name = "Akshaya Geeti (ଅକ୍ଷୟ ମହାନ୍ତି ଗୀତିମାଳା)",
        logoText = "AKG",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "36.8K",
        resolution = "1080p FHD",
        currentShow = "ଅକ୍ଷୟ ମହାନ୍ତି କାଳଜୟୀ ସଙ୍ଗୀତ (Legendary Melodies)",
        currentShowCategory = "Evergreen Legends",
        progressPercent = 0.85f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "24x7 tribute stream dedicated to the eternal melodies of Khoka Bhai (Akshaya Mohanty) and golden Odia music."
    ),
    RamChannel(
        id = "odia_melodies",
        serialNumber = 137,
        name = "Odia Melodies TV (ଓଡ଼ିଆ ସଦାବହାର ଗୀତ)",
        logoText = "OMT",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "25.3K",
        resolution = "720p HD",
        currentShow = "୯୦ ଦଶକର ଶ୍ରେଷ୍ଠ ଓଡ଼ିଆ ଗୀତ (90s Odia Golden Hits)",
        currentShowCategory = "Retro Nostalgia",
        progressPercent = 0.60f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Nostalgic 80s and 90s melodies from legendary singers Bhikari Bal, Pranab Patnaik, and Geeta Dash."
    ),
    // Odia Devotional & Spiritual
    RamChannel(
        id = "prarthana_tv",
        serialNumber = 138,
        name = "Prarthana TV (ପ୍ରାର୍ଥନା ଟିଭି ଭକ୍ତି)",
        logoText = "PRT",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "85.4K",
        resolution = "1080p FHD",
        currentShow = "ପୁରୀ ଶ୍ରୀମନ୍ଦିର ମଙ୍ଗଳ ଆଳତି ଓ ଜଗନ୍ନାଥ ଭଜନ",
        currentShowCategory = "Temple Darshan",
        progressPercent = 0.90f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Odisha's foremost 24x7 devotional television bringing live morning Mangala Alati from Puri and holy Gita discourses."
    ),
    RamChannel(
        id = "sidharth_bhakti",
        serialNumber = 139,
        name = "Sidharth Bhakti (ସିଦ୍ଧାର୍ଥ ଭକ୍ତି ୨୪x୭)",
        logoText = "SDB",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.9K",
        resolution = "1080p FHD",
        currentShow = "ଜଗନ୍ନାଥ ସହସ୍ରନାମ ଓ ଭିକାରୀ ବଳ ଭଜନ",
        currentShowCategory = "Lord Jagannath",
        progressPercent = 0.75f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = true,
        description = "Dedicated spiritual sanctuary featuring immortal Jagannath Bhajans by Bhikari Bal, Namita Agrawal, and live kirtans."
    ),
    RamChannel(
        id = "puri_srimandir_live",
        serialNumber = 140,
        name = "Puri Sri Mandir Live (ଶ୍ରୀ ଜଗନ୍ନାଥ ଦର୍ଶନ)",
        logoText = "PUR",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "99.9K",
        resolution = "1080p FHD",
        currentShow = "ଶ୍ରୀମନ୍ଦିର ବଡ଼ଦାଣ୍ଡ ଓ ପତିତପାବନ ବାନା ଦର୍ଶନ (Live Puri)",
        currentShowCategory = "Live Temple Rituals",
        progressPercent = 0.95f,
        language = "Odia / Sanskrit",
        isFeatured = true,
        description = "Sacred direct feed from Sri Jagannath Dham Puri displaying Bada Danda, Patitapabana flag rituals and Sandhya Dhupa."
    ),
    RamChannel(
        id = "iskcon_puri",
        serialNumber = 141,
        name = "ISKCON Puri Live (ଇସ୍କନ ପୁରୀ ସତସଙ୍ଗ)",
        logoText = "ISK",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.4K",
        resolution = "1080p FHD",
        currentShow = "ହରେ କୃଷ୍ଣ ମହାମନ୍ତ୍ର ସଙ୍କୀର୍ତ୍ତନ ଓ ଶ୍ରୀମଦ୍ ଭାଗବତମ୍ କଥା",
        currentShowCategory = "Krishna Bhakti",
        progressPercent = 0.60f,
        language = "Odia / Hindi",
        isFeatured = false,
        description = "Continuous chanting, spiritual lectures, Gaura Aarti, and transcendental teachings from ISKCON Puri."
    ),
    RamChannel(
        id = "tulasi_tv",
        serialNumber = 142,
        name = "Tulasi TV Odia (ତୁଳସୀ ଟିଭି ଭକ୍ତି)",
        logoText = "TLS",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "28.7K",
        resolution = "720p HD",
        currentShow = "ଓଡ଼ିଆ ଭାଗବତ ଟୁଙ୍ଗୀ ପାରାୟଣ (Odia Bhagabata)",
        currentShowCategory = "Spiritual Katha",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Atibadi Jagannath Das's holy Odia Bhagabata recitations, morning shlokas, and temple documentaries."
    ),
    RamChannel(
        id = "ayush_tv_odia",
        serialNumber = 143,
        name = "Ayush TV Odia (ଆୟୁଷ ଆୟୁର୍ବେଦ ଓଡ଼ିଶା)",
        logoText = "AYU",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "24.1K",
        resolution = "720p HD",
        currentShow = "ଯୋଗ, ପ୍ରାଣାୟାମ ଓ ଆୟୁର୍ବେଦିକ ଚିକିତ୍ସା",
        currentShowCategory = "Health & Spirituality",
        progressPercent = 0.45f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Ancient healing wisdom, herbal medicines, yoga routines, and holistic wellness in Odia."
    ),
    RamChannel(
        id = "jagannath_bhajan",
        serialNumber = 144,
        name = "Jagannath Bhajan Sagar (ଜଗନ୍ନାଥ ଭଜନ ସାଗର)",
        logoText = "JBS",
        category = ChannelCategory.DEVOTIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "33.5K",
        resolution = "1080p FHD",
        currentShow = "କାଳିଆ ସାଆନ୍ତ ଭଜନ ମାଳା (Kalia Saanta)",
        currentShowCategory = "Devotional Songs",
        progressPercent = 0.70f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Continuous soothing Jagannath bhajans, Janana, Gita Govinda, and devotional lyrics."
    ),
    // Sports, Culture & Learning
    RamChannel(
        id = "odisha_sports",
        serialNumber = 145,
        name = "Odisha Sports TV (କଳିଙ୍ଗ ଷ୍ଟାଡିୟମ ଖେଳ)",
        logoText = "ODS",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "46.7K",
        resolution = "1080p 60FPS",
        currentShow = "ହକି ଇଣ୍ଡିଆ ଲାଇଭ ଓ କଳିଙ୍ଗ ସୁପର କପ୍",
        currentShowCategory = "Sports Arena",
        progressPercent = 0.85f,
        language = "Odia / Hindi",
        isFeatured = true,
        description = "Live feed of sports from Kalinga Stadium, Birsa Munda Stadium, Odisha FC football and state athletics."
    ),
    RamChannel(
        id = "odia_pathasala",
        serialNumber = 146,
        name = "Odia Pathasala (ଶିଶୁ ପାଠଶାଳା ଟିଭି)",
        logoText = "PTS",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "26.4K",
        resolution = "1080p FHD",
        currentShow = "ଓଡ଼ିଆ ବର୍ଣ୍ଣମାଳା, ଆନନ୍ଦଦାୟକ ଗପ ଓ କାର୍ଟୁନ୍",
        currentShowCategory = "Kids & Learning",
        progressPercent = 0.50f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Fun learning, animated stories, rhymes and Odia language lessons for kids and school students."
    ),
    RamChannel(
        id = "madhu_learning",
        serialNumber = 147,
        name = "Madhu Learning Odisha (ମଧୁ ଆପ୍ ଶିକ୍ଷା)",
        logoText = "MDH",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "32.1K",
        resolution = "1080p FHD",
        currentShow = "ବିଜ୍ଞାନ, ଗଣିତ ଓ ଇତିହାସ ଭିଡିଓ ପାଠ୍ୟକ୍ରମ (Class 1-10)",
        currentShowCategory = "Educational TV",
        progressPercent = 0.55f,
        language = "Odia (ଓଡ଼ିଆ)",
        isFeatured = false,
        description = "Government of Odisha's educational broadcast platform named after Utkal Gourab Madhusudan Das."
    )
)
