package com.example.model

/**
 * 50 India Free-To-Air (FTA) & General Entertainment Channels (Serial 151 - 200)
 * Covers:
 * - DD National Networks (DD National HD, DD News HD, DD Retro, DD Bharati, DD Kisan, DD India English)
 * - State DD Regional Channels (DD Kashir, DD Rajasthan, DD MP, DD UP, DD Bihar, DD Jharkhand, DD Shimla)
 * - Parliamentary & Educational (Sansad TV 1 & 2, DD Gyan Darshan, Swayam Prabha 1-10, PM eVIDYA 1, 2, 5, 10, 12)
 * - Major FTA Hindi GEC Networks (Dangal TV, Dangal 2, Shemaroo TV, Shemaroo Umang, Big Magic,
 *   Manoranjan Grand, Nazara TV, Ishara TV, Sun Neo, Dhamaal TV, Atrangii TV, Enterr10, Zee Anmol,
 *   Star Utsav, Colors Rishtey, Sony Pal, Unique TV, Manoranjan Prime)
 */
fun buildIndiaFtaChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "dd_national",
        serialNumber = 151,
        name = "DD National HD (ଦୂରଦର୍ଶନ DD1)",
        logoText = "DD1",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/DDNational/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "92.5K",
        resolution = "1080p FHD",
        currentShow = "Prasar Bharati National Heritage Broadcast",
        currentShowCategory = "National TV",
        progressPercent = 0.50f,
        language = "Hindi / English",
        isFeatured = true,
        description = "India's flagship national network bringing unity in diversity, Republic Day, and national ceremonies."
    ),
    RamChannel(
        id = "dd_news",
        serialNumber = 152,
        name = "DD News HD (ଡିଡି ନ୍ୟୁଜ ୨୪x୭)",
        logoText = "DDN",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/0811cd8c37ca4c409d5385a6cd2fa18b/index.m3u8",
        backupStreamUrls = listOf(
            "https://hls.media.nic.in/hls/live/ddnews/ddnews.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "78.3K",
        resolution = "1080p FHD",
        currentShow = "Prime News Hour & Vaad Samvaad",
        currentShowCategory = "National News",
        progressPercent = 0.60f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Official 24x7 public service news channel providing factual, unbiased news across India."
    ),
    RamChannel(
        id = "dd_india",
        serialNumber = 153,
        name = "DD India Global HD (ଡିଡି ଇଣ୍ଡିଆ)",
        logoText = "DDI",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/7d89be7ec75c4046b0ec9c916b7e51e1/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.4K",
        resolution = "1080p FHD",
        currentShow = "Global India Review & Diplomatic Dispatch",
        currentShowCategory = "International Affairs",
        progressPercent = 0.45f,
        language = "English",
        isFeatured = false,
        description = "India's voice to the world showcasing international diplomacy, foreign policy, and economic growth."
    ),
    RamChannel(
        id = "dd_retro",
        serialNumber = 154,
        name = "DD Retro (ଡିଡି ରେଟ୍ରୋ କ୍ଲାସିକ୍)",
        logoText = "RET",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "55.8K",
        resolution = "1080p FHD",
        currentShow = "ରାମାୟଣ, ମହାଭାରତ ଓ ଶକ୍ତିମାନ (Golden Classic TV)",
        currentShowCategory = "Golden Classics",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Doordarshan nostalgia channel broadcasting Ramayan, Mahabharat, Byomkesh Bakshi, and Shaktimaan."
    ),
    RamChannel(
        id = "dd_bharati",
        serialNumber = 155,
        name = "DD Bharati (ଡିଡି ଭାରତୀ ସଂସ୍କୃତି)",
        logoText = "BHR",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.6K",
        resolution = "1080p FHD",
        currentShow = "Indian Classical Music & Classical Dance Heritage",
        currentShowCategory = "Indian Culture & Arts",
        progressPercent = 0.55f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Public service culture channel preserving Indian classical dance, vocal music, drama, and literature."
    ),
    RamChannel(
        id = "dd_kisan",
        serialNumber = 156,
        name = "DD Kisan (ଡିଡି କିଷାନ କୃଷି)",
        logoText = "KSN",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "43.2K",
        resolution = "1080p FHD",
        currentShow = "Kisan Samachar & Krishi Vigyan Live",
        currentShowCategory = "Agriculture & Farming",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "24x7 channel dedicated to Indian farmers, organic cultivation, weather advisory, and market mandis."
    ),
    RamChannel(
        id = "dd_urdu",
        serialNumber = 157,
        name = "DD Urdu (ଡିଡି ଉର୍ଦ୍ଦୁ)",
        logoText = "URD",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "29.8K",
        resolution = "720p HD",
        currentShow = "Ghazal Mehfil & Urdu Adab",
        currentShowCategory = "Culture & Literature",
        progressPercent = 0.50f,
        language = "Urdu",
        isFeatured = false,
        description = "Urdu poetic symposiums, mushairas, historical serials, and heritage broadcasts."
    ),
    RamChannel(
        id = "sansad_tv_1",
        serialNumber = 158,
        name = "Sansad TV 1 (ସଂସଦ ଲୋକସଭା ଲାଇଭ)",
        logoText = "LS1",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.3K",
        resolution = "1080p FHD",
        currentShow = "Lok Sabha Live Proceedings & Question Hour",
        currentShowCategory = "Parliament Live",
        progressPercent = 0.80f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Official live broadcast of the Lower House of Indian Parliament and policy debates."
    ),
    RamChannel(
        id = "sansad_tv_2",
        serialNumber = 159,
        name = "Sansad TV 2 (ସଂସଦ ରାଜ୍ୟସଭା ଲାଇଭ)",
        logoText = "RS2",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "38.7K",
        resolution = "1080p FHD",
        currentShow = "Rajya Sabha Live Proceedings & Standing Committees",
        currentShowCategory = "Parliament Live",
        progressPercent = 0.75f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Live sessions of the Upper House of Indian Parliament and constitutional discussions."
    ),
    RamChannel(
        id = "dd_gyan_darshan",
        serialNumber = 160,
        name = "DD Gyan Darshan (ଜ୍ଞାନ ଦର୍ଶନ ଟିଭି)",
        logoText = "GYN",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "34.5K",
        resolution = "1080p FHD",
        currentShow = "Higher Education & IGNOU Lectures Live",
        currentShowCategory = "University Education",
        progressPercent = 0.60f,
        language = "English / Hindi",
        isFeatured = false,
        description = "National educational TV channel produced by IGNOU and the Ministry of Education."
    ),
    RamChannel(
        id = "swayam_prabha_1",
        serialNumber = 161,
        name = "Swayam Prabha DTH 1 (ସ୍ୱୟଂ ପ୍ରଭା)",
        logoText = "SW1",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "25.1K",
        resolution = "1080p FHD",
        currentShow = "Engineering, Sciences & Technology MOOCs",
        currentShowCategory = "DTH Education",
        progressPercent = 0.50f,
        language = "English / Hindi",
        isFeatured = false,
        description = "24x7 high quality educational programmes across India using GSAT-15 satellite."
    ),
    RamChannel(
        id = "pm_evidya_10",
        serialNumber = 162,
        name = "PM eVIDYA Class 10 (ଇ-ବିଦ୍ୟା ଦଶମ ଶ୍ରେଣୀ)",
        logoText = "EV10",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "29.3K",
        resolution = "1080p FHD",
        currentShow = "CBSE & State Board Mathematics & Science Prep",
        currentShowCategory = "Secondary School",
        progressPercent = 0.65f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Government of India's One Class, One TV channel initiative for class 10 students."
    ),
    // FTA GEC & Entertainment Channels
    RamChannel(
        id = "dangal_tv",
        serialNumber = 163,
        name = "Dangal TV (ଦଙ୍ଗଲ ଟିଭି ଲାଇଭ)",
        logoText = "DGL",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.6K",
        resolution = "1080p FHD",
        currentShow = "ନଥ୍ ଜେୱର ୟା ଜଞ୍ଜୀର (Nath Zevar Ya Zanjeer)",
        currentShowCategory = "Hindi Mega Drama",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "India's highest rated FTA Hindi general entertainment channel with dramatic family sagas."
    ),
    RamChannel(
        id = "dangal_2",
        serialNumber = 164,
        name = "Dangal 2 (ଦଙ୍ଗଲ ୨ ମନୋରଞ୍ଜନ)",
        logoText = "DG2",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "81.4K",
        resolution = "1080p FHD",
        currentShow = "ସିଆ କେ ରାମ ଓ ପୌରାଣିକ କଥା (Mythology Special)",
        currentShowCategory = "Mythological Series",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Second GEC channel from Enterr10 network airing mythological epics and popular re-runs."
    ),
    RamChannel(
        id = "shemaroo_tv",
        serialNumber = 165,
        name = "Shemaroo TV (ଶେମାରୁ ଟିଭି)",
        logoText = "SHM",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "74.8K",
        resolution = "1080p FHD",
        currentShow = "ଗୀତ ହୁଇ ସବସେ ପରାଇ ଓ ପରିବାର କାହାଣୀ",
        currentShowCategory = "Romantic Drama",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = true,
        description = "Popular Hindi family entertainment channel by Shemaroo Entertainment."
    ),
    RamChannel(
        id = "shemaroo_umang",
        serialNumber = 166,
        name = "Shemaroo Umang (ଶେମାରୁ ଉମଙ୍ଗ)",
        logoText = "SHU",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.2K",
        resolution = "1080p FHD",
        currentShow = "କିସ୍ମତ କି ଲକିରୋଁ ସେ (Kismat Ki Lakeeron Se)",
        currentShowCategory = "Original Drama",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Youth-centric Hindi general entertainment channel with fresh original stories and romance."
    ),
    RamChannel(
        id = "big_magic",
        serialNumber = 167,
        name = "Big Magic (ବିଗ୍ ମ୍ୟାଜିକ୍ କମେଡି)",
        logoText = "BGM",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "79.1K",
        resolution = "1080p FHD",
        currentShow = "ଅକବର ବୀରବଲ ଓ ହାସ୍ୟରସ (Akbar Birbal Comedy)",
        currentShowCategory = "Comedy & Laughter",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "India's favorite comedy FTA channel featuring historical humour, situational sitcoms and laughs."
    ),
    RamChannel(
        id = "manoranjan_grand",
        serialNumber = 168,
        name = "Manoranjan Grand (ମନୋରଞ୍ଜନ ଗ୍ରାଣ୍ଡ)",
        logoText = "MRG",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.7K",
        resolution = "1080p FHD",
        currentShow = "ସୁପରହିଟ୍ ଫ୍ୟାମିଲି ସିରିଏଲ ଓ ମନୋରଞ୍ଜନ",
        currentShowCategory = "Family GEC",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Free dish entertainment channel broadcasting drama, comedy and cultural family serials."
    ),
    RamChannel(
        id = "nazara_tv",
        serialNumber = 169,
        name = "Nazara TV (ନଜାରା ଟିଭି ହିନ୍ଦୀ)",
        logoText = "NZR",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "60.4K",
        resolution = "1080p FHD",
        currentShow = "ଲାଲ ବନାରସୀ ଓ ନୂତନ ଧାରାବାହିକ",
        currentShowCategory = "Hindi Serials",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "IN10 Media's general entertainment channel offering engaging social dramas and human emotions."
    ),
    RamChannel(
        id = "ishara_tv",
        serialNumber = 170,
        name = "Ishara TV (ଇଶାରା ଟିଭି)",
        logoText = "ISR",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.3K",
        resolution = "1080p FHD",
        currentShow = "ଜିନ୍ଦେଗୀ ତୁମହାରି ହୈ (Hindi Drama Prime)",
        currentShowCategory = "Emotional Drama",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Zindagi ke har rang - engaging Hindi family drama channel reflecting Indian household values."
    ),
    RamChannel(
        id = "sun_neo",
        serialNumber = 171,
        name = "Sun Neo (ସନ୍ ନିଓ ହିନ୍ଦୀ)",
        logoText = "SNE",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "63.9K",
        resolution = "1080p FHD",
        currentShow = "ଛଠି ମୈୟା କି ବିଟୁଆ ଓ ସନ୍ ନିଓ ପ୍ରାଇମଟାଇମ",
        currentShowCategory = "Devotional Drama",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Sun TV Network's brand new Hindi GEC channel bringing grand scale production serials."
    ),
    RamChannel(
        id = "dhamaal_tv",
        serialNumber = 172,
        name = "Dhamaal TV (ଧମାଲ ଟିଭି କମେଡି)",
        logoText = "DHM",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.2K",
        resolution = "720p HD",
        currentShow = "କମେଡି ସର୍କସ ଓ ହାସ୍ୟ ଉତ୍ସବ (Comedy Hour)",
        currentShowCategory = "Comedy & Standup",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = false,
        description = "Non-stop laughter and gag channel designed to relieve stress and bring smiles to the whole family."
    ),
    RamChannel(
        id = "atrangii_tv",
        serialNumber = 173,
        name = "Atrangii TV (ଅତରଙ୍ଗୀ ଟିଭି)",
        logoText = "ATG",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "49.1K",
        resolution = "1080p FHD",
        currentShow = "ଅତରଙ୍ଗୀ ଓଟିଟି ସ୍ପେଶାଲ ସିରିଏଲ (Originals)",
        currentShowCategory = "OTT Series",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Vibhu Agarwal's premium Hindi FTA channel showcasing fresh OTT quality drama and thriller series."
    ),
    RamChannel(
        id = "enterr10_tv",
        serialNumber = 174,
        name = "Enterr10 TV (ଏଣ୍ଟରଟେନ୍ ଟିଭି)",
        logoText = "E10",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.4K",
        resolution = "1080p FHD",
        currentShow = "ସୁପରହିଟ୍ ଏକ୍ସନ ଡ୍ରାମା (Superhit Action)",
        currentShowCategory = "Action & Drama",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Foundational free-to-air Indian channel broadcasting action movies, thrillers, and popular series."
    ),
    RamChannel(
        id = "zee_anmol",
        serialNumber = 175,
        name = "Zee Anmol (ଜୀ ଅନମୋଲ)",
        logoText = "ZAN",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.7K",
        resolution = "1080p FHD",
        currentShow = "କୁମକୁମ ଭାଗ୍ୟ ଓ ଜୋଦ୍ଧା ଆକବର (All-Time Classics)",
        currentShowCategory = "Legendary Serials",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = true,
        description = "Zee Network's FTA powerhouse featuring the all-time most loved serials and family drama."
    ),
    RamChannel(
        id = "star_utsav",
        serialNumber = 176,
        name = "Star Utsav (ଷ୍ଟାର ଉତ୍ସବ)",
        logoText = "UTS",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "86.3K",
        resolution = "1080p FHD",
        currentShow = "ୟେ ରିସ୍ତା କ୍ୟା କେହଲାତା ହୈ (Star Utsav Superhits)",
        currentShowCategory = "Superhit Family Drama",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Star network's premier free channel rebroadcasting iconic serials that shaped Indian television."
    ),
    RamChannel(
        id = "colors_rishtey",
        serialNumber = 177,
        name = "Colors Rishtey (କଲର୍ସ ରିସ୍ତେ)",
        logoText = "RST",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.9K",
        resolution = "1080p FHD",
        currentShow = "ବାଲିକା ବଧୁ ଓ ଶଶୁରାଲ ସିମର କା (Rishtey Special)",
        currentShowCategory = "Family Serials",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Colors flagship FTA channel uniting hearts with social awakening stories and emotional relationships."
    ),
    RamChannel(
        id = "sony_pal",
        serialNumber = 178,
        name = "Sony Pal (ସୋନି ପଲ୍)",
        logoText = "PAL",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "84.2K",
        resolution = "1080p FHD",
        currentShow = "ସି.ଆଇ.ଡି ଓ ତାରକ ମେହେତା କା ଉଲ୍ଟା ଚଷମା",
        currentShowCategory = "CID & Comedy",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "Sony's free-to-air channel broadcasting iconic episodes of CID, Taarak Mehta and Adaalat."
    ),
    RamChannel(
        id = "unique_tv",
        serialNumber = 179,
        name = "Unique TV (ୟୁନିକ୍ ଟିଭି ହିନ୍ଦୀ)",
        logoText = "UNQ",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "38.6K",
        resolution = "720p HD",
        currentShow = "ଦେଶୀ ତଡକା ଓ ଲୋକପ୍ରିୟ ଧାରାବାହିକ",
        currentShowCategory = "Entertainment",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Free Dish Hindi channel delivering classic comedy, romance and adventure drama."
    ),
    RamChannel(
        id = "manoranjan_prime",
        serialNumber = 180,
        name = "Manoranjan Prime (ମନୋରଞ୍ଜନ ପ୍ରାଇମ)",
        logoText = "MRP",
        category = ChannelCategory.ENTERTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "42.1K",
        resolution = "720p HD",
        currentShow = "ହିନ୍ଦୀ ଓ ଭୋଜପୁରୀ ମନୋରଞ୍ଜନ ଉତ୍ସବ",
        currentShowCategory = "Bhojpuri & Hindi GEC",
        progressPercent = 0.55f,
        language = "Hindi / Bhojpuri",
        isFeatured = false,
        description = "Multi-language entertainment channel popular across rural and semi-urban India."
    ),
    // DD State Networks & Swayam Prabha Education (181 - 200)
    RamChannel(
        id = "dd_kashir",
        serialNumber = 181,
        name = "DD Kashir (ଦୂରଦର୍ଶନ କାଶ୍ମୀର)",
        logoText = "KSH",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "37.4K",
        resolution = "1080p FHD",
        currentShow = "Kashmir Heritage, Sufiyana Mausiqi & Valley News",
        currentShowCategory = "Kashmir Culture",
        progressPercent = 0.50f,
        language = "Kashmiri / Urdu",
        isFeatured = false,
        description = "Doordarshan Srinagar broadcasting Kashmiri art, music, crafts and valley development."
    ),
    RamChannel(
        id = "dd_rajasthan",
        serialNumber = 182,
        name = "DD Rajasthan (ଦୂରଦର୍ଶନ ରାଜସ୍ଥାନ)",
        logoText = "RAJ",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "46.2K",
        resolution = "1080p FHD",
        currentShow = "ପଧାରୋ ମ୍ହାରେ ଦେଶ ଓ ରାଜସ୍ଥାନୀ ଲୋକଗୀତ",
        currentShowCategory = "Rajasthani Folk",
        progressPercent = 0.65f,
        language = "Rajasthani / Hindi",
        isFeatured = false,
        description = "Doordarshan Jaipur presenting vibrant desert culture, Ghoomar, and Thar heritage."
    ),
    RamChannel(
        id = "dd_madhya_pradesh",
        serialNumber = 183,
        name = "DD Madhya Pradesh (ଦୂରଦର୍ଶନ ଏମ.ପି)",
        logoText = "DMP",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.8K",
        resolution = "1080p FHD",
        currentShow = "ମଧ୍ୟପ୍ରଦେଶ ସମାଚାର ଓ ଆଦିବାସୀ ସଂସ୍କୃତି",
        currentShowCategory = "State News",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Doordarshan Bhopal broadcasting state development, wildlife tourism, and tribal folk arts."
    ),
    RamChannel(
        id = "dd_uttar_pradesh",
        serialNumber = 184,
        name = "DD Uttar Pradesh (ଦୂରଦର୍ଶନ ୟୁ.ପି)",
        logoText = "DUP",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.7K",
        resolution = "1080p FHD",
        currentShow = "ଉତ୍ତର ପ୍ରଦେଶ ଦର୍ପଣ ଓ ଅଯୋଧ୍ୟା ସମାଚାର",
        currentShowCategory = "UP News & Culture",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Doordarshan Lucknow bringing Ayodhya, Varanasi, Mathura cultural updates and governance."
    ),
    RamChannel(
        id = "dd_bihar",
        serialNumber = 185,
        name = "DD Bihar (ଦୂରଦର୍ଶନ ବିହାର)",
        logoText = "DBH",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.3K",
        resolution = "1080p FHD",
        currentShow = "ବିହାର ବିହଙ୍ଗମ ଓ ମୈଥିଳୀ, ଭୋଜପୁରୀ ଲୋକଗୀତ",
        currentShowCategory = "Bihari Culture",
        progressPercent = 0.60f,
        language = "Hindi / Bhojpuri / Maithili",
        isFeatured = false,
        description = "Doordarshan Patna celebrating Chhath Puja, ancient Nalanda, Bodh Gaya, and regional folklore."
    ),
    RamChannel(
        id = "dd_jharkhand",
        serialNumber = 186,
        name = "DD Jharkhand (ଦୂରଦର୍ଶନ ଝାଡ଼ଖଣ୍ଡ)",
        logoText = "DJH",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.5K",
        resolution = "1080p FHD",
        currentShow = "ଜୁହାର ଝାଡ଼ଖଣ୍ଡ ଓ ଆଦିବାସୀ ମହୋତ୍ସବ",
        currentShowCategory = "Tribal Culture",
        progressPercent = 0.50f,
        language = "Hindi / Santhali",
        isFeatured = false,
        description = "Doordarshan Ranchi promoting Santhali tribal dances, forest ecosystems, and mining industry."
    ),
    RamChannel(
        id = "dd_shimla",
        serialNumber = 187,
        name = "DD Shimla (ଦୂରଦର୍ଶନ ହିମାଚଳ)",
        logoText = "SML",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "33.1K",
        resolution = "1080p FHD",
        currentShow = "ଦେବଭୂମି ହିମାଚଳ ଦର୍ଶନ ଓ ପାହାଡ଼ି ଗୀତ",
        currentShowCategory = "Himachali Culture",
        progressPercent = 0.45f,
        language = "Hindi / Pahari",
        isFeatured = false,
        description = "Scenic Himalayan traditions, apple orchards, Kullu Dussehra, and Devbhoomi temples."
    ),
    RamChannel(
        id = "swayam_prabha_2",
        serialNumber = 188,
        name = "Swayam Prabha DTH 2 (ସଂସ୍କୃତି ଓ କଳା)",
        logoText = "SW2",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "21.4K",
        resolution = "1080p FHD",
        currentShow = "Humanities, Social Sciences & Arts",
        currentShowCategory = "Higher Education",
        progressPercent = 0.50f,
        language = "English / Hindi",
        isFeatured = false,
        description = "College education programs in sociology, political science, history, and literature."
    ),
    RamChannel(
        id = "swayam_prabha_3",
        serialNumber = 189,
        name = "Swayam Prabha DTH 3 (ବାଣିଜ୍ୟ ଶିକ୍ଷା)",
        logoText = "SW3",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "23.6K",
        resolution = "1080p FHD",
        currentShow = "Commerce, Finance & Business Management",
        currentShowCategory = "Commerce MOOCs",
        progressPercent = 0.55f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Curated undergraduate and postgraduate business, economics, accounting and finance courses."
    ),
    RamChannel(
        id = "swayam_prabha_4",
        serialNumber = 190,
        name = "Swayam Prabha DTH 4 (ବିଜ୍ଞାନ ଓ ଗଣିତ)",
        logoText = "SW4",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "27.8K",
        resolution = "1080p FHD",
        currentShow = "Physics, Chemistry, Life Sciences & Math",
        currentShowCategory = "Science Education",
        progressPercent = 0.60f,
        language = "English / Hindi",
        isFeatured = false,
        description = "IIT, IISc, and central university professors explaining foundational sciences and laboratory experiments."
    ),
    RamChannel(
        id = "swayam_prabha_5",
        serialNumber = 191,
        name = "Swayam Prabha DTH 5 (କମ୍ପ୍ୟୁଟର ବିଜ୍ଞାନ)",
        logoText = "SW5",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "31.2K",
        resolution = "1080p FHD",
        currentShow = "Computer Science, AI & Coding in Python/Java",
        currentShowCategory = "Tech & Coding",
        progressPercent = 0.65f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Free computer programming, data structures, algorithms, and artificial intelligence lectures."
    ),
    RamChannel(
        id = "swayam_prabha_6",
        serialNumber = 192,
        name = "Swayam Prabha DTH 6 (କୃଷି ଶିକ୍ଷା)",
        logoText = "SW6",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "22.5K",
        resolution = "1080p FHD",
        currentShow = "Agricultural Sciences & Horticulture",
        currentShowCategory = "Agri Education",
        progressPercent = 0.45f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Crop science, soil management, dairy farming, and modern agro-technology degrees."
    ),
    RamChannel(
        id = "swayam_prabha_7",
        serialNumber = 193,
        name = "Swayam Prabha DTH 7 (ସ୍ୱାସ୍ଥ୍ୟ ବିଜ୍ଞାନ)",
        logoText = "SW7",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "24.9K",
        resolution = "1080p FHD",
        currentShow = "Nursing, Paramedical & Community Health",
        currentShowCategory = "Health Education",
        progressPercent = 0.50f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Healthcare vocational training, epidemiology, public hygiene, and clinical care."
    ),
    RamChannel(
        id = "swayam_prabha_8",
        serialNumber = 194,
        name = "Swayam Prabha DTH 8 (ଆଇନ ଓ ସମ୍ବିଧାନ)",
        logoText = "SW8",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "20.1K",
        resolution = "1080p FHD",
        currentShow = "Indian Constitution, Law & Jurisprudence",
        currentShowCategory = "Legal Education",
        progressPercent = 0.55f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Legal studies, constitutional rights, civil procedures, and administrative justice."
    ),
    RamChannel(
        id = "swayam_prabha_9",
        serialNumber = 195,
        name = "Swayam Prabha DTH 9 (ଭାଷା ଶିକ୍ଷା)",
        logoText = "SW9",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "19.3K",
        resolution = "1080p FHD",
        currentShow = "Indian Languages, Sanskrit, Hindi, English",
        currentShowCategory = "Languages",
        progressPercent = 0.40f,
        language = "Multilingual",
        isFeatured = false,
        description = "Language acquisition, Sanskrit grammar, conversational skills, and Indian linguistics."
    ),
    RamChannel(
        id = "swayam_prabha_10",
        serialNumber = 196,
        name = "Swayam Prabha DTH 10 (କୃତ୍ରିମ ବୁଦ୍ଧିମତ୍ତା)",
        logoText = "SW10",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "36.4K",
        resolution = "1080p FHD",
        currentShow = "Applied Machine Learning, Robotics & IoT",
        currentShowCategory = "Emerging Tech",
        progressPercent = 0.70f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Cutting-edge skills in machine learning, micro-controllers, IoT, and industrial robotics."
    ),
    RamChannel(
        id = "pm_evidya_1",
        serialNumber = 197,
        name = "PM eVIDYA Class 1 (ପ୍ରଥମ ଶ୍ରେଣୀ ଶିକ୍ଷା)",
        logoText = "EV1",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "24.7K",
        resolution = "1080p FHD",
        currentShow = "Class 1 Rhymes, Alphabet & Storytime",
        currentShowCategory = "Primary Education",
        progressPercent = 0.60f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Foundational literacy, phonics, and numeracy for first grade primary students."
    ),
    RamChannel(
        id = "pm_evidya_2",
        serialNumber = 198,
        name = "PM eVIDYA Class 2 (ଦ୍ୱିତୀୟ ଶ୍ରେଣୀ ଶିକ୍ଷା)",
        logoText = "EV2",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "25.2K",
        resolution = "1080p FHD",
        currentShow = "Class 2 Environmental Studies & Math",
        currentShowCategory = "Primary School",
        progressPercent = 0.55f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Interactive learning, nature around us, addition and storytelling."
    ),
    RamChannel(
        id = "pm_evidya_5",
        serialNumber = 199,
        name = "PM eVIDYA Class 5 (ପଞ୍ଚମ ଶ୍ରେଣୀ ଶିକ୍ଷା)",
        logoText = "EV5",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "28.1K",
        resolution = "1080p FHD",
        currentShow = "Class 5 Science, History & Language",
        currentShowCategory = "Upper Primary",
        progressPercent = 0.50f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Upper primary curriculum preparing young minds with reasoning and environmental awareness."
    ),
    RamChannel(
        id = "pm_evidya_12",
        serialNumber = 200,
        name = "PM eVIDYA Class 12 (ଦ୍ୱାଦଶ ଶ୍ରେଣୀ ଶିକ୍ଷା)",
        logoText = "EV12",
        category = ChannelCategory.INDIA_FTA,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.8K",
        resolution = "1080p FHD",
        currentShow = "Board Exam Prep, JEE & NEET Foundations",
        currentShowCategory = "Senior Secondary",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Comprehensive Class 12 board examination preparation, calculus, organic chemistry, and optics."
    )
)
