package com.example.model

/**
 * 25 Infotainment, Wildlife, Knowledge & Lifestyle Channels (Serial 501 - 525)
 * Covers:
 * - Wildlife & Nature (Discovery Nature, Nat Geo Wild India, Animal Planet Wilderness, Safari India, Corbett Tiger Trails, Marine Ocean World)
 * - Science, Space & Technology (ISRO Space Live, NASA TV English, Gadget & Tech 360, Science Frontier, AI & Robotics World)
 * - History & Civilization (History TV18 Heritage, Ancient Civilizations India, Bharat Historical Monuments, Epic War Strategies)
 * - Food & Culinary (Food Food Sanjeev Kapoor, MasterChef Kitchen India, Desi Street Food Safari, Royal Indian Thali)
 * - Travel & Exploration (TravelXP India, Auto Expo & Supercars, Himalayan Road Trips, Indian Railways Journey TV, Offbeat World Trails)
 */
fun buildInfotainmentChannels(): List<RamChannel> = listOf(
    // Wildlife & Nature (501 - 506)
    RamChannel(
        id = "discovery_nature_hd",
        serialNumber = 501,
        name = "Discovery Nature HD (ଡିସକଭରୀ ନେଚର)",
        logoText = "DSC",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "98.5K",
        resolution = "1080p FHD",
        currentShow = "ମ୍ୟାନ୍ ଭର୍ସେସ ୱାଇଲ୍ଡ ଓ ଆଫ୍ରିକୀୟ ଜଙ୍ଗଲ (Man vs Wild)",
        currentShowCategory = "Wild Survival",
        progressPercent = 0.85f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Bear Grylls survival expeditions, African savannah safaris, and deep rainforest mysteries."
    ),
    RamChannel(
        id = "nat_geo_wild_india",
        serialNumber = 502,
        name = "Nat Geo Wild India (ନେସନାଲ ଜିଓଗ୍ରାଫିକ)",
        logoText = "NGW",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "105.2K",
        resolution = "1080p FHD",
        currentShow = "ବିଗ୍ କ୍ୟାଟ୍ସ: ସିଂହ ଓ ଚିତା ବାଘର ଲଢେଇ (Predators)",
        currentShowCategory = "Apex Predators",
        progressPercent = 0.80f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Unrivaled high-definition wildlife cinematography tracking lions, leopards, and polar bears."
    ),
    RamChannel(
        id = "animal_planet_wilderness",
        serialNumber = 503,
        name = "Animal Planet Wilderness (ପଶୁ ପକ୍ଷୀ ଦୁନିଆ)",
        logoText = "ANP",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.4K",
        resolution = "1080p FHD",
        currentShow = "ରିଭର ମନଷ୍ଟର ଓ ବିଷାକ୍ତ ସାପଙ୍କ ରହସ୍ୟ",
        currentShowCategory = "Wild Encounters",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Dedicated to animal habitats, aquatic creatures, veterinary heroes, and rescue missions."
    ),
    RamChannel(
        id = "safari_india_wild",
        serialNumber = 504,
        name = "Safari India Wild (ଭାରତୀୟ ଅଭୟାରଣ୍ୟ)",
        logoText = "SAF",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.1K",
        resolution = "1080p FHD",
        currentShow = "କାଜିରଙ୍ଗା ଗଣ୍ଡା ଓ ସୁନ୍ଦରବନ ରାୟାଲ ବେଙ୍ଗଲ ଟାଇଗର",
        currentShowCategory = "Indian Wildlife",
        progressPercent = 0.75f,
        language = "Hindi / Odia",
        isFeatured = true,
        description = "India's greatest national parks: Kaziranga, Ranthambore, Gir Forest Asiatic lions, and Similipal elephants."
    ),
    RamChannel(
        id = "corbett_tiger_trails",
        serialNumber = 505,
        name = "Corbett Tiger Trails (ଜିମ କର୍ବେଟ୍ ବାଘ)",
        logoText = "CBT",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.7K",
        resolution = "1080p FHD",
        currentShow = "ହିମାଳୟ ପାଦଦେଶରେ ବାଘଙ୍କ ଚଲାପଥ (Tiger Trail)",
        currentShowCategory = "Tiger Sanctuary",
        progressPercent = 0.65f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Live cameras in Jim Corbett, Bandhavgarh, and Kanha tracking Royal Bengal Tigers."
    ),
    RamChannel(
        id = "marine_ocean_world",
        serialNumber = 506,
        name = "Marine Ocean World (ସମୁଦ୍ର ଗଭୀର ରହସ୍ୟ)",
        logoText = "OCN",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.9K",
        resolution = "1080p FHD",
        currentShow = "ବ୍ଲୁ ହ୍ୱେଲ, କୋରାଲ ରିଫ୍ ଓ ଗଭୀର ସମୁଦ୍ର ଜୀବ",
        currentShowCategory = "Deep Ocean",
        progressPercent = 0.80f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Exploring mysterious Mariana trench, great barrier reefs, dolphins, and bioluminescent ocean life."
    ),
    // Science, Space & Technology (507 - 511)
    RamChannel(
        id = "isro_space_live",
        serialNumber = 507,
        name = "ISRO Bharat Space (ଭାରତ ମହାକାଶ ଗବେଷଣା)",
        logoText = "ISR",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "145.6K",
        resolution = "1080p FHD",
        currentShow = "ଚନ୍ଦ୍ରଯାନ, ଆଦିତ୍ୟ-ଏଲ୍୧ ଓ ଗଗନଯାନ ମିଶନ (Space Explorer)",
        currentShowCategory = "Space Exploration",
        progressPercent = 0.90f,
        language = "Hindi / English",
        isFeatured = true,
        description = "ISRO's triumphant journeys: Chandrayaan lunar landings, Mangalyaan, and Gaganyaan human spaceflight missions."
    ),
    RamChannel(
        id = "nasa_tv_english",
        serialNumber = 508,
        name = "NASA TV Global (ନାସା ମହାକାଶ ଲାଇଭ)",
        logoText = "NAS",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "92.4K",
        resolution = "1080p FHD",
        currentShow = "International Space Station Live Earth Views",
        currentShowCategory = "ISS Live Stream",
        progressPercent = 0.95f,
        language = "English",
        isFeatured = true,
        description = "Direct 24/7 telecast from the International Space Station orbiting Earth at 28,000 km/h."
    ),
    RamChannel(
        id = "gadget_tech_360",
        serialNumber = 509,
        name = "Gadget & Tech 360 (ଟେକ୍ନୋଲୋଜି ଦୁନିଆ)",
        logoText = "T360",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "74.3K",
        resolution = "1080p FHD",
        currentShow = "ସ୍ମାର୍ଟଫୋନ ତୁଳନା, ଇଲେକ୍ଟ୍ରିକ କାର ଓ ନୂଆ ଗ୍ୟାଜେଟ୍ସ",
        currentShowCategory = "Consumer Tech",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Hands-on flagship phone reviews, wearable electronics, drone testing, and electric vehicles."
    ),
    RamChannel(
        id = "science_frontier_tv",
        serialNumber = 510,
        name = "Science Frontier TV (ବିଜ୍ଞାନ ରହସ୍ୟ)",
        logoText = "SCI",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.2K",
        resolution = "1080p FHD",
        currentShow = "କ୍ୱାଣ୍ଟମ ଫିଜିକ୍ସ, ବ୍ଲାକ ହୋଲ ଓ ସମୟ ଯାତ୍ରା",
        currentShowCategory = "Cosmology",
        progressPercent = 0.65f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Einstein's general relativity, James Webb space telescope photos, wormholes, and multiverse physics."
    ),
    RamChannel(
        id = "ai_robotics_world",
        serialNumber = 511,
        name = "AI & Robotics World (କୃତ୍ରିମ ବୁଦ୍ଧିମତା)",
        logoText = "AIW",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.9K",
        resolution = "1080p FHD",
        currentShow = "ଭବିଷ୍ୟତର ହ୍ୟୁମାନଏଡ୍ ରୋବୋଟ୍ ଓ ଜେନେରେଟିଭ୍ ଏଆଇ",
        currentShowCategory = "Next-Gen AI",
        progressPercent = 0.75f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Artificial general intelligence breakthroughs, humanoid robots, self-driving cars, and cybernetics."
    ),
    // History & Civilization (512 - 515)
    RamChannel(
        id = "history_tv18_heritage",
        serialNumber = 512,
        name = "History TV18 Heritage (ହିଷ୍ଟ୍ରି ଟିଭି୧୮)",
        logoText = "H18",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "112.8K",
        resolution = "1080p FHD",
        currentShow = "ଓମ୍ ଶର୍ମାଙ୍କ ଭାରତ ଇତିହାସ ଓ ପନ୍ ଷ୍ଟାର୍ସ (OMG Yeh Mera India)",
        currentShowCategory = "India History & Curiosities",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "India's greatest stories: OMG! Yeh Mera India, pawn stars, ancient fort engineering and weapons."
    ),
    RamChannel(
        id = "ancient_civilizations_india",
        serialNumber = 513,
        name = "Ancient Bharat Civilizations (ପ୍ରାଚୀନ ଭାରତ)",
        logoText = "ABC",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.4K",
        resolution = "1080p FHD",
        currentShow = "ସିନ୍ଧୁ ଉପତ୍ୟକା ସଭ୍ୟତା, ହରପ୍ପା ଓ ଧୋଲାଭିରା ରହସ୍ୟ",
        currentShowCategory = "Indus Civilization",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Archaeological excavations of Indus Valley, underwater Dwarka, Lothal dockyard, and Vedic towns."
    ),
    RamChannel(
        id = "bharat_historical_monuments",
        serialNumber = 514,
        name = "Monuments of India (ଭାରତର ଐତିହ୍ୟ ସ୍ଥଳୀ)",
        logoText = "MNM",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.3K",
        resolution = "1080p FHD",
        currentShow = "କୁତୁବ ମିନାର, କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର ଓ ଲାଲକିଲ୍ଲା",
        currentShowCategory = "UNESCO World Heritage",
        progressPercent = 0.65f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "Architectural wonders: Taj Mahal, Ellora Kailash temple carved from single rock, and Hampi ruins."
    ),
    RamChannel(
        id = "epic_war_strategies",
        serialNumber = 515,
        name = "Epic War Strategies (ଐତିହାସିକ ଯୁଦ୍ଧ କାହାଣୀ)",
        logoText = "WAR",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.5K",
        resolution = "1080p FHD",
        currentShow = "ଛତ୍ରପତି ଶିବାଜୀ ମହାରାଜ ଗରିଲା ରଣନୀତି ଓ ପାନିପଥ",
        currentShowCategory = "Military Strategies",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = false,
        description = "Battles of Panipat, Chhatrapati Shivaji's Ganimi Kava guerilla tactics, and Maharana Pratap's valor."
    ),
    // Food & Culinary (516 - 520)
    RamChannel(
        id = "food_food_sanjeev",
        serialNumber = 516,
        name = "Food Food (ଫୁଡ୍ ଫୁଡ୍ ସଞ୍ଜୀବ କପୁର)",
        logoText = "FDF",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "93.8K",
        resolution = "1080p FHD",
        currentShow = "ଖାନା ଖଜାନା ଓ ଘରୋଇ ସ୍ୱାଦିଷ୍ଟ ବ୍ୟଞ୍ଜନ ପ୍ରସ୍ତୁତି",
        currentShowCategory = "Indian Gastronomy",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Master Chef Sanjeev Kapoor presenting restaurant secret recipes, healthy biryanis, and sweets."
    ),
    RamChannel(
        id = "masterchef_kitchen_india",
        serialNumber = 517,
        name = "MasterChef Kitchen India (ମାଷ୍ଟରସେଫ ଟିଭି)",
        logoText = "MCK",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "84.2K",
        resolution = "1080p FHD",
        currentShow = "ଇନୋଭେଟିଭ୍ ଫ୍ୟୁଜନ ରନ୍ଧନ ଓ ମିଷ୍ଟ୍ରି ବକ୍ସ ଚ୍ୟାଲେଞ୍ଜ",
        currentShowCategory = "Culinary Showdown",
        progressPercent = 0.75f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Intense culinary showdowns with Vikas Khanna, Ranveer Brar, and Garima Arora."
    ),
    RamChannel(
        id = "desi_street_food_safari",
        serialNumber = 518,
        name = "Desi Street Food Safari (ଷ୍ଟ୍ରିଟ୍ ଫୁଡ୍ ସଫାରୀ)",
        logoText = "STR",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "102.6K",
        resolution = "1080p FHD",
        currentShow = "ଦିଲ୍ଲୀ ଚାଟ୍, କୋଲକାତା କାଠି ରୋଲ୍ ଓ କଟକ ଦହିବରା ଆଳୁଦମ",
        currentShowCategory = "Street Food",
        progressPercent = 0.90f,
        language = "Hindi / Odia",
        isFeatured = true,
        description = "Mouthwatering journey through Chandni Chowk parathas, Cuttack Dahi Bara Aloodum, and Mumbai Vada Pav."
    ),
    RamChannel(
        id = "royal_indian_thali",
        serialNumber = 519,
        name = "Royal Indian Thali (ରାଜକୀୟ ଭାରତୀୟ ଥାଳି)",
        logoText = "RYL",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "63.7K",
        resolution = "1080p FHD",
        currentShow = "ରାଜସ୍ଥାନୀ ଦାଲ ବାଟୀ ଚୁର୍ମା ଓ ନବାବୀ ଦମ ବିରିୟାନୀ",
        currentShowCategory = "Royal Cuisines",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Heritage feast recipes from Mewar royal kitchens, Awadhi Nawabs, and Nizams of Hyderabad."
    ),
    RamChannel(
        id = "sweet_delights_india",
        serialNumber = 520,
        name = "Mithai & Sweet Delights (ଭାରତର ମିଠା)",
        logoText = "MTH",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.1K",
        resolution = "1080p FHD",
        currentShow = "ପାହାଳ ରସଗୋଲା, ଛେନାପୋଡ଼ ଓ କୋଲକାତା ସନ୍ଦେଶ",
        currentShowCategory = "Desi Desserts",
        progressPercent = 0.70f,
        language = "Odia / Hindi",
        isFeatured = false,
        description = "Odisha's world famous Pahala Rasagola, baked Chhenapoda, Gulab Jamun, and Kaju Katli."
    ),
    // Travel & Exploration (521 - 525)
    RamChannel(
        id = "travel_xp_india",
        serialNumber = 521,
        name = "TravelXP 4K India (ଟ୍ରାଭେଲ ଏକ୍ସପି)",
        logoText = "TXP",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.4K",
        resolution = "4K Ultra HD",
        currentShow = "Scenic Europe, Goa Beaches & Kerala Backwaters",
        currentShowCategory = "Global Luxury Travel",
        progressPercent = 0.85f,
        language = "English / Hindi",
        isFeatured = true,
        description = "World's leading 4K travel channel highlighting scenic destinations, boutique resorts, and cultures."
    ),
    RamChannel(
        id = "auto_expo_supercars",
        serialNumber = 522,
        name = "Supercars & Auto Expo (ସୁପରକାର୍ସ ଟିଭି)",
        logoText = "CAR",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.2K",
        resolution = "1080p FHD",
        currentShow = "ଫେରାରୀ, ଲାମ୍ବୋର୍ଗିନି ଓ ଭାରତୀୟ ଥାର୍ ଅଫ୍-ରୋଡିଂ",
        currentShowCategory = "Supercars & Off-Road",
        progressPercent = 0.75f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Top speed supercar acceleration, Mahindra Thar mountain 4x4 trails, and luxury automobile reviews."
    ),
    RamChannel(
        id = "himalayan_road_trips",
        serialNumber = 523,
        name = "Himalayan Road Trips (ଲେହ-ଲଦାଖ ଯାତ୍ରା)",
        logoText = "LEH",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.9K",
        resolution = "1080p FHD",
        currentShow = "ମନାଲୀରୁ ଲେହ ବାଇକ୍ ଯାତ୍ରା ଓ ଖାରଦୁଙ୍ଗଲା ପାସ୍ (Khardung La)",
        currentShowCategory = "Mountain Expeditions",
        progressPercent = 0.80f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Royal Enfield bike rides through Spiti Valley, Pangong Tso lake, and high mountain passes."
    ),
    RamChannel(
        id = "indian_railways_journey",
        serialNumber = 524,
        name = "Indian Railways Journey TV (ଭାରତୀୟ ରେଳ ଯାତ୍ରା)",
        logoText = "RLW",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.1K",
        resolution = "1080p FHD",
        currentShow = "ବନ୍ଦେ ଭାରତ ଏକ୍ସପ୍ରେସ୍, ରାଜଧାନୀ ଓ ଦାର୍ଜିଲିଂ ଟୟ ଟ୍ରେନ୍",
        currentShowCategory = "Railfan Expeditions",
        progressPercent = 0.90f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Scenic train cab views of Vande Bharat at 160 km/h, Konkan railway bridges, and steam toy trains."
    ),
    RamChannel(
        id = "offbeat_world_trails",
        serialNumber = 525,
        name = "Offbeat World Trails (ଅଜଣା ଦୁନିଆର ଯାତ୍ରା)",
        logoText = "TRL",
        category = ChannelCategory.INFOTAINMENT,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.6K",
        resolution = "1080p FHD",
        currentShow = "ଆଣ୍ଟାର୍କଟିକା ବରଫ ଯାତ୍ରା ଓ ସାହାରା ମରୁଭୂମି ଅନୁସନ୍ଧାନ",
        currentShowCategory = "Untamed Expeditions",
        progressPercent = 0.60f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Expeditions to Antarctica glaciers, nomadic Sahara caravans, Amazon deep tribes and remote islands."
    )
)
