package com.example.model

/**
 * 25 Kids, Cartoons & Animated Adventures Channels (Serial 401 - 425)
 * Covers:
 * - Chhota Bheem, Motu Patlu, Krishna Balram, Roll No 21, Shiva Super Kid,
 *   Pogo Indian Animation, Cartoon Network Classics, Tenali Raman Stories,
 *   Panchatantra Tale World, Akbar Birbal Animated, Vikram Betal,
 *   Mighty Raju City, Tom and Jerry Comedy, Anime Action India,
 *   Kids Nursery Rhymes 24x7, Junior Science Explorers, Origami & Art Craft,
 *   Gattu Battu Comedy, Vir The Robot Boy, Jungle Book Mowgli,
 *   Ganesha Little Warrior, Kumbh Karan Animated, Shikari Shambu Comic TV,
 *   Suppandi & Friends Fun, Fairy Tales in Hindi.
 */
fun buildKidsChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "chhota_bheem_tv",
        serialNumber = 401,
        name = "Chhota Bheem Dholakpur (ଛୋଟା ଭୀମ)",
        logoText = "BHM",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "132.4K",
        resolution = "1080p FHD",
        currentShow = "ଢୋଲକପୁରରେ ଭୀମ ଓ ଲଡୁ ଚୋର (Chhota Bheem Adventures)",
        currentShowCategory = "Indian Animated Hero",
        progressPercent = 0.85f,
        language = "Hindi / Odia Dub",
        isFeatured = true,
        description = "India's beloved superhero Chhota Bheem, Chutki, Raju, Jaggu and Kalia defending Dholakpur."
    ),
    RamChannel(
        id = "motu_patlu_live",
        serialNumber = 402,
        name = "Motu Patlu Furfuri Nagar (ମୋଟୁ ପତଲୁ)",
        logoText = "MPL",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "124.9K",
        resolution = "1080p FHD",
        currentShow = "ସମୋସା ଧମାକା ଓ ଜନ ସାହେବଙ୍କ ନୂଆ ଚାଲ (Furfuri Nagar)",
        currentShowCategory = "Slapstick Comedy",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Motu Patlu, Dr. Jhatka's inventions, Ghasitaram's Samosas, and Inspector Chingum in Furfuri Nagar."
    ),
    RamChannel(
        id = "krishna_balram_animated",
        serialNumber = 403,
        name = "Little Krishna & Balram (ଲିଟିଲ କୃଷ୍ଣ)",
        logoText = "KBL",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.5K",
        resolution = "1080p FHD",
        currentShow = "ମାଖନ ଚୋର କୃଷ୍ଣ ଓ କାଳୀୟ ଦମନ (Little Krishna Adventures)",
        currentShowCategory = "Mythological Animation",
        progressPercent = 0.80f,
        language = "Hindi / Odia",
        isFeatured = true,
        description = "Award-winning 3D animation chronicling childhood adventures of Little Krishna in Vrindavan."
    ),
    RamChannel(
        id = "roll_no_21_tv",
        serialNumber = 404,
        name = "Roll No 21 Kris (ରୋଲ୍ ନମ୍ବର ୨୧)",
        logoText = "R21",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "87.3K",
        resolution = "1080p FHD",
        currentShow = "କନିଷ୍କର ନୂଆ ପ୍ଲାନ ଓ କ୍ରିସର ମ୍ୟାଜିକ (Kris vs Kanishk)",
        currentShowCategory = "Modern Mythic Adventure",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Modern school incarnation where Principal Kanishk tries wicked schemes against the brilliant Kris."
    ),
    RamChannel(
        id = "shiva_super_kid",
        serialNumber = 405,
        name = "Shiva Super Kid (ଶିବା ସାଇକେଲ ହିରୋ)",
        logoText = "SHV",
        category = ChannelCategory.KIDS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "81.6K",
        resolution = "1080p FHD",
        currentShow = "ଭେଦସିଟିରେ ଶିବାର ସୁପର ସାଇକେଲ ଷ୍ଟଣ୍ଟ (Super Shiva)",
        currentShowCategory = "High Action Kids",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Brave child hero Shiva with his flying high-tech supersonic cycle solving crimes in Vedas City."
    ),
    RamChannel(
        id = "pogo_classics",
        serialNumber = 406,
        name = "Pogo Indian Animation (ପୋଗୋ କାର୍ଟୁନ)",
        logoText = "PGO",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.2K",
        resolution = "1080p FHD",
        currentShow = "ଟିଟୋ ବୋବୋ ଓ ମଜାଦାର କାର୍ଟୁନ ଉତ୍ସବ (Pogo Fun Fest)",
        currentShowCategory = "Kids Comedy",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Turner's dedicated kids brand broadcasting vibrant, colorful domestic and global animation."
    ),
    RamChannel(
        id = "cartoon_network_classics",
        serialNumber = 407,
        name = "Cartoon Network Classics (ସିଏନ୍ କ୍ଲାସିକ)",
        logoText = "CNC",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "106.4K",
        resolution = "1080p FHD",
        currentShow = "ବେନ୍ ୧୦, ଡେକ୍ସଟର ଲ୍ୟାବ୍ ଓ ପାୱାରପଫ୍ ଗାର୍ଲ୍ସ",
        currentShowCategory = "Retro Cartoons",
        progressPercent = 0.90f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Golden age animation: Ben 10, Dexter's Laboratory, Courage the Cowardly Dog, and Johnny Bravo."
    ),
    RamChannel(
        id = "tenali_raman_tales",
        serialNumber = 408,
        name = "Tenali Raman Stories (ତେନାଲି ରାମନ କାହାଣୀ)",
        logoText = "TNL",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.8K",
        resolution = "1080p FHD",
        currentShow = "ବିଜୟନଗର ଦରବାରରେ ତେନାଲି ରାମନଙ୍କ ଚତୁରତା",
        currentShowCategory = "Moral Wit Tales",
        progressPercent = 0.60f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "Witty tales of minister Tenali Raman resolving Emperor Krishnadevaraya's trickiest challenges."
    ),
    RamChannel(
        id = "panchatantra_world",
        serialNumber = 409,
        name = "Panchatantra Tale World (ପଞ୍ଚତନ୍ତ୍ର କାହାଣୀ)",
        logoText = "PNC",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.4K",
        resolution = "1080p FHD",
        currentShow = "ସିଂହ ଓ ଚତୁର ଠେକୁଆ, ନୀତି ଶିକ୍ଷା କାହାଣୀସମୂହ",
        currentShowCategory = "Moral Fables",
        progressPercent = 0.70f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "Timeless Vishnu Sharma animal fables teaching friendship, wisdom, and moral ethics to youngsters."
    ),
    RamChannel(
        id = "akbar_birbal_animated",
        serialNumber = 410,
        name = "Akbar Birbal Tales (ଆକବର ବିରବଲ କାହାଣୀ)",
        logoText = "AKB",
        category = ChannelCategory.KIDS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.1K",
        resolution = "1080p FHD",
        currentShow = "ବିରବଲଙ୍କ ଖେଚୁଡ଼ି ଓ ଅସାଧାରଣ ବୁଦ୍ଧି ପ୍ରଦର୍ଶନ",
        currentShowCategory = "Historical Wit",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Birbal's unparalleled wit outsmarting royal court schemers with laughter and fairness."
    ),
    // Additional 15 Kids & Cartoons Channels (411 - 425)
    RamChannel(
        id = "vikram_betal_animated",
        serialNumber = 411,
        name = "Vikram Betal Riddles (ବିକ୍ରମ ବେତାଳ)",
        logoText = "VKB",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.4K",
        resolution = "1080p FHD",
        currentShow = "ରାଜା ବିକ୍ରମାଦିତ୍ୟଙ୍କୁ ବେତାଳର ୨୫ଟି ରହସ୍ୟମୟ ପ୍ରଶ୍ନ",
        currentShowCategory = "Ancient Riddles",
        progressPercent = 0.75f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "The 25 deep ethical dilemmas posed by the ghost Betal to wise King Vikramaditya."
    ),
    RamChannel(
        id = "mighty_raju_city",
        serialNumber = 412,
        name = "Mighty Raju Aryanagar (ମାଇଟି ରାଜୁ)",
        logoText = "MRJ",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "63.9K",
        resolution = "1080p FHD",
        currentShow = "ଆର୍ଯ୍ୟନଗରରେ ମାଇଟି ରାଜୁର ସୁପର ହିରୋ ରକ୍ଷା",
        currentShowCategory = "Superhero Kids",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Four-year-old superhero Raju defending the futuristic city of Aryanagar with dog Moby."
    ),
    RamChannel(
        id = "tom_jerry_comedy",
        serialNumber = 413,
        name = "Tom and Jerry Chase (ଟମ୍ ଏଣ୍ଡ ଜେରୀ)",
        logoText = "TNJ",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "115.3K",
        resolution = "1080p FHD",
        currentShow = "ଟମ୍ ଆଉ ଜେରୀଙ୍କ ଅନବରତ ହସର ଧମାକା (Classic Slapstick)",
        currentShowCategory = "Evergreen Slapstick",
        progressPercent = 0.95f,
        language = "Universal Comic Audio",
        isFeatured = true,
        description = "The world's greatest cat and mouse chase, guaranteed belly laughs for all family ages."
    ),
    RamChannel(
        id = "anime_action_india",
        serialNumber = 414,
        name = "Anime Action India (ଆନିମେ ହିନ୍ଦୀ ଡବ୍)",
        logoText = "ANM",
        category = ChannelCategory.KIDS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "92.8K",
        resolution = "1080p FHD",
        currentShow = "ନାରୁଟୋ, ଡ୍ରାଗନ ବଲ ଜେଡ୍ ହିନ୍ଦୀ (Naruto & DBZ)",
        currentShowCategory = "Shonen Anime",
        progressPercent = 0.85f,
        language = "Hindi Dubbed",
        isFeatured = true,
        description = "Action-packed shonen anime: Naruto ninja fights, Goku's Kamehameha, and Beyblade spin battles."
    ),
    RamChannel(
        id = "kids_nursery_rhymes",
        serialNumber = 415,
        name = "Kids Nursery Rhymes (ଶିଶୁ ଗୀତ ଓ କବିତା)",
        logoText = "RHY",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "86.4K",
        resolution = "1080p FHD",
        currentShow = "ଚନ୍ଦାମାମା ଦୂର କେ, ଲାଲକି କି ରାଣୀ ଓ ଜହ୍ନମାମୁଁ (Rhymes)",
        currentShowCategory = "Toddler Rhymes",
        progressPercent = 0.90f,
        language = "Hindi / Odia / English",
        isFeatured = false,
        description = "Joyful rhymes for toddlers, ABC phonics, numbers 1-100, and sweet bedtime lullabies."
    ),
    RamChannel(
        id = "junior_science_explorers",
        serialNumber = 416,
        name = "Junior Science Explorers (ବିଜ୍ଞାନ ଆବିଷ୍କାର)",
        logoText = "SCI",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.2K",
        resolution = "1080p FHD",
        currentShow = "କାହିଁକି ଆକାଶ ନୀଳ? ମଜାଦାର ବିଜ୍ଞାନ ପରୀକ୍ଷା (Kids Science)",
        currentShowCategory = "Fun Science",
        progressPercent = 0.60f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Interactive fun science experiments, solar system astronomy, and biology for curious minds."
    ),
    RamChannel(
        id = "origami_art_craft",
        serialNumber = 417,
        name = "Origami & Art Craft TV (ଚିତ୍ରାଙ୍କନ ଓ କଳା)",
        logoText = "ART",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.8K",
        resolution = "1080p FHD",
        currentShow = "କାଗଜ ଫୁଲ, ରଙ୍ଗୋଲୀ ଓ ଡ୍ରଇଂ ଶିକ୍ଷା (DIY Art Craft)",
        currentShowCategory = "Creative DIY",
        progressPercent = 0.55f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Paper folding origami, clay modeling, acrylic painting and easy DIY school craft projects."
    ),
    RamChannel(
        id = "gattu_battu_comedy",
        serialNumber = 418,
        name = "Gattu Battu Comedy (ଗଟ୍ଟୁ ବଟ୍ଟୁ)",
        logoText = "GBU",
        category = ChannelCategory.KIDS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.1K",
        resolution = "1080p FHD",
        currentShow = "ଗଟ୍ଟୁର ଷଷ୍ଠ ଇନ୍ଦ୍ରିୟ ଓ ବଟ୍ଟୁର କରାଟେ (Gattu Battu Detective)",
        currentShowCategory = "Detective Comedy",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Detective agency duo Gattu and Battu solving neighborhood mysteries with humorous twists."
    ),
    RamChannel(
        id = "vir_the_robot_boy",
        serialNumber = 419,
        name = "Vir The Robot Boy (ଭିର୍ ଦ ରୋବୋଟ୍)",
        logoText = "VIR",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.6K",
        resolution = "1080p FHD",
        currentShow = "ଡକ୍ଟର ପ୍ରେମ ସହାୟଙ୍କ ରୋବୋଟ୍ ଓ ମ୍ୟାଡ୍ ମ୍ୟାକ୍ସ ଲଢେଇ",
        currentShowCategory = "Robotic Hero",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Humanoid robot boy Vir with superhero powers fighting evil Mad Max to save humanity."
    ),
    RamChannel(
        id = "jungle_book_mowgli",
        serialNumber = 420,
        name = "Jungle Book Mowgli (ଜଙ୍ଗଲ ବୁକ ମୋଗଲି)",
        logoText = "JBK",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "93.4K",
        resolution = "1080p FHD",
        currentShow = "ଜଙ୍ଗଲ ଜଙ୍ଗଲ ବାତ୍ ଚଲି ହୈ, ବାଘିରା ଓ ବାଲୁ ସହ ମୋଗଲି",
        currentShowCategory = "Classic Forest Lore",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Rudyard Kipling's timeless classic: Mowgli raised by wolves, battling ferocious Shere Khan."
    ),
    RamChannel(
        id = "ganesha_little_warrior",
        serialNumber = 421,
        name = "My Friend Ganesha (ବାଳ ଗଣେଶ)",
        logoText = "BLG",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.9K",
        resolution = "1080p FHD",
        currentShow = "ମୋଦକ ପ୍ରେମୀ ବାଳ ଗଣେଶ ଓ ମୂଷିକା ବିଜୟ",
        currentShowCategory = "Spiritual Cartoon",
        progressPercent = 0.80f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "Enchanting animated stories of Bal Ganesha's wisdom, modak feasts, and sweet pranks with Kartikeya."
    ),
    RamChannel(
        id = "kumbh_karan_animated",
        serialNumber = 422,
        name = "Kumbh Karan Fun (କୁମ୍ଭ କରନ ଆନିମେସନ)",
        logoText = "KKN",
        category = ChannelCategory.KIDS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "49.5K",
        resolution = "720p HD",
        currentShow = "କୁମ୍ଭର ଭୋଜନ ପ୍ରେମ ଓ କରନର ଧନୁର୍ବିଦ୍ୟା ମଜାଦାର ଖେଳ",
        currentShowCategory = "Twin Comedy",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Hilarious adventures of twin brothers: food lover Kumbh and energetic archer Karan."
    ),
    RamChannel(
        id = "shikari_shambu_comic",
        serialNumber = 423,
        name = "Shikari Shambu Tinkle (ଶିକାରୀ ସମ୍ଭୁ)",
        logoText = "SHB",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.3K",
        resolution = "1080p FHD",
        currentShow = "ଭୟାଳୁ ଶିକାରୀ ଶମ୍ଭୁଙ୍କ ଅଜବ ବାଘ ଶିକାର ସଫଳତା",
        currentShowCategory = "Comic Strip Lore",
        progressPercent = 0.65f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Tinkle comics legendary accidental hero Shikari Shambu whose sheer luck saves every day."
    ),
    RamChannel(
        id = "suppandi_friends_fun",
        serialNumber = 424,
        name = "Suppandi Fun Club (ସୁପ୍ପଣ୍ଡି କମେଡି)",
        logoText = "SUP",
        category = ChannelCategory.KIDS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "60.7K",
        resolution = "1080p FHD",
        currentShow = "ସୁପ୍ପଣ୍ଡିର ଅକ୍ଷରଶଃ ଅନୁପାଳନ ଓ ମାଲିକଙ୍କ ମୁଣ୍ଡବିନ୍ଧା",
        currentShowCategory = "Tinkle Toons",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = false,
        description = "The innocent village bumpkin Suppandi whose literal interpretation of instructions causes havoc."
    ),
    RamChannel(
        id = "fairy_tales_in_hindi",
        serialNumber = 425,
        name = "Fairy Tales Hindi (ପରୀ ଦେଶର କାହାଣୀ)",
        logoText = "FRY",
        category = ChannelCategory.KIDS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.8K",
        resolution = "1080p FHD",
        currentShow = "ଯାଦୁକରୀ ପରୀ ଓ ସୁନେଲୀ ହରିଣ (Magical Fairy World)",
        currentShowCategory = "Bedtime Stories",
        progressPercent = 0.80f,
        language = "Hindi / Odia",
        isFeatured = false,
        description = "Magical castles, talking animals, fairy godmothers, and inspiring bedtime stories for young dreamers."
    )
)
