package com.example.model

/**
 * 40 Cinema, Movies & Blockbuster Channels (Serial 201 - 240)
 * Covers:
 * - Top Bollywood, Hindi Cinema, South Dubbed Blockbusters, Bhojpuri Hits, Hollywood Dubbed & Classics:
 * - Goldmines, Goldmines Bollywood, B4U Movies, B4U Kadak, Star Gold Thrills, Zee Anmol Cinema,
 *   Colors Cineplex Superhits, Colors Cineplex Bollywood, Sony Wah, Dhinchaak, Rishtey Cineplex,
 *   Manoranjan Movies, Cinema TV India, Maha Movie, Movie Plus, Bflix Movies, ABZY Movies,
 *   Bhojpuri Cinema, B4U Bhojpuri, Dabangg TV, Oscar Movies Bhojpuri, Enterr10 Movies, Box Cinema,
 *   Manoranjan Grand Movies, Superhit Bhojpuri TV, Bhojpuri Dhamaka, Cinema B4U Classic, South Premiere Hindi,
 *   Bollywood Romance 24x7, Thriller Movies India, Action Premiere TV, Hollywood Dubbed Cinema,
 *   Classic 60s Cinema, World Cinema Hindi, Golden Film Club, Filmy TV India, Cinema Bharat HD, etc.
 */
fun buildMoviesChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "goldmines",
        serialNumber = 201,
        name = "Goldmines Telefilms (ଗୋଲ୍ଡମାଇନ୍ସ ହିନ୍ଦୀ)",
        logoText = "GLD",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "142.8K",
        resolution = "1080p FHD",
        currentShow = "ପୁଷ୍ପା: ଦ ରାଇଜ୍ ଓ ସାଉଥ୍ ବ୍ଲକବଷ୍ଟର (Pushpa Hindi)",
        currentShowCategory = "South Blockbuster",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "India's undisputed king of South Indian Hindi dubbed mega blockbusters featuring Allu Arjun, Yash, and Prabhas."
    ),
    RamChannel(
        id = "goldmines_bollywood",
        serialNumber = 202,
        name = "Goldmines Bollywood (ବଲିଉଡ଼ ହିଟ୍ସ)",
        logoText = "GBL",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.4K",
        resolution = "1080p FHD",
        currentShow = "ସୂର୍ଯ୍ୟବଂଶମ ଓ ସୁପରହିଟ୍ ହିନ୍ଦୀ ଚଳଚ୍ଚିତ୍ର",
        currentShowCategory = "Bollywood Classics",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Evergreen Hindi superhits, family action dramas, and iconic Bollywood romantic blockbusters."
    ),
    RamChannel(
        id = "b4u_movies",
        serialNumber = 203,
        name = "B4U Movies (ବି୪ୟୁ ମୁଭିଜ୍)",
        logoText = "B4U",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "105.1K",
        resolution = "1080p FHD",
        currentShow = "କେଜିଏଫ୍ ଚାପ୍ଟର-୧ ଓ ରକି ଭାଇ ହିନ୍ଦୀ ପ୍ରିମିୟର",
        currentShowCategory = "Action Cinema",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "Pioneer in worldwide Bollywood movie broadcasting with massive library of high energy action cinema."
    ),
    RamChannel(
        id = "b4u_kadak",
        serialNumber = 204,
        name = "B4U Kadak (ବି୪ୟୁ କଡ଼କ ସିନେମା)",
        logoText = "KDK",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.6K",
        resolution = "1080p FHD",
        currentShow = "ଦବଙ୍ଗ ରାଉଡି ଓ ଜବରଦସ୍ତ ଏକ୍ସନ ସିନେମା",
        currentShowCategory = "Masala Action",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "High octane Kadak action movies, thrilling chases, and heroic punch dialogues."
    ),
    RamChannel(
        id = "star_gold_thrills",
        serialNumber = 205,
        name = "Star Gold Thrills (ଷ୍ଟାର ଗୋଲ୍ଡ)",
        logoText = "SGT",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "112.3K",
        resolution = "1080p FHD",
        currentShow = "ମାର୍ଭେଲ ଆଭେଞ୍ଜର୍ସ ଓ ହଲିଉଡ୍ ହିନ୍ଦୀ ଡବ୍",
        currentShowCategory = "Hollywood Hindi",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Hollywood sci-fi, Marvel superhero epics, and monster thrillers dubbed in explosive Hindi."
    ),
    RamChannel(
        id = "zee_anmol_cinema",
        serialNumber = 206,
        name = "Zee Anmol Cinema (ଜୀ ଅନମୋଲ ସିନେମା)",
        logoText = "ZAC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "96.7K",
        resolution = "1080p FHD",
        currentShow = "ସିମ୍ବା, ରାଓଡି ରାଠୋର ଓ ଦିଲୱାଲେ (Hit Premiere)",
        currentShowCategory = "Bollywood Superhits",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Zee's beloved free movie channel broadcasting Bollywood's greatest comedic and romantic family films."
    ),
    RamChannel(
        id = "colors_cineplex_superhits",
        serialNumber = 207,
        name = "Colors Cineplex Superhits (କଲର୍ସ ସିନେପ୍ଲେକ୍ସ)",
        logoText = "CCS",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.5K",
        resolution = "1080p FHD",
        currentShow = "ବାହୁବଲୀ ୨: ଦ କନକ୍ଲୁଜନ (Bahubali 2 Hindi)",
        currentShowCategory = "Historic Blockbuster",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "Viacom18's movie destination with grand visual spectacles like Baahubali and RRR."
    ),
    RamChannel(
        id = "colors_cineplex_bollywood",
        serialNumber = 208,
        name = "Colors Cineplex Bollywood (ସିନେପ୍ଲେକ୍ସ ବଲିଉଡ଼)",
        logoText = "CCB",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.4K",
        resolution = "1080p FHD",
        currentShow = "ଜବ୍ ଉଇ ମେଟ୍ ଓ ଚେନ୍ନାଇ ଏକ୍ସପ୍ରେସ୍ (Rom-Com Special)",
        currentShowCategory = "Romantic Comedy",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Pure romantic Bollywood comedies, timeless songs, and family entertainment."
    ),
    RamChannel(
        id = "sony_wah",
        serialNumber = 209,
        name = "Sony Wah (ସୋନି ୱାଃ ମୁଭିଜ୍)",
        logoText = "WAH",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "91.8K",
        resolution = "1080p FHD",
        currentShow = "ଧୂମ୍ ୩ ଓ ସୁଲତାନ (Mega Hit Cinema)",
        currentShowCategory = "Action Thriller",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Sony Pictures Networks' FTA cinema channel with blockbuster hits from Shah Rukh, Salman, and Aamir Khan."
    ),
    RamChannel(
        id = "dhinchaak",
        serialNumber = 210,
        name = "Dhinchaak Movies (ଢିଞ୍ଚାକ୍ ସିନେମା)",
        logoText = "DHK",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "73.2K",
        resolution = "1080p FHD",
        currentShow = "ସାଉଥ୍ କମାଣ୍ଡୋ ଓ ଖିଲାଡ଼ି ସିନେମା",
        currentShowCategory = "South Action",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Full energy Hindi dubbed South Indian mass action films with adrenaline-pumping sequences."
    ),
    RamChannel(
        id = "rishtey_cineplex",
        serialNumber = 211,
        name = "Rishtey Cineplex (ରିସ୍ତେ ସିନେପ୍ଲେକ୍ସ)",
        logoText = "RCX",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.9K",
        resolution = "1080p FHD",
        currentShow = "ଦ୍ରୃଶ୍ୟମ୍ ଓ କାହାନୀ ସସପେନ୍ସ ସିନେମା (Suspense)",
        currentShowCategory = "Thriller & Suspense",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Engaging mystery thrillers, high stake investigations, and gripping drama movies."
    ),
    RamChannel(
        id = "manoranjan_movies",
        serialNumber = 212,
        name = "Manoranjan Movies (ମନୋରଞ୍ଜନ ମୁଭିଜ୍)",
        logoText = "MRM",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.5K",
        resolution = "1080p FHD",
        currentShow = "ହିନ୍ଦୀ ମସାଲା ଫିଲ୍ମ ଉତ୍ସବ (Masala Hits)",
        currentShowCategory = "Bollywood Masala",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Popular FTA movie destination showcasing superhit family and village drama films."
    ),
    RamChannel(
        id = "cinema_tv_india",
        serialNumber = 213,
        name = "Cinema TV India (ସିନେମା ଟିଭି)",
        logoText = "CTV",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.1K",
        resolution = "1080p FHD",
        currentShow = "୯୦ ଦଶକର ସୁପରହିଟ୍ ଫିଲ୍ମ ମେଳା",
        currentShowCategory = "90s Golden Era",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Dedicated to the unforgettable 1990s decade of Govinda, Akshay Kumar, and Sunny Deol blockbusters."
    ),
    RamChannel(
        id = "maha_movie",
        serialNumber = 214,
        name = "Maha Movie (ମହା ମୁଭି ହିନ୍ଦୀ)",
        logoText = "MMV",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "55.8K",
        resolution = "720p HD",
        currentShow = "ମହା ଏକ୍ସନ ଫାଇଟ୍ ସିନେମା (Action Fest)",
        currentShowCategory = "Desi Action",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Free Dish favorite channel delivering action packed punch-dialogue blockbusters all day."
    ),
    RamChannel(
        id = "movie_plus",
        serialNumber = 215,
        name = "Movie Plus (ମୁଭି ପ୍ଲସ୍)",
        logoText = "MVP",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.4K",
        resolution = "720p HD",
        currentShow = "ସୁପରହିଟ୍ ଡବ୍ଡ ଧମାକା",
        currentShowCategory = "Dubbed Movies",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Non-stop movie entertainment with regional dubbed superhits and Bollywood comedies."
    ),
    RamChannel(
        id = "bflix_movies",
        serialNumber = 216,
        name = "Bflix Movies (ବିଫ୍ଲିକ୍ସ ସିନେମା)",
        logoText = "BFX",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.7K",
        resolution = "720p HD",
        currentShow = "ହଲିଉଡ୍ ହିନ୍ଦୀ ସସପେନ୍ସ ଆଣ୍ଡ ଥ୍ରୀଲର",
        currentShowCategory = "Sci-Fi & Thriller",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Creature features, disaster movies, and thrilling alien invasions dubbed in easy Hindi."
    ),
    RamChannel(
        id = "abzy_movies",
        serialNumber = 217,
        name = "ABZY Movies (ଏବିଜେଡୱାଇ ମୁଭିଜ୍)",
        logoText = "ABZ",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.3K",
        resolution = "720p HD",
        currentShow = "ଧୁଆଁଧାର ଆକ୍ସନ୍ ଫିଲ୍ମସ (Action 24x7)",
        currentShowCategory = "Action Hindi",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Free-to-air Indian movie channel broadcasting non-stop popular action dramas."
    ),
    RamChannel(
        id = "bhojpuri_cinema",
        serialNumber = 218,
        name = "Bhojpuri Cinema (ଭୋଜପୁରୀ ସିନେମା ୨୪x୭)",
        logoText = "BJC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "86.4K",
        resolution = "1080p FHD",
        currentShow = "ଦିନେଶ ଲାଲ ଯାଦବ (ନିରହୁଆ) ଓ ଖେସାରି ଲାଲ ବ୍ଲକବଷ୍ଟର",
        currentShowCategory = "Bhojpuri Blockbuster",
        progressPercent = 0.85f,
        language = "Bhojpuri",
        isFeatured = true,
        description = "India's No.1 Bhojpuri movie channel featuring Nirahua, Pawan Singh, and Khesari Lal Yadav."
    ),
    RamChannel(
        id = "b4u_bhojpuri",
        serialNumber = 219,
        name = "B4U Bhojpuri (ବି୪ୟୁ ଭୋଜପୁରୀ)",
        logoText = "B4B",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "79.8K",
        resolution = "1080p FHD",
        currentShow = "ପବନ ସିଂହ ଓ ଆମ୍ରପାଲୀ ଦୁବେ ସୁପରହିଟ୍ ଫିଲ୍ମ",
        currentShowCategory = "Bhojpuri Hits",
        progressPercent = 0.75f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "B4U Network's premier Bhojpuri cinema broadcaster bringing top grossing films."
    ),
    RamChannel(
        id = "dabangg_tv",
        serialNumber = 220,
        name = "Dabangg TV (ଦବଙ୍ଗ ଭୋଜପୁରୀ)",
        logoText = "DBG",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.2K",
        resolution = "720p HD",
        currentShow = "ଦବଙ୍ଗ ହିଟ୍ସ ଓ ଲୋକପ୍ରିୟ ଭୋଜପୁରୀ ଗୀତ",
        currentShowCategory = "Regional Movies",
        progressPercent = 0.60f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "Power-packed Bhojpuri cinema and high-tempo musical item hits."
    ),
    RamChannel(
        id = "oscar_movies_bhojpuri",
        serialNumber = 221,
        name = "Oscar Movies Bhojpuri (ଓସ୍କାର ଭୋଜପୁରୀ)",
        logoText = "OSC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.6K",
        resolution = "720p HD",
        currentShow = "ଭୋଜପୁରିଆ ତଡ଼କା ଓ ସିନେମା ସୁପରଷ୍ଟାର୍ସ",
        currentShowCategory = "Bhojpuri Masala",
        progressPercent = 0.65f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "Bhojpuri cinema classics, comedy sketches, and rustic folk entertainment."
    ),
    RamChannel(
        id = "enterr10_movies",
        serialNumber = 222,
        name = "Enterr10 Movies (ଏଣ୍ଟରଟେନ୍ ମୁଭିଜ୍)",
        logoText = "E10M",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.4K",
        resolution = "1080p FHD",
        currentShow = "ହିନ୍ଦୀ ଏକ୍ସନ ଓ ସସ୍ପେନ୍ସ ଚଳଚ୍ଚିତ୍ର",
        currentShowCategory = "Action Cinema",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Popular FTA movie destination with nonstop Hindi dubbed blockbusters."
    ),
    RamChannel(
        id = "box_cinema",
        serialNumber = 223,
        name = "Box Cinema (ବକ୍ସ ସିନେମା)",
        logoText = "BOX",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.9K",
        resolution = "720p HD",
        currentShow = "ସୁପରହିଟ୍ ଏକ୍ସନ୍ ଓ ରୋମାଞ୍ଚକର ଫିଲ୍ମସ",
        currentShowCategory = "Entertainment Cinema",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Free Dish Hindi movie channel offering masala comedy and martial arts movies."
    ),
    RamChannel(
        id = "classic_cinema_club",
        serialNumber = 224,
        name = "Classic Hindi Cinema (କ୍ଲାସିକ୍ ହିନ୍ଦୀ ସିନେମା)",
        logoText = "CLC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.1K",
        resolution = "1080p FHD",
        currentShow = "ଗୁରୁଦତ୍ତ, ରାଜ କପୁର ଓ ଦିଲୀପ କୁମାର ଫିଲ୍ମ ଫେଷ୍ଟିଭାଲ",
        currentShowCategory = "Black & White Golden Era",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Tribute to the golden foundation of Indian cinema: Mughal-e-Azam, Pyaasa, Sholay, and Mother India."
    ),
    // Additional 16 Cinema Channels (225 - 240)
    RamChannel(
        id = "manoranjan_grand_movies",
        serialNumber = 225,
        name = "Manoranjan Grand Movies (ଗ୍ରାଣ୍ଡ ସିନେମା)",
        logoText = "MGM",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "49.3K",
        resolution = "1080p FHD",
        currentShow = "ସାଉଥ୍ ଇଣ୍ଡିଆନ୍ ଆକ୍ସନ ହିଟ୍ସ (South Action)",
        currentShowCategory = "South Indian Hindi",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "High definition South Indian action epics dubbed in Hindi with pulse pounding fights."
    ),
    RamChannel(
        id = "superhit_bhojpuri_tv",
        serialNumber = 226,
        name = "Superhit Bhojpuri TV (ସୁପରହିଟ୍ ଭୋଜପୁରୀ)",
        logoText = "SBJ",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.2K",
        resolution = "720p HD",
        currentShow = "ଭୋଜପୁରୀ ରଙ୍ଗାରଙ୍ଗ ଚଳଚ୍ଚିତ୍ର ଓ ମନୋରଞ୍ଜନ",
        currentShowCategory = "Bhojpuri Cinema",
        progressPercent = 0.70f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "Engaging Bhojpuri cinema celebrating rural folklore, comedy, and vibrant family celebrations."
    ),
    RamChannel(
        id = "bhojpuri_dhamaka",
        serialNumber = 227,
        name = "Bhojpuri Dhamaka (ଭୋଜପୁରୀ ଧମାକା)",
        logoText = "BDH",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.8K",
        resolution = "720p HD",
        currentShow = "ରବି କିସନ ଓ ମନୋଜ ତିୱାରୀ କ୍ଲାସିକ୍ ହିଟ୍ସ",
        currentShowCategory = "Classic Bhojpuri",
        progressPercent = 0.60f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "Early Bhojpuri superstars Ravi Kishan, Manoj Tiwari, and Sharda Sinha songs and movies."
    ),
    RamChannel(
        id = "cinema_b4u_classic",
        serialNumber = 228,
        name = "B4U Classic Movies (ବି୪ୟୁ କ୍ଲାସିକ୍)",
        logoText = "BCL",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.4K",
        resolution = "1080p FHD",
        currentShow = "୭୦ ଓ ୮୦ ଦଶକର ବ୍ଲକବଷ୍ଟର ଚଳଚ୍ଚିତ୍ର",
        currentShowCategory = "70s & 80s Hits",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Timeless classics from Rajesh Khanna, Amitabh Bachchan, and Dharmendra."
    ),
    RamChannel(
        id = "south_premiere_hindi",
        serialNumber = 229,
        name = "South Premiere Hindi (ସାଉଥ୍ ପ୍ରିମିୟର)",
        logoText = "SPH",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.1K",
        resolution = "1080p FHD",
        currentShow = "ତେଲୁଗୁ, ତାମିଲ୍ ମେଗା ହିଟ୍ ହିନ୍ଦୀ ପ୍ରିମିୟର",
        currentShowCategory = "Mega Premiere",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "First time on television South blockbusters dubbed with top dubbing artists."
    ),
    RamChannel(
        id = "bollywood_romance_247",
        serialNumber = 230,
        name = "Bollywood Romance 24x7 (ରୋମାଣ୍ଟିକ ସିନେମା)",
        logoText = "ROM",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.4K",
        resolution = "1080p FHD",
        currentShow = "ଦିଲୱାଲେ ଦୁଲହନିଆ ଲେ ଜାୟେଙ୍ଗେ ଓ କୁଛ୍ କୁଛ୍ ହୋତା ହୈ",
        currentShowCategory = "All-Time Romance",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Love stories that defined generations with unforgettable melodies and scenic foreign locations."
    ),
    RamChannel(
        id = "thriller_movies_india",
        serialNumber = 231,
        name = "Thriller Movies India (ରହସ୍ୟ ଓ ଥ୍ରୀଲର)",
        logoText = "THM",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "66.8K",
        resolution = "1080p FHD",
        currentShow = "କ୍ରାଇମ୍, ସସ୍ପେନ୍ସ ଓ ମର୍ଡର ମିଷ୍ଟ୍ରି ସିନେମା",
        currentShowCategory = "Suspense Mystery",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Edge-of-the-seat nail-biting thrillers, locked-room mysteries, and investigative crime cinema."
    ),
    RamChannel(
        id = "action_premiere_tv",
        serialNumber = 232,
        name = "Action Premiere TV (ଆକ୍ସନ ପ୍ରିମିୟର)",
        logoText = "ACT",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "75.3K",
        resolution = "1080p FHD",
        currentShow = "ମାର୍ଶାଲ ଆର୍ଟସ ଓ ହଲିଉଡ୍ ଆକ୍ସନ ଡବ୍",
        currentShowCategory = "High Action",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Hand-to-hand combat, car explosions, gun battles and superhero stunts in full HD."
    ),
    RamChannel(
        id = "hollywood_dubbed_cinema",
        serialNumber = 233,
        name = "Hollywood Dubbed Cinema (ହଲିଉଡ୍ ହିନ୍ଦୀ ଡବ୍)",
        logoText = "HWD",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "83.7K",
        resolution = "1080p FHD",
        currentShow = "ଜୁରାସିକ ପାର୍କ ଓ ଗଡଜିଲା ଭର୍ସେସ କଙ୍ଗ",
        currentShowCategory = "Sci-Fi Dubbed",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Biggest worldwide Hollywood blockbusters dubbed in crisp, engaging Hindi dialogue."
    ),
    RamChannel(
        id = "classic_60s_cinema",
        serialNumber = 234,
        name = "Classic 60s Cinema (୬୦ ଦଶକର ସିନେମା)",
        logoText = "C60",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "45.2K",
        resolution = "1080p FHD",
        currentShow = "ଶମ୍ମୀ କପୁର, ଦେବ ଆନନ୍ଦ ଓ ବୈଜୟନ୍ତୀମାଲା ହିଟ୍ସ",
        currentShowCategory = "60s Golden Era",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "The vibrant, musical 1960s with iconic songs from Shankar-Jaikishan and SD Burman."
    ),
    RamChannel(
        id = "world_cinema_hindi",
        serialNumber = 235,
        name = "World Cinema Hindi (ବିଶ୍ୱ ସିନେମା ହିନ୍ଦୀ)",
        logoText = "WCH",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "42.9K",
        resolution = "1080p FHD",
        currentShow = "କୋରିଆନ, ଚାଇନିଜ୍ ଓ ୟୁରୋପିଆନ୍ ଚଳଚ୍ଚିତ୍ର (Dubbed)",
        currentShowCategory = "World Cinema",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Internationally acclaimed foreign films, Korean drama films and martial arts dubbed in Hindi."
    ),
    RamChannel(
        id = "golden_film_club",
        serialNumber = 236,
        name = "Golden Film Club (ସ୍ୱର୍ଣ୍ଣିମ ଚଳଚ୍ଚିତ୍ର)",
        logoText = "GFC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.1K",
        resolution = "1080p FHD",
        currentShow = "ସତ୍ୟଜିତ ରାୟ ଓ ବିମଳ ରାୟ ମାଷ୍ଟରପିସ୍ ସିନେମା",
        currentShowCategory = "Art & Parallel Cinema",
        progressPercent = 0.70f,
        language = "Hindi / Bengali",
        isFeatured = false,
        description = "Award-winning parallel cinema, realistic societal stories that gained global acclaim."
    ),
    RamChannel(
        id = "filmy_tv_india",
        serialNumber = 237,
        name = "Filmy TV India (ଫିଲ୍ମି ଟିଭି ହିନ୍ଦୀ)",
        logoText = "FLM",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.4K",
        resolution = "720p HD",
        currentShow = "ବଲିଉଡ଼ ଗପସପ ଓ ଚଳଚ୍ଚିତ୍ର ସମୀକ୍ଷା",
        currentShowCategory = "Behind The Scenes",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Behind the scenes shooting moments, director interviews, and weekend movie marathon."
    ),
    RamChannel(
        id = "cinema_bharat_hd",
        serialNumber = 238,
        name = "Cinema Bharat HD (ସିନେମା ଭାରତ)",
        logoText = "CBH",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "60.5K",
        resolution = "1080p FHD",
        currentShow = "ଭାରତୀୟ ସ୍ୱାଧୀନତା ଓ ଐତିହାସିକ ଫିଲ୍ମସ",
        currentShowCategory = "Patriotic & Historic",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Patriotic films: Border, LOC Kargil, The Legend of Bhagat Singh, and historical biopics."
    ),
    RamChannel(
        id = "super_cinema_hd",
        serialNumber = 239,
        name = "Super Cinema HD (ସୁପର ସିନେମା)",
        logoText = "SCN",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.9K",
        resolution = "1080p FHD",
        currentShow = "ଫ୍ୟାମିଲି କମେଡି ମୁଭି ଧମାକା (Hera Pheri Special)",
        currentShowCategory = "Comedy Blockbuster",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Laughter riot comedy movies: Hera Pheri, Dhamaal, Welcome, and Golmaal."
    ),
    RamChannel(
        id = "mega_cinema_247",
        serialNumber = 240,
        name = "Mega Cinema 24x7 (ମେଗା ସିନେମା)",
        logoText = "MGC",
        category = ChannelCategory.MOVIES,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.1K",
        resolution = "1080p FHD",
        currentShow = "ମେଗା ଷ୍ଟାର ଚଳଚ୍ଚିତ୍ର ମହୋତ୍ସବ",
        currentShowCategory = "Mega Blockbusters",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "24x7 continuous high-definition movie marathon for true cinema connoisseurs."
    )
)
