package com.example.model

/**
 * 35 24/7 Music Television Channels (Serial 321 - 355)
 * Covers:
 * - Bollywood Chartbusters, Punjabi Beats, 90s Nostalgia, Indipop, Sufi & Ghazals,
 *   Desi Hip-Hop, Classical Ragas, Regional Melodies:
 * - 9XM, 9X Jalwa, Mastiii TV, B4U Music, MTV Beats, Zing TV, 9X Tashan, Balle Balle TV,
 *   Pitaara TV, ShowBox TV, Music India, Desi Hip Hop TV, Sufi & Ghazal Sanctuary,
 *   Retro Bollywood 70s, Indipop Live, 9X Jhakaas, Haryanvi Hits TV, Bhojpuri Sangeet 24x7,
 *   Folk Music India, Romantic Hits 24x7, Club Dance Beats, EDM Festival TV, Ghazal Mehfil Live,
 *   Classical Ragas TV, Bollywood Party Mix, Acoustic Guitar Chill, Desi Lo-Fi Beats, Qawwali Live TV,
 *   Golden 60s Bollywood, 90s Romantic Duets, Instrumental Sitar & Flute, Bengali Melodies TV,
 *   Tamil Beats 24x7, Telugu Hits Music, Kannada Sangeetha.
 */
fun buildMusicChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "nine_xm",
        serialNumber = 321,
        name = "9XM Music (୯ଏକ୍ସଏମ୍ ସଙ୍ଗୀତ)",
        logoText = "9XM",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "118.9K",
        resolution = "1080p FHD",
        currentShow = "ବଲିଉଡ଼ ଟପ୍ ୧୦ ଓ ଭିଗେଶ-ବାଡେ-ଛୋଟେ (9XM Top Hits)",
        currentShowCategory = "Bollywood Chartbusters",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "India's favorite youth music channel with animated characters Bade-Chhote, Bheegi Billi, and hits."
    ),
    RamChannel(
        id = "nine_x_jalwa",
        serialNumber = 322,
        name = "9X Jalwa (୯ଏକ୍ସ ଜଲୱା ରେଟ୍ରୋ)",
        logoText = "JLW",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "92.4K",
        resolution = "1080p FHD",
        currentShow = "୯୦ ଓ ୨୦୦୦ ଦଶକର ସଦାବହାର ଗୀତ (90s Forever Hits)",
        currentShowCategory = "90s Bollywood Classics",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Forever Young 90s and 2000s Bollywood melodies from Kumar Sanu, Alka Yagnik, and Udit Narayan."
    ),
    RamChannel(
        id = "mastiii_tv",
        serialNumber = 323,
        name = "Mastiii TV (ମସ୍ତୀ ଟିଭି ହିନ୍ଦୀ)",
        logoText = "MST",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "104.7K",
        resolution = "1080p FHD",
        currentShow = "ମସ୍ତୀ କ୍ଲବ ଡାନ୍ସ ଓ ସୁପରହିଟ୍ ସଙ୍ଗୀତ (Party Beats)",
        currentShowCategory = "Party & Dance Music",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "India's top ranking music television channel featuring nonstop dance music, celebrity gossip and laughs."
    ),
    RamChannel(
        id = "b4u_music",
        serialNumber = 324,
        name = "B4U Music (ବି୪ୟୁ ମ୍ୟୁଜିକ୍)",
        logoText = "B4M",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "87.1K",
        resolution = "1080p FHD",
        currentShow = "ଆୱାଜ ଦେ କାହାଁ ହୈ ଓ ବଲିଉଡ଼ ବିଟ୍ସ (Morning Melodies)",
        currentShowCategory = "Bollywood Melodies",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Global Indian music destination featuring evergreen soundtracks, indie pop, and fresh talent."
    ),
    RamChannel(
        id = "mtv_beats",
        serialNumber = 325,
        name = "MTV Beats (ଏମଟିଭି ବିଟ୍ସ)",
        logoText = "BTS",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.8K",
        resolution = "1080p FHD",
        currentShow = "ବ୍ଲଡ୍ ପମ୍ପିଂ ବିଟ୍ସ ଓ ଲଭ୍ ଗୀତ (MTV Blood Beats)",
        currentShowCategory = "Youth & Pop Music",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Viacom18's 24x7 Hindi music channel for the youth, curating romantic tunes, rap, and party anthems."
    ),
    RamChannel(
        id = "zing_tv",
        serialNumber = 326,
        name = "Zing TV (ଜିଙ୍ଗ୍ ସଙ୍ଗୀତ)",
        logoText = "ZNG",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.3K",
        resolution = "1080p FHD",
        currentShow = "ପ୍ୟାର ତୁନେ କ୍ୟା କିୟା ଓ ଟ୍ରେଣ୍ଡିଂ ମ୍ୟୁଜିକ୍",
        currentShowCategory = "Romance & Beats",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Zee Entertainment's youth lifestyle and music brand featuring romantic shows and modern trends."
    ),
    RamChannel(
        id = "nine_x_tashan",
        serialNumber = 327,
        name = "9X Tashan (୯ଏକ୍ସ ତସନ୍ ପଞ୍ଜାବୀ)",
        logoText = "TSH",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.4K",
        resolution = "1080p FHD",
        currentShow = "ସିଦ୍ଧୁ ମୁସେୱାଲା, ଦିଲଜିତ ଦୋସାଞ୍ଜ ସୁପରହିଟ୍ସ (Punjabi Hits)",
        currentShowCategory = "Punjabi Bhangra & Hip-Hop",
        progressPercent = 0.85f,
        language = "Punjabi",
        isFeatured = true,
        description = "Unstoppable Punjabi hit music channel bringing Diljit Dosanjh, AP Dhillon, and Karan Aujla tracks."
    ),
    RamChannel(
        id = "balle_balle_tv",
        serialNumber = 328,
        name = "Balle Balle TV (ବଲ୍ଲେ ବଲ୍ଲେ ପଞ୍ଜାବୀ)",
        logoText = "BLB",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.1K",
        resolution = "720p HD",
        currentShow = "ଭାଙ୍ଗଡ଼ା ବୀଟ୍ସ ଓ ଲୋକଗୀତ (Bhangra Beats)",
        currentShowCategory = "Bhangra & Folk",
        progressPercent = 0.75f,
        language = "Punjabi",
        isFeatured = false,
        description = "High spirit Punjabi folk music, dhol rhythms, and wedding celebration tunes."
    ),
    RamChannel(
        id = "pitaara_tv",
        serialNumber = 329,
        name = "Pitaara TV (ପିତାରା ପଞ୍ଜାବୀ ସଙ୍ଗୀତ)",
        logoText = "PTR",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "55.8K",
        resolution = "1080p FHD",
        currentShow = "ପଞ୍ଜାବୀ ଫିଲ୍ମ ମ୍ୟୁଜିକ୍ ଓ ଇଣ୍ଟରଭ୍ୟୁ (Pitaara Live)",
        currentShowCategory = "Punjabi Cinema Music",
        progressPercent = 0.65f,
        language = "Punjabi",
        isFeatured = false,
        description = "Punjabi cinema musical box featuring movie hits, star interactions, and viral singles."
    ),
    RamChannel(
        id = "showbox_tv",
        serialNumber = 330,
        name = "ShowBox TV (ସୋବକ୍ସ ମ୍ୟୁଜିକ୍)",
        logoText = "SHB",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.3K",
        resolution = "1080p FHD",
        currentShow = "ସ୍ୱାଗ୍ ଭାରତ ଓ ଦେଶୀ ଟ୍ରେଣ୍ଡ୍ସ (Swag Bharat)",
        currentShowCategory = "Indie & Bollywood",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Modern multi-genre music channel celebrating Hindi pop, Bengali, and Haryanvi viral sensations."
    ),
    RamChannel(
        id = "music_india",
        serialNumber = 331,
        name = "Music India (ମ୍ୟୁଜିକ୍ ଇଣ୍ଡିଆ)",
        logoText = "MSI",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "49.6K",
        resolution = "720p HD",
        currentShow = "ଭାରତୀୟ ସଙ୍ଗୀତ ଯାତ୍ରା (All India Melodies)",
        currentShowCategory = "Pan-India Melodies",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Melodious blend of regional compositions, classic playback legends, and acoustic music."
    ),
    RamChannel(
        id = "desi_hip_hop_tv",
        serialNumber = 332,
        name = "Desi Hip Hop TV (ଦେଶୀ ରାପ୍ ସଙ୍ଗୀତ)",
        logoText = "DHH",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.7K",
        resolution = "1080p FHD",
        currentShow = "ଗଲ୍ଲୀ ବଏ, ଡିଭାଇନ୍, ଏମିୱେ ଓ ରଫ୍ତାର ହିପ୍-ହପ୍",
        currentShowCategory = "Indian Rap & Cyphers",
        progressPercent = 0.80f,
        language = "Hindi / Punjabi",
        isFeatured = true,
        description = "India's booming underground rap movement, cyphers, lyrical beat battles and hip-hop culture."
    ),
    RamChannel(
        id = "sufi_ghazal_tv",
        serialNumber = 333,
        name = "Sufi & Ghazal Sanctuary (ସୂଫୀ ଓ ଗଜଲ)",
        logoText = "SFG",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.4K",
        resolution = "1080p FHD",
        currentShow = "ନୁସରତ ଫତେହ ଅଲୀ ଖାନ ଓ ଜଗଜିତ ସିଂ ଗଜଲ (Soulful Sufi)",
        currentShowCategory = "Sufi & Ghazals",
        progressPercent = 0.90f,
        language = "Hindi / Urdu",
        isFeatured = true,
        description = "Soul-stirring poetry, qawwalis, and timeless ghazals from Jagjit Singh, Nusrat, and Rahat Fateh Ali Khan."
    ),
    RamChannel(
        id = "retro_bollywood_70s",
        serialNumber = 334,
        name = "Retro Bollywood 70s & 80s (ସ୍ୱର୍ଣ୍ଣିମ ଗୀତ)",
        logoText = "R70",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "63.8K",
        resolution = "1080p FHD",
        currentShow = "କିଶୋର କୁମାର, ମହମ୍ମଦ ରଫି ଓ ଲତା ମଙ୍ଗେସକର",
        currentShowCategory = "Golden Legends",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Golden era tribute channel featuring Kishore Kumar, Mohd Rafi, Lata Mangeshkar, and Asha Bhosle."
    ),
    RamChannel(
        id = "indipop_live",
        serialNumber = 335,
        name = "Indipop Live (ଇଣ୍ଡିପପ୍ ମ୍ୟୁଜିକ୍)",
        logoText = "POP",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "46.2K",
        resolution = "1080p FHD",
        currentShow = "ଇଣ୍ଡିଆନ୍ ବ୍ୟାଣ୍ଡ୍ସ ଓ ୟୁଫୋରିଆ, ସିଲ୍କ ରୁଟ୍ ହିଟ୍ସ",
        currentShowCategory = "Indian Pop & Bands",
        progressPercent = 0.60f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Memories of the Indipop revolution: Euphoria, Lucky Ali, Alisha Chinai, and modern indie music."
    ),
    // Additional 20 Music Channels (336 - 355)
    RamChannel(
        id = "nine_x_jhakaas",
        serialNumber = 336,
        name = "9X Jhakaas (୯ଏକ୍ସ ଝକାସ ମରାଠୀ)",
        logoText = "JHK",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.4K",
        resolution = "1080p FHD",
        currentShow = "ଲାବଣୀ, କୋଳିଗୀତ ଓ ମରାଠୀ ଚିତ୍ରପଟ ସଙ୍ଗୀତ",
        currentShowCategory = "Marathi Music",
        progressPercent = 0.70f,
        language = "Marathi",
        isFeatured = false,
        description = "Maharashtra's premier 24/7 Marathi music television channel playing Lavani, film hits and pop."
    ),
    RamChannel(
        id = "haryanvi_hits_tv",
        serialNumber = 337,
        name = "Haryanvi Hits TV (ହରିୟାଣବୀ ବିଟ୍ସ)",
        logoText = "HRY",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.8K",
        resolution = "1080p FHD",
        currentShow = "ସପନା ଚୌଧୁରୀ, ରେଣୁକା ପନୱାର ଓ ୫୨ ଗଜ କା ଦମନ",
        currentShowCategory = "Haryanvi Dance",
        progressPercent = 0.85f,
        language = "Haryanvi",
        isFeatured = true,
        description = "High bass Haryanvi dance beats, Sapna Choudhary stages, and 52 Gaj Ka Daman viral sensations."
    ),
    RamChannel(
        id = "bhojpuri_sangeet_247",
        serialNumber = 338,
        name = "Bhojpuri Sangeet 24x7 (ଭୋଜପୁରୀ ସଙ୍ଗୀତ)",
        logoText = "BJS",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.1K",
        resolution = "1080p FHD",
        currentShow = "ଲଲିପପ୍ ଲାଗେଲୁ ଓ ସୁପରହିଟ୍ ଭୋଜପୁରୀ ଗୀତ",
        currentShowCategory = "Bhojpuri Dance Hits",
        progressPercent = 0.80f,
        language = "Bhojpuri",
        isFeatured = false,
        description = "Non-stop energetic Bhojpuri celebration music, Pawan Singh, Khesari Lal, and wedding folk beats."
    ),
    RamChannel(
        id = "folk_music_india",
        serialNumber = 339,
        name = "Folk Music India (ଭାରତୀୟ ଲୋକଗୀତ)",
        logoText = "FLK",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "43.5K",
        resolution = "1080p FHD",
        currentShow = "ରାଜସ୍ଥାନୀ ମାଙ୍ଗନିୟାର ଓ ବାଉଲ ଗୀତି (Folk Masters)",
        currentShowCategory = "Traditional Folk",
        progressPercent = 0.65f,
        language = "Multilingual",
        isFeatured = false,
        description = "Preserving authentic Indian folk instruments: Sarangi, Ektara, Dholak, and tribal harvest songs."
    ),
    RamChannel(
        id = "romantic_hits_247",
        serialNumber = 340,
        name = "Romantic Hits 24x7 (ପ୍ରେମ ଗୀତ ୨୪x୭)",
        logoText = "RMC",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.6K",
        resolution = "1080p FHD",
        currentShow = "ଅରିଜିତ ସିଂହ ଓ ଆତିଫ ଅସଲମ ରୋମାଣ୍ଟିକ ସ୍ପେସାଲ",
        currentShowCategory = "Romantic Ballads",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "Arijit Singh, Atif Aslam, Mohit Chauhan, and Shreya Ghoshal romantic soul-stirring melodies."
    ),
    RamChannel(
        id = "club_dance_beats",
        serialNumber = 341,
        name = "Club Dance Beats (କ୍ଲବ ଡାନ୍ସ ବିଟ୍ସ)",
        logoText = "CLB",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "73.2K",
        resolution = "1080p FHD",
        currentShow = "ଡିଜେ ରିମିକ୍ସ ଓ ବଲିଉଡ଼ କ୍ଲବ ନାଇଟ୍ (DJ Remix)",
        currentShowCategory = "Party DJ Remix",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = false,
        description = "DJ Chetas, Nucleya, and high BPM party mixes transforming your living room into a dance club."
    ),
    RamChannel(
        id = "edm_festival_tv",
        serialNumber = 342,
        name = "EDM Festival TV (ଇଡିଏମ ଫେଷ୍ଟିଭାଲ)",
        logoText = "EDM",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.9K",
        resolution = "1080p FHD",
        currentShow = "Sunburn Goa & Tomorrowland Live DJ Sets",
        currentShowCategory = "Electronic Dance",
        progressPercent = 0.75f,
        language = "English",
        isFeatured = false,
        description = "Direct festival stages from Sunburn Goa and global electronic music gatherings."
    ),
    RamChannel(
        id = "ghazal_mehfil_live",
        serialNumber = 343,
        name = "Ghazal Mehfil Live (ଗଜଲ ମେହଫିଲ)",
        logoText = "GZL",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "44.2K",
        resolution = "1080p FHD",
        currentShow = "ପଙ୍କଜ ଉଧାସ, ଗୁଲାମ ଅଲୀ ଓ ଚିତ୍ରା ସିଂହ (Live Mehfil)",
        currentShowCategory = "Classic Ghazals",
        progressPercent = 0.80f,
        language = "Hindi / Urdu",
        isFeatured = false,
        description = "Chithi Aayi Hai, Hungama Hai Kyon Barpa, and poetic evenings of gentle nostalgia."
    ),
    RamChannel(
        id = "classical_ragas_tv",
        serialNumber = 344,
        name = "Classical Ragas TV (ଭାରତୀୟ ଶାସ୍ତ୍ରୀୟ)",
        logoText = "RAG",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "32.8K",
        resolution = "1080p FHD",
        currentShow = "ଭୈରବୀ, ୟମନ ଓ ଦରବାରୀ କାନଡ଼ା (Morning & Evening Ragas)",
        currentShowCategory = "Hindustani & Carnatic",
        progressPercent = 0.60f,
        language = "Instrumental / Sanskrit",
        isFeatured = false,
        description = "Ustad Bismillah Khan Shehnai, Pt Bhimsen Joshi vocals, and MS Subbulakshmi Carnatic compositions."
    ),
    RamChannel(
        id = "bollywood_party_mix",
        serialNumber = 345,
        name = "Bollywood Party Mix (ପାର୍ଟି ସଙ୍ଗୀତ)",
        logoText = "PTY",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "66.3K",
        resolution = "1080p FHD",
        currentShow = "ହନି ସିଂହ, ବାଦଶାହ ଓ ନେହା କକ୍କର ହିଟ୍ସ",
        currentShowCategory = "Bollywood Rap & Party",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = false,
        description = "Yo Yo Honey Singh, Badshah, and Guru Randhawa non-stop energetic beats."
    ),
    RamChannel(
        id = "acoustic_guitar_chill",
        serialNumber = 346,
        name = "Acoustic Guitar Chill (ଶାନ୍ତ ଗିଟାର ସଙ୍ଗୀତ)",
        logoText = "GTR",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.1K",
        resolution = "1080p FHD",
        currentShow = "ମଧୁର ଆକୋଷ୍ଟିକ୍ ଅନୁଭୂତି (Acoustic Unplugged)",
        currentShowCategory = "Unplugged Sessions",
        progressPercent = 0.70f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Mellow acoustic guitar strumming, coffee-shop vibes, and acoustic Bollywood unplugged covers."
    ),
    RamChannel(
        id = "desi_lofi_beats",
        serialNumber = 347,
        name = "Desi Lo-Fi Beats (ଦେଶୀ ଲୋ-ଫାଇ)",
        logoText = "LFI",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.4K",
        resolution = "1080p FHD",
        currentShow = "ଲେଟ୍ ନାଇଟ୍ ଲୋ-ଫାଇ ଚିଲ୍ (Late Night Lo-Fi)",
        currentShowCategory = "Lo-Fi Study Beats",
        progressPercent = 0.90f,
        language = "Ambient Hindi",
        isFeatured = true,
        description = "Relaxing slow-reverbed Lo-Fi Bollywood beats ideal for studying, late-night working, and coding."
    ),
    RamChannel(
        id = "qawwali_live_tv",
        serialNumber = 348,
        name = "Qawwali Live TV (କବାଲୀ ଲାଇଭ)",
        logoText = "QWL",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.7K",
        resolution = "1080p FHD",
        currentShow = "ସାବରୀ ବ୍ରଦର୍ସ ଓ ନିଜାମୁଦ୍ଦୀନ ଆଉଲିଆ ଦରଗାହ କବାଲୀ",
        currentShowCategory = "Spiritual Qawwalis",
        progressPercent = 0.80f,
        language = "Urdu / Hindi",
        isFeatured = false,
        description = "Live spiritual clapping, harmonium ecstasy, and soulful devotional qawwalis from Delhi and Ajmer."
    ),
    RamChannel(
        id = "golden_60s_bollywood",
        serialNumber = 349,
        name = "Golden 60s Bollywood (୬୦ ଦଶକର ସୁମଧୁର ଗୀତ)",
        logoText = "G60",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.6K",
        resolution = "1080p FHD",
        currentShow = "ତେରେ ମେରେ ସପନେ ଓ ମୁକେଶ, ମନ୍ନା ଡେ ହିଟ୍ସ",
        currentShowCategory = "Golden Nostalgia",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Mukesh, Manna Dey, Hemant Kumar, Geeta Dutt and magical orchestration of Bollywood golden years."
    ),
    RamChannel(
        id = "nineties_romantic_duets",
        serialNumber = 350,
        name = "90s Romantic Duets (୯୦ ଦଶକର ଯୁଗଳବନ୍ଦୀ)",
        logoText = "DUE",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.9K",
        resolution = "1080p FHD",
        currentShow = "କୁମାର ସାନୁ ଓ ଅଲକା ୟାଗ୍ନିକ ଯୁଗଳବନ୍ଦୀ",
        currentShowCategory = "90s Duets",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "Nadeem-Shravan and Jatin-Lalit romantic harmonies that defined college romances across India."
    ),
    RamChannel(
        id = "instrumental_sitar_flute",
        serialNumber = 351,
        name = "Sitar & Flute Harmonies (ବାଂଶୁରୀ ଓ ସିତାର)",
        logoText = "SIT",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "35.2K",
        resolution = "1080p FHD",
        currentShow = "ପଣ୍ଡିତ ହରିପ୍ରସାଦ ଚୌରାସିଆ ଓ ରବିଶଙ୍କର ଧ୍ୱନି",
        currentShowCategory = "Peaceful Instrumental",
        progressPercent = 0.65f,
        language = "Pure Melody",
        isFeatured = false,
        description = "Pandit Hariprasad Chaurasia's flute and Pt Ravi Shankar's sitar creating celestial peace."
    ),
    RamChannel(
        id = "bengali_melodies_tv",
        serialNumber = 352,
        name = "Bengali Melodies TV (বাংলা গানের সুর)",
        logoText = "BGM",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.8K",
        resolution = "1080p FHD",
        currentShow = "ହେମନ୍ତ ମୁଖାର୍ଜୀ, ଆରଡି ବର୍ମନ ଓ ରବୀନ୍ଦ୍ର ସଙ୍ଗୀତ",
        currentShowCategory = "Bengali Classics",
        progressPercent = 0.70f,
        language = "Bengali",
        isFeatured = false,
        description = "Unforgettable Bengali modern songs, Adhunik Gaan, Manna Dey, and timeless melodies."
    ),
    RamChannel(
        id = "tamil_beats_247",
        serialNumber = 353,
        name = "Tamil Beats 24x7 (தமிழ் இசை)",
        logoText = "TMB",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.4K",
        resolution = "1080p FHD",
        currentShow = "ଏଆର ରହମାନ ଓ ଅନିରୁଦ୍ଧ ସୁପରହିଟ୍ସ (ARR & Anirudh Hits)",
        currentShowCategory = "Tamil Chartbusters",
        progressPercent = 0.85f,
        language = "Tamil",
        isFeatured = true,
        description = "AR Rahman magic, Ilaiyaraaja symphonies, and Anirudh Ravichander viral youth tracks."
    ),
    RamChannel(
        id = "telugu_hits_music",
        serialNumber = 354,
        name = "Telugu Hits Music (తెలుగు పాటలు)",
        logoText = "TLM",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.3K",
        resolution = "1080p FHD",
        currentShow = "ନାଟୁ ନାଟୁ ଓ ଥମନ, ଦେବୀ ଶ୍ରୀ ପ୍ରସାଦ ମ୍ୟୁଜିକ୍",
        currentShowCategory = "Tollywood Beats",
        progressPercent = 0.80f,
        language = "Telugu",
        isFeatured = false,
        description = "Oscar-winning Naatu Naatu energy, Devi Sri Prasad dance songs, and romantic Tollywood tracks."
    ),
    RamChannel(
        id = "kannada_sangeetha",
        serialNumber = 355,
        name = "Kannada Sangeetha (ಕನ್ನಡ ಸಂಗೀತ)",
        logoText = "KNS",
        category = ChannelCategory.MUSIC,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "46.7K",
        resolution = "1080p FHD",
        currentShow = "କାନ୍ତାରା ବରାହ ରୂପମ୍ ଓ କେଜିଏଫ୍ ମ୍ୟୁଜିକ୍",
        currentShowCategory = "Sandalwood Hits",
        progressPercent = 0.75f,
        language = "Kannada",
        isFeatured = false,
        description = "Kantara spiritual divine beats, KGF thumping bgm, and melodious Sandalwood movie tracks."
    )
)
