package com.example.model

/**
 * 50 National & Global Live News Channels (Serial 241 - 290)
 * Covers:
 * - Top National Hindi 24x7 News (Aaj Tak, India TV, ABP News, Zee News, News18 India, Republic Bharat,
 *   NDTV India, Times Now Navbharat, Good News Today, TV9 Bharatvarsh, Bharat 24, News 24,
 *   India News, News Nation, Sudarshan News, CNBC Awaaz, Zee Business)
 * - State & Regional Hindi News (Swadesh News, Khabar Fast, Janta TV, First India News, News State UP/UK,
 *   News18 MP/CG, Zee MP/CG, Zee UP/UK, Zee Bihar/Jharkhand, News18 Bihar/Jharkhand, News18 Rajasthan,
 *   Zee Rajasthan, ABP Ganga, News State MP/CG)
 * - Top English National & Global (WION, Republic TV, NDTV 24x7, CNN-News18, Times Now,
 *   India Today TV, DW News, Al Jazeera English, France 24, RT News, NHK World, CNBC TV18,
 *   Bloomberg TV, Sky News, Euronews, Arirang World, TRT World, CNA Singapore, ABC News Live)
 */
fun buildNewsChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "aaj_tak",
        serialNumber = 241,
        name = "Aaj Tak (ଆଜ ତକ ନ୍ୟୁଜ ୨୪x୭)",
        logoText = "ATK",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "142.5K",
        resolution = "1080p FHD",
        currentShow = "ଶଙ୍ଖନାଦ ଓ ଦଙ୍ଗଲ (Shankhnaad & Dangal Debate)",
        currentShowCategory = "Primetime Debate",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = true,
        description = "India's highest viewed Hindi news channel delivering fastest updates, ground reports, and hard debates."
    ),
    RamChannel(
        id = "india_tv",
        serialNumber = 242,
        name = "India TV (ଇଣ୍ଡିଆ ଟିଭି ଲାଇଭ)",
        logoText = "ITV",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "118.3K",
        resolution = "1080p FHD",
        currentShow = "ଆପ କି ଅଦାଲତ ଓ ଆଜ କି ବାତ (Aap Ki Adalat)",
        currentShowCategory = "Flagship Show",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = true,
        description = "Rajat Sharma's India TV featuring courtroom interviews, political investigations, and national news."
    ),
    RamChannel(
        id = "abp_news",
        serialNumber = 243,
        name = "ABP News (ଏବିପି ନ୍ୟୁଜ ୨୪x୭)",
        logoText = "ABP",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "105.7K",
        resolution = "1080p FHD",
        currentShow = "ମାଷ୍ଟର ଷ୍ଟ୍ରୋକ ଓ ସମ୍ବିଧାନ କି ଶପଥ (Master Stroke)",
        currentShowCategory = "Investigative News",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Credible, responsible national journalism with deep analytical perspective and verified facts."
    ),
    RamChannel(
        id = "zee_news",
        serialNumber = 244,
        name = "Zee News (ଜୀ ନ୍ୟୁଜ ଲାଇଭ)",
        logoText = "ZEE",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "112.4K",
        resolution = "1080p FHD",
        currentShow = "ଡିଏନଏ - ଡେଲି ନ୍ୟୁଜ ଏଣ୍ଡ ଆନାଲିସିସ (DNA Live)",
        currentShowCategory = "News Analysis",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Pioneering Indian news channel with the iconic Daily News & Analysis (DNA) primetime show."
    ),
    RamChannel(
        id = "news18_india",
        serialNumber = 245,
        name = "News18 India (ନ୍ୟୁଜ୧୮ ଇଣ୍ଡିଆ)",
        logoText = "N18",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "96.8K",
        resolution = "1080p FHD",
        currentShow = "ଦେଶ କି ନହିଁ ହାରେଗା ଓ ଆରପାର (Aar Paar)",
        currentShowCategory = "Primetime Clash",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Network18's high voltage national Hindi news channel bringing breaking bulletins from across India."
    ),
    RamChannel(
        id = "republic_bharat",
        serialNumber = 246,
        name = "Republic Bharat (ରିପବ୍ଲିକ ଭାରତ)",
        logoText = "RPB",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "125.1K",
        resolution = "1080p FHD",
        currentShow = "ପୁଛତା ହୈ ଭାରତ ଓ ମହାଦେବତ (Poochta Hai Bharat)",
        currentShowCategory = "Fierce Debate",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "High octane, nationalist news channel led by Arnab Goswami, fearless and uncompromising."
    ),
    RamChannel(
        id = "ndtv_india",
        serialNumber = 247,
        name = "NDTV India (ଏନଡିଟିଭି ଇଣ୍ଡିଆ)",
        logoText = "NDI",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.9K",
        resolution = "1080p FHD",
        currentShow = "ପ୍ରାଇମ ଟାଇମ ଓ ଦେଶ କି ବାତ (Prime Time NDTV)",
        currentShowCategory = "Critical Analysis",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Esteemed news broadcasting brand known for deep field reporting and balanced discussions."
    ),
    RamChannel(
        id = "times_now_navbharat",
        serialNumber = 248,
        name = "Times Now Navbharat (ଟାଇମ୍ସ ନାଓ)",
        logoText = "TNN",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.4K",
        resolution = "1080p FHD",
        currentShow = "ନ୍ୟୁଜ କି ପାଠଶାଳା ଓ ସୱାଲ ପବ୍ଲିକ କା",
        currentShowCategory = "Public Interest",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Times Network's dynamic Hindi news offering modern graphics, facts, and engaging debates."
    ),
    RamChannel(
        id = "good_news_today",
        serialNumber = 249,
        name = "Good News Today (ଜିଏନଟି)",
        logoText = "GNT",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.2K",
        resolution = "1080p FHD",
        currentShow = "ଆଶାବାଦୀ ଭାରତ ଓ ସକାରାତ୍ମକ ସମାଚାର (Positive India)",
        currentShowCategory = "Positive News",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "India Today Group's constructive journalism channel focusing on positive human stories and innovations."
    ),
    RamChannel(
        id = "tv9_bharatvarsh",
        serialNumber = 250,
        name = "TV9 Bharatvarsh (ଟିଭି୯ ଭାରତବର୍ଷ)",
        logoText = "TV9",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "91.3K",
        resolution = "1080p FHD",
        currentShow = "ଫିକ୍ର ଆପକି ଓ ବିଶ୍ୱ ଯୁଦ୍ଧ କଭରେଜ (Global War Room)",
        currentShowCategory = "War & Geopolitics",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Cutting-edge graphics and defense reporting covering global geopolitical conflicts and national news."
    ),
    RamChannel(
        id = "bharat_24",
        serialNumber = 251,
        name = "Bharat 24 (ଭାରତ ୨୪ ଲାଇଭ)",
        logoText = "B24",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "47.8K",
        resolution = "1080p FHD",
        currentShow = "ଭିଜନ ଇଣ୍ଡିଆ ଓ ଦେଶ କା ସ୍ୱର (Vision India)",
        currentShowCategory = "National Perspective",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Fast-growing national news network with comprehensive multi-state bureaus."
    ),
    RamChannel(
        id = "news_24",
        serialNumber = 252,
        name = "News 24 (ନ୍ୟୁଜ ୨୪ ରାଷ୍ଟ୍ର)",
        logoText = "N24",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.5K",
        resolution = "1080p FHD",
        currentShow = "ରାଷ୍ଟ୍ର କି ବାତ ଓ ମାହୋଲ କ୍ୟା ହୈ (Rashtra Ki Baat)",
        currentShowCategory = "Election & Politics",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Anurradha Prasad's News 24 known for ground-level political surveys and election coverage."
    ),
    RamChannel(
        id = "india_news",
        serialNumber = 253,
        name = "India News (ଇଣ୍ଡିଆ ନ୍ୟୁଜ)",
        logoText = "INW",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.9K",
        resolution = "1080p FHD",
        currentShow = "ଦେଶ କା ବଡ଼ା ମୁଦ୍ଦା (National Debate)",
        currentShowCategory = "Debate & News",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "ITV Network's flagship national Hindi news channel focusing on governance, politics, and defense."
    ),
    RamChannel(
        id = "news_nation",
        serialNumber = 254,
        name = "News Nation (ନ୍ୟୁଜ ନେସନ)",
        logoText = "NNT",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.1K",
        resolution = "1080p FHD",
        currentShow = "ନ୍ୟୁଜ ରୁମ ଲାଇଭ ଓ ଖୋଜ (Khoj Investigation)",
        currentShowCategory = "Investigation",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Hard-hitting investigative journalism, crime reports, and defense news."
    ),
    RamChannel(
        id = "sudarshan_news",
        serialNumber = 255,
        name = "Sudarshan News (ସୁଦର୍ଶନ ନ୍ୟୁଜ)",
        logoText = "SUD",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "43.7K",
        resolution = "720p HD",
        currentShow = "ବିନ୍ଦାସ ବୋଲ ଓ ରାଷ୍ଟ୍ରବାଦ (Bindas Bol)",
        currentShowCategory = "Nationalist Views",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = false,
        description = "Nationalist perspective channel focused on national security, ancient heritage and cultural preservation."
    ),
    RamChannel(
        id = "cnbc_awaaz",
        serialNumber = 256,
        name = "CNBC Awaaz (ସିଏନବିସି ଆୱାଜ ବଜାର)",
        logoText = "AWZ",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.2K",
        resolution = "1080p FHD",
        currentShow = "ସେୟାର ବଜାର ଲାଇଭ ଓ କମାୟୀ କା ଅଡ୍ଡା (Stock Market)",
        currentShowCategory = "Business & Stock Market",
        progressPercent = 0.90f,
        language = "Hindi",
        isFeatured = true,
        description = "India's No.1 Hindi business news channel guiding investors on Sensex, Nifty, mutual funds and IPOs."
    ),
    RamChannel(
        id = "zee_business",
        serialNumber = 257,
        name = "Zee Business (ଜୀ ବିଜନେସ)",
        logoText = "ZBZ",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.6K",
        resolution = "1080p FHD",
        currentShow = "ଅନିଲ ସିଂଘଭି ବଜାର ଷ୍ଟ୍ରାଟେଜି (Market Strategy Live)",
        currentShowCategory = "Financial Markets",
        progressPercent = 0.85f,
        language = "Hindi",
        isFeatured = false,
        description = "Market expert Anil Singhvi and top financial minds decode trading opportunities and personal finance."
    ),
    RamChannel(
        id = "wion_news",
        serialNumber = 258,
        name = "WION News Global (ୱିଅନ ଗ୍ଲୋବାଲ)",
        logoText = "WIO",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf(
            "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "134.8K",
        resolution = "1080p FHD",
        currentShow = "World Is One News & Gravitas Live",
        currentShowCategory = "Global Affairs",
        progressPercent = 0.80f,
        language = "English",
        isFeatured = true,
        description = "India's premier international news network broadcasting geopolitical insights to over 190 countries."
    ),
    RamChannel(
        id = "republic_tv_english",
        serialNumber = 259,
        name = "Republic TV (ରିପବ୍ଲିକ ଇଂରାଜୀ)",
        logoText = "RTV",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "102.3K",
        resolution = "1080p FHD",
        currentShow = "The Debate with Arnab Goswami (Live Debate)",
        currentShowCategory = "Primetime English",
        progressPercent = 0.90f,
        language = "English",
        isFeatured = true,
        description = "India's highest rated English news channel with fiery debates and high-impact investigative exposés."
    ),
    RamChannel(
        id = "ndtv_247",
        serialNumber = 260,
        name = "NDTV 24x7 (ଏନଡିଟିଭି ୨୪x୭)",
        logoText = "ND2",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "85.7K",
        resolution = "1080p FHD",
        currentShow = "Left, Right & Centre with Vishnu Som",
        currentShowCategory = "In-Depth English",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Iconic English news channel delivering global standards of broadcast journalism and defense analyses."
    ),
    RamChannel(
        id = "cnn_news18",
        serialNumber = 261,
        name = "CNN-News18 (ସିଏନଏନ ନ୍ୟୁଜ୧୮)",
        logoText = "CNN",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "79.4K",
        resolution = "1080p FHD",
        currentShow = "The Right Stand & Brass Tacks with Zakka Jacob",
        currentShowCategory = "English Primetime",
        progressPercent = 0.75f,
        language = "English",
        isFeatured = false,
        description = "Network18 partnership with CNN presenting balanced international perspectives and Indian politics."
    ),
    RamChannel(
        id = "times_now_english",
        serialNumber = 262,
        name = "Times Now English (ଟାଇମ୍ସ ନାଓ)",
        logoText = "TMN",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.5K",
        resolution = "1080p FHD",
        currentShow = "India Upfront & The Newshour Live",
        currentShowCategory = "The Newshour",
        progressPercent = 0.85f,
        language = "English",
        isFeatured = true,
        description = "Leading English television news network known for bold questions and definitive stance on national issues."
    ),
    RamChannel(
        id = "india_today_tv",
        serialNumber = 263,
        name = "India Today TV (ଇଣ୍ଡିଆ ଟୁଡେ)",
        logoText = "ITD",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "83.1K",
        resolution = "1080p FHD",
        currentShow = "News Today with Rajdeep Sardesai",
        currentShowCategory = "Political Review",
        progressPercent = 0.65f,
        language = "English",
        isFeatured = false,
        description = "India Today Group's premier English news channel with comprehensive national election and world coverage."
    ),
    RamChannel(
        id = "dw_news_english",
        serialNumber = 264,
        name = "DW News English (ଡିଡବ୍ଲ୍ୟୁ ଜର୍ମାନୀ)",
        logoText = "DWN",
        category = ChannelCategory.NEWS,
        streamUrl = "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.8K",
        resolution = "1080p FHD",
        currentShow = "DW News Global Journal & Conflict Zone",
        currentShowCategory = "European & World News",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "Germany's international public broadcaster providing unbiased world news, science, and ecology."
    ),
    RamChannel(
        id = "al_jazeera_english",
        serialNumber = 265,
        name = "Al Jazeera English (ଅଲ ଜଜିରା)",
        logoText = "AJE",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live-hls-web-aje.getaj.net/AJE/03.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.3K",
        resolution = "1080p FHD",
        currentShow = "Al Jazeera World News Hour & Inside Story",
        currentShowCategory = "World News",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = true,
        description = "Award-winning global 24x7 news covering underreported stories from Asia, Africa, and the Middle East."
    ),
    RamChannel(
        id = "france_24_english",
        serialNumber = 266,
        name = "France 24 English (ଫ୍ରାନ୍ସ ୨୪)",
        logoText = "F24",
        category = ChannelCategory.NEWS,
        streamUrl = "https://stream.france24.com/hls/live/2037167/F24_EN_LO_HLS/master.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.4K",
        resolution = "1080p FHD",
        currentShow = "Eye on Africa & The World This Week",
        currentShowCategory = "International News",
        progressPercent = 0.50f,
        language = "English",
        isFeatured = false,
        description = "French international news channel offering a European perspective on global culture, arts, and diplomacy."
    ),
    RamChannel(
        id = "rt_news_english",
        serialNumber = 267,
        name = "RT News English (ଆରଟି ୱାର୍ଲ୍ଡ)",
        logoText = "RTW",
        category = ChannelCategory.NEWS,
        streamUrl = "https://rt-eng-live.akamaized.net/hls/live/2026859/rt_eng/master.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.2K",
        resolution = "1080p FHD",
        currentShow = "Question More & International Headlines",
        currentShowCategory = "Alternative Global Views",
        progressPercent = 0.55f,
        language = "English",
        isFeatured = false,
        description = "24x7 English international news providing alternate viewpoints on major geopolitical flashpoints."
    ),
    RamChannel(
        id = "nhk_world_japan",
        serialNumber = 268,
        name = "NHK World Japan (ଏନଏଚକେ ଜାପାନ)",
        logoText = "NHK",
        category = ChannelCategory.NEWS,
        streamUrl = "https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/2003458/live.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.9K",
        resolution = "1080p FHD",
        currentShow = "NHK Newsline & Japanese Tech Innovation",
        currentShowCategory = "Asia & Technology",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "Japan's national public broadcaster showcasing Tokyo updates, robotics, culinary art, and culture."
    ),
    // Additional Hindi State & Global English News (269 - 290)
    RamChannel(
        id = "swadesh_news",
        serialNumber = 269,
        name = "Swadesh News (ସ୍ୱଦେଶ ନ୍ୟୁଜ)",
        logoText = "SWD",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.4K",
        resolution = "720p HD",
        currentShow = "ସବକା ସାଥ ସବକା ବିକାଶ ଓ ସ୍ୱଦେଶୀ ସମାଚାର",
        currentShowCategory = "National News",
        progressPercent = 0.50f,
        language = "Hindi",
        isFeatured = false,
        description = "Hindi regional news channel covering grassroots developments across central India."
    ),
    RamChannel(
        id = "khabar_fast",
        serialNumber = 270,
        name = "Khabar Fast (ଖବର ଫାଷ୍ଟ)",
        logoText = "KBF",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "36.2K",
        resolution = "720p HD",
        currentShow = "ହରିୟାଣା, ପଞ୍ଜାବ ଓ ଦିଲ୍ଲୀ ଏନସିଆର ବୁଲେଟିନ",
        currentShowCategory = "North India News",
        progressPercent = 0.60f,
        language = "Hindi",
        isFeatured = false,
        description = "Speedy regional updates from Delhi-NCR, Haryana, and western Uttar Pradesh."
    ),
    RamChannel(
        id = "janta_tv",
        serialNumber = 271,
        name = "Janta TV (ଜନତା ଟିଭି ହିନ୍ଦୀ)",
        logoText = "JNT",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.5K",
        resolution = "1080p FHD",
        currentShow = "ଜନତା କି ଆୱାଜ ଓ ବିଧାନସଭା ଖବର",
        currentShowCategory = "Public Voice",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Voice of the common citizen bringing hyper-local issues directly to government attention."
    ),
    RamChannel(
        id = "first_india_news",
        serialNumber = 272,
        name = "First India News (ଫାର୍ଷ୍ଟ ଇଣ୍ଡିଆ ରାଜସ୍ଥାନ)",
        logoText = "FIN",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.6K",
        resolution = "1080p FHD",
        currentShow = "ରାଜସ୍ଥାନ କା ଦଙ୍ଗଲ ଓ ଜୟପୁର ଲାଇଭ",
        currentShowCategory = "Rajasthan Politics",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Premier Rajasthan regional news channel broadcasting from Jaipur bureaus."
    ),
    RamChannel(
        id = "news_state_up_uk",
        serialNumber = 273,
        name = "News State UP & Uttarakhand (ନ୍ୟୁଜ ଷ୍ଟେଟ ୟୁପି)",
        logoText = "NSU",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.8K",
        resolution = "1080p FHD",
        currentShow = "ୟୁପି ମହାସମର ଓ ଦେବଭୂମି ଉତ୍ତରାଖଣ୍ଡ",
        currentShowCategory = "State Politics",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Top regional channel by News Nation focusing exclusively on UP and Uttarakhand."
    ),
    RamChannel(
        id = "news18_mp_cg",
        serialNumber = 274,
        name = "News18 MP & Chhattisgarh (ନ୍ୟୁଜ୧୮ ଏମପି)",
        logoText = "N18M",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.2K",
        resolution = "1080p FHD",
        currentShow = "ଭୋପାଳ-ରାୟପୁର ସୁପରଫାଷ୍ଟ ସମାଚାର",
        currentShowCategory = "State News",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Comprehensive coverage of Madhya Pradesh and Chhattisgarh politics and development."
    ),
    RamChannel(
        id = "zee_mp_cg",
        serialNumber = 275,
        name = "Zee MP Chhattisgarh (ଜୀ ଏମପି ଛତିଶଗଡ଼)",
        logoText = "ZMC",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "57.4K",
        resolution = "1080p FHD",
        currentShow = "ମଧ୍ୟପ୍ରଦେଶ କି ବଡ଼ି ବାତ (State Primetime)",
        currentShowCategory = "Central India News",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Zee Media's trusted network channel for Central India with massive grassroots network."
    ),
    RamChannel(
        id = "zee_up_uk",
        serialNumber = 276,
        name = "Zee UP Uttarakhand (ଜୀ ଉତ୍ତରପ୍ରଦେଶ)",
        logoText = "ZUP",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.8K",
        resolution = "1080p FHD",
        currentShow = "ୟୁପି କା ମୁଦ୍ଦା ଓ ଲକ୍ଷ୍ନୌରୁ ସିଧା ପ୍ରସାରଣ",
        currentShowCategory = "UP News",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = false,
        description = "Leading regional news in India's most populous state reporting from Lucknow and Dehradun."
    ),
    RamChannel(
        id = "zee_bihar_jharkhand",
        serialNumber = 277,
        name = "Zee Bihar Jharkhand (ଜୀ ବିହାର ଝାଡ଼ଖଣ୍ଡ)",
        logoText = "ZBJ",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.3K",
        resolution = "1080p FHD",
        currentShow = "ବିହାର କି ରାଜନୀତି ଓ ପାଟନା ଲାଇଭ ଡିବେଟ",
        currentShowCategory = "Bihar News",
        progressPercent = 0.75f,
        language = "Hindi",
        isFeatured = false,
        description = "Round-the-clock political analysis, election coverage, and district news of Bihar and Jharkhand."
    ),
    RamChannel(
        id = "news18_bihar_jharkhand",
        serialNumber = 278,
        name = "News18 Bihar Jharkhand (ନ୍ୟୁଜ୧୮ ବିହାର)",
        logoText = "N18B",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.9K",
        resolution = "1080p FHD",
        currentShow = "ଦୋ କା ଦମ ଓ ରାଜଧାନୀ ପାଟନାରୁ ସମାଚାର",
        currentShowCategory = "State Bulletins",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Network18's high impact news channel with deep ground reporting across eastern India."
    ),
    RamChannel(
        id = "news18_rajasthan",
        serialNumber = 279,
        name = "News18 Rajasthan (ନ୍ୟୁଜ୧୮ ରାଜସ୍ଥାନ)",
        logoText = "N18R",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.7K",
        resolution = "1080p FHD",
        currentShow = "ମ୍ହାରୋ ରାଜସ୍ଥାନ ଓ ଫ୍ରଣ୍ଟପେଜ ସମାଚାର",
        currentShowCategory = "Desert State News",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = false,
        description = "Reliable reporting on tourism, culture, politics, and law enforcement in Rajasthan."
    ),
    RamChannel(
        id = "zee_rajasthan",
        serialNumber = 280,
        name = "Zee Rajasthan (ଜୀ ରାଜସ୍ଥାନ)",
        logoText = "ZRJ",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.1K",
        resolution = "1080p FHD",
        currentShow = "ରାଜସ୍ଥାନ ଏକ୍ସପ୍ରେସ୍ ଓ ମୁଦ୍ଦା ଆପଣଙ୍କର",
        currentShowCategory = "Rajasthan Debates",
        progressPercent = 0.65f,
        language = "Hindi",
        isFeatured = false,
        description = "Zee Media's dedicated Rajasthan news channel with vibrant graphics and fearless debates."
    ),
    RamChannel(
        id = "abp_ganga",
        serialNumber = 281,
        name = "ABP Ganga (ଏବିପି ଗଙ୍ଗା ୟୁପି)",
        logoText = "ABG",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "66.2K",
        resolution = "1080p FHD",
        currentShow = "ଖବର ବଡ଼ି ହୈ ଓ ବ୍ରହ୍ମାସ୍ତ୍ର (UP Uttarakhand)",
        currentShowCategory = "UP Uttarakhand Debate",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "ABP Network's prestigious channel serving 250 million citizens along the sacred river Ganga."
    ),
    RamChannel(
        id = "news_state_mp_cg",
        serialNumber = 282,
        name = "News State MP & CG (ନ୍ୟୁଜ ଷ୍ଟେଟ ଏମପି)",
        logoText = "NSM",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "44.7K",
        resolution = "720p HD",
        currentShow = "ମଧ୍ୟାହ୍ନ ବୁଲେଟିନ ଓ ଆଜ କା ମୁଦ୍ଦା",
        currentShowCategory = "State Issues",
        progressPercent = 0.55f,
        language = "Hindi",
        isFeatured = false,
        description = "Dedicated reporting on farmer subsidies, administrative changes, and district events."
    ),
    RamChannel(
        id = "cnbc_tv18",
        serialNumber = 283,
        name = "CNBC TV18 (ସିଏନବିସି ଇଂରାଜୀ ବଜାର)",
        logoText = "C18",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.4K",
        resolution = "1080p FHD",
        currentShow = "Bazaar Morning Call & India Business Hour",
        currentShowCategory = "Business English",
        progressPercent = 0.85f,
        language = "English",
        isFeatured = true,
        description = "India's undisputed leader in English financial news, Dalal Street analysis and corporate boardroom debates."
    ),
    RamChannel(
        id = "bloomberg_tv",
        serialNumber = 284,
        name = "Bloomberg Global (ବ୍ଲୁମବର୍ଗ ଗ୍ଲୋବାଲ)",
        logoText = "BLM",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.5K",
        resolution = "1080p FHD",
        currentShow = "Bloomberg Surveillance & Wall Street Live",
        currentShowCategory = "Global Finance",
        progressPercent = 0.90f,
        language = "English",
        isFeatured = false,
        description = "Worldwide financial terminal reporting, Wall Street trends, central bank decisions, and tech unicorns."
    ),
    RamChannel(
        id = "sky_news_intl",
        serialNumber = 285,
        name = "Sky News International (ସ୍କାଇ ନ୍ୟୁଜ)",
        logoText = "SKY",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "63.1K",
        resolution = "1080p FHD",
        currentShow = "Sky News UK & The World Tonight Live",
        currentShowCategory = "UK & World News",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "British 24x7 television news known for rapid breaking news from Europe, America and the Middle East."
    ),
    RamChannel(
        id = "euronews_english",
        serialNumber = 286,
        name = "Euronews English (ୟୁରୋ ନ୍ୟୁଜ)",
        logoText = "EUR",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.7K",
        resolution = "1080p FHD",
        currentShow = "Europe Tonight & Brussels Insider",
        currentShowCategory = "European Affairs",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "Independent multi-perspective coverage of EU policies, European economy, and global culture."
    ),
    RamChannel(
        id = "arirang_tv_world",
        serialNumber = 287,
        name = "Arirang TV World (କୋରିଆ ୱାର୍ଲ୍ଡ)",
        logoText = "ARI",
        category = ChannelCategory.NEWS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "45.9K",
        resolution = "1080p FHD",
        currentShow = "Arirang News, K-Pop Global & Seoul Today",
        currentShowCategory = "Korea & World",
        progressPercent = 0.65f,
        language = "English",
        isFeatured = false,
        description = "South Korea's global English broadcaster covering East Asian diplomacy, technology, and K-Wave culture."
    ),
    RamChannel(
        id = "trt_world_english",
        serialNumber = 288,
        name = "TRT World English (ଟିଆରଟି ୱାର୍ଲ୍ଡ)",
        logoText = "TRT",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.3K",
        resolution = "1080p FHD",
        currentShow = "The Newsmakers & World In Focus",
        currentShowCategory = "Eurasia & World",
        progressPercent = 0.55f,
        language = "English",
        isFeatured = false,
        description = "Eurasian perspective on geopolitics, humanitarian conflicts, and Middle Eastern affairs."
    ),
    RamChannel(
        id = "cna_singapore",
        serialNumber = 289,
        name = "CNA Singapore (ସିଙ୍ଗାପୁର ନ୍ୟୁଜ ଏସିଆ)",
        logoText = "CNA",
        category = ChannelCategory.NEWS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.4K",
        resolution = "1080p FHD",
        currentShow = "Asia First & East Asia Business Watch",
        currentShowCategory = "Southeast Asia",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Singapore's premier news network delivering award-winning journalism and Asian economic insights."
    ),
    RamChannel(
        id = "abc_news_live",
        serialNumber = 290,
        name = "ABC News Live (ଏବିସି ଆମେରିକା ଲାଇଭ)",
        logoText = "ABC",
        category = ChannelCategory.NEWS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.1K",
        resolution = "1080p FHD",
        currentShow = "World News Tonight & Nightline Special",
        currentShowCategory = "US & World Affairs",
        progressPercent = 0.80f,
        language = "English",
        isFeatured = false,
        description = "American news network bringing live Washington White House updates, space, and world headlines."
    )
)
