package com.example.model

/**
 * 65 Regional Multi-Language Indian Channels (Serial 431 - 495)
 * Covers:
 * - Bengali (ABP Ananda, 24 Ghanta, Kolkata TV, News18 Bangla, Sangeet Bangla, Aakash Aath, CTVN AKD Plus)
 * - Telugu (TV9 Telugu, NTV Telugu, Sakshi TV, V6 News, ABN Andhra Jyothi, T News, 10TV, Gemini Music)
 * - Tamil (Sun News, Puthiya Thalaimurai, Thanthi TV, News18 Tamil Nadu, Polimer News, Kalaignar TV, Raj TV)
 * - Malayalam (Asianet News, 24 News Kerala, Manorama News, Mathrubhumi News, MediaOne, Jaihind TV, Kairali TV)
 * - Kannada (TV9 Kannada, Public TV, News18 Kannada, Suvarna News, Dighvijay 24x7, Kasthuri TV)
 * - Marathi (ABP Majha, Zee 24 Taas, TV9 Marathi, News18 Lokmat, Saam TV, Jai Maharashtra)
 * - Gujarati (ABP Asmita, TV9 Gujarati, Sandesh News, Zee 24 Kalak, VTV Gujarati)
 * - Punjabi (PTC News, Zee Punjab Haryana, Living India News, MH ONE News, Chardikla Time TV)
 * - Assamese & North East (Pratidin Time, News Live Assam, DY 365, Prag News, Assam Talks, News18 Assam/NE, Hornbill TV)
 * - Bhojpuri, Urdu & Kashmiri (DD Kashir, Gulistan News, Tahzeeb TV, Zee Salaam, Big Ganga)
 */
fun buildRegionalChannels(): List<RamChannel> = listOf(
    // Bengali (431 - 437)
    RamChannel(
        id = "abp_ananda",
        serialNumber = 431,
        name = "ABP Ananda (ଏବିପି ଆନନ୍ଦ ବଙ୍ଗଳା)",
        logoText = "ANA",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf(
            "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "138.4K",
        resolution = "1080p FHD",
        currentShow = "ଯୁକ୍ତିତର୍କ ଓ ଘଣ୍ଟାଖାନେକ ସଙ୍ଗେ ସୁମନ (Sange Suman)",
        currentShowCategory = "Bengali Primetime",
        progressPercent = 0.85f,
        language = "Bengali",
        isFeatured = true,
        description = "Bengal's undisputed No. 1 news channel featuring Suman De's flagship evening debate show."
    ),
    RamChannel(
        id = "zee_24_ghanta",
        serialNumber = 432,
        name = "Zee 24 Ghanta (ଜୀ ୨୪ ଘଣ୍ଟା ବଙ୍ଗଳା)",
        logoText = "24G",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "96.2K",
        resolution = "1080p FHD",
        currentShow = "ଆପଣାର ରାୟ ଓ କୋଲକାତା ଲାଇଭ ନ୍ୟୁଜ",
        currentShowCategory = "Bengali News",
        progressPercent = 0.70f,
        language = "Bengali",
        isFeatured = false,
        description = "Zee's pioneer Bengali 24x7 news channel with comprehensive Bengal district coverage."
    ),
    RamChannel(
        id = "kolkata_tv",
        serialNumber = 433,
        name = "Kolkata TV (କୋଲକାତା ଟିଭି)",
        logoText = "KTV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "64.1K",
        resolution = "1080p FHD",
        currentShow = "କୋଲକାତା ରାତଦିନ ଓ ସାମ୍ବାଦିକୀୟ ବିଶ୍ଳେଷଣ",
        currentShowCategory = "Kolkata City News",
        progressPercent = 0.65f,
        language = "Bengali",
        isFeatured = false,
        description = "Independent progressive Bengali news channel covering literature, arts, and political struggles."
    ),
    RamChannel(
        id = "news18_bangla",
        serialNumber = 434,
        name = "News18 Bangla (ନ୍ୟୁଜ୧୮ ବାଂଲା)",
        logoText = "N18B",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.9K",
        resolution = "1080p FHD",
        currentShow = "ଡାକପେୟାଦା ଓ ଜିଲ୍ଲା ସମାଚାର (District News)",
        currentShowCategory = "Bengal Regional",
        progressPercent = 0.75f,
        language = "Bengali",
        isFeatured = false,
        description = "Network18's Bengali arm reporting live from North Bengal hills to the Sundarbans delta."
    ),
    RamChannel(
        id = "sangeet_bangla",
        serialNumber = 435,
        name = "Sangeet Bangla (ସଙ୍ଗୀତ ବାଂଲା)",
        logoText = "SGB",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.4K",
        resolution = "1080p FHD",
        currentShow = "ଟଲିଉଡ଼ ଟପ୍ ୧୦ ଓ ଅନୁପମ ରାୟ ହିଟ୍ସ (Bengali Music)",
        currentShowCategory = "Bengali Music",
        progressPercent = 0.80f,
        language = "Bengali",
        isFeatured = true,
        description = "Bengal's beloved 24x7 television music channel featuring modern Bengali movie hits and Rabindrasangeet."
    ),
    RamChannel(
        id = "aakash_aath",
        serialNumber = 436,
        name = "Aakash Aath (ଆକାଶ ଆଠ ବଙ୍ଗଳା)",
        logoText = "AK8",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "53.6K",
        resolution = "720p HD",
        currentShow = "ପ୍ରାତଃ ରନ୍ନାଘର ଓ ସାହିତ୍ୟିକ ଧାରାବାହିକ",
        currentShowCategory = "Bengali Culture",
        progressPercent = 0.55f,
        language = "Bengali",
        isFeatured = false,
        description = "Culturally rich Bengali programming with classical detective serials and culinary cooking shows."
    ),
    RamChannel(
        id = "ctvn_akd_plus",
        serialNumber = 437,
        name = "CTVN AKD Plus (ସିଟିଭିଏନ ବଙ୍ଗଳା)",
        logoText = "CTV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.2K",
        resolution = "720p HD",
        currentShow = "ବାଂଲାର ସ୍ୱର ଓ ଲୋକ ସମାଚାର",
        currentShowCategory = "Public Issues",
        progressPercent = 0.50f,
        language = "Bengali",
        isFeatured = false,
        description = "Bengal grassroots reporting channel dedicated to civic infrastructure, art exhibitions and education."
    ),
    // Telugu (438 - 444)
    RamChannel(
        id = "tv9_telugu",
        serialNumber = 438,
        name = "TV9 Telugu (ଟିଭି୯ ତେଲୁଗୁ)",
        logoText = "TV9T",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "146.5K",
        resolution = "1080p FHD",
        currentShow = "TV9 Prime News Bulletin & Andhra-Telangana Headlines",
        currentShowCategory = "Telugu Primetime",
        progressPercent = 0.90f,
        language = "Telugu",
        isFeatured = true,
        description = "Dominant No. 1 Telugu news channel leading in breaking reporting and investigative journalism."
    ),
    RamChannel(
        id = "ntv_telugu",
        serialNumber = 439,
        name = "NTV Telugu (ଏନଟିଭି ତେଲୁଗୁ)",
        logoText = "NTV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "112.3K",
        resolution = "1080p FHD",
        currentShow = "Politricks Debate & Amaravati-Hyderabad News",
        currentShowCategory = "Telugu Politics",
        progressPercent = 0.75f,
        language = "Telugu",
        isFeatured = true,
        description = "High-impact political debates, state capital reports, and development coverage."
    ),
    RamChannel(
        id = "sakshi_tv",
        serialNumber = 440,
        name = "Sakshi TV (ସାକ୍ଷୀ ତେଲୁଗୁ ନ୍ୟୁଜ)",
        logoText = "SKT",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.1K",
        resolution = "1080p FHD",
        currentShow = "People's Voice, Special Bulletins & Rural Andhra News",
        currentShowCategory = "Rural & Governance",
        progressPercent = 0.70f,
        language = "Telugu",
        isFeatured = false,
        description = "Comprehensive regional television network covering governance, welfare schemes, and grassroots voices."
    ),
    RamChannel(
        id = "v6_news_telugu",
        serialNumber = 441,
        name = "V6 News Telugu (ଭି୬ ନ୍ୟୁଜ ତେଲଙ୍ଗାନା)",
        logoText = "V6T",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.4K",
        resolution = "1080p FHD",
        currentShow = "Teenmaar News with Bithiri Sathi (ତେଲଙ୍ଗାନା ହାସ୍ୟ)",
        currentShowCategory = "Satirical News",
        progressPercent = 0.85f,
        language = "Telugu",
        isFeatured = true,
        description = "Famous for Teenmaar satirical folk humor with Bithiri Sathi and rural Telangana cultural reporting."
    ),
    RamChannel(
        id = "abn_andhra_jyothi",
        serialNumber = 442,
        name = "ABN Andhra Jyothi (ଏବିଏନ୍ ତେଲୁଗୁ)",
        logoText = "ABN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "81.6K",
        resolution = "1080p FHD",
        currentShow = "Open Heart with RK & Ground Reality",
        currentShowCategory = "Interviews & Debates",
        progressPercent = 0.75f,
        language = "Telugu",
        isFeatured = false,
        description = "Radhakrishna's influential talk show and investigative political coverage across Telugu states."
    ),
    RamChannel(
        id = "t_news_telangana",
        serialNumber = 443,
        name = "T News Telangana (ଟି ନ୍ୟୁଜ)",
        logoText = "TNW",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.8K",
        resolution = "720p HD",
        currentShow = "Telangana Pride & Bathukamma Celebrations",
        currentShowCategory = "Telangana Culture",
        progressPercent = 0.60f,
        language = "Telugu",
        isFeatured = false,
        description = "Authentic Telangana voice highlighting local festivals, irrigation projects, and traditions."
    ),
    RamChannel(
        id = "gemini_music",
        serialNumber = 444,
        name = "Gemini Music (ଜେମିନି ମ୍ୟୁଜିକ୍ ତେଲୁଗୁ)",
        logoText = "GMM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.7K",
        resolution = "1080p FHD",
        currentShow = "Tollywood Superhit Songs & Chiranjeevi Specials",
        currentShowCategory = "Tollywood Cinema Music",
        progressPercent = 0.85f,
        language = "Telugu",
        isFeatured = true,
        description = "Sun TV Network's powerhouse Telugu music destination playing nonstop mass, beat, and melody tracks."
    ),
    // Tamil (445 - 451)
    RamChannel(
        id = "sun_news_tamil",
        serialNumber = 445,
        name = "Sun News Tamil (ସନ୍ ନ୍ୟୁଜ ତାମିଲ)",
        logoText = "SUN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "132.8K",
        resolution = "1080p FHD",
        currentShow = "Tamil Nadu News Live & Chennai City Watch",
        currentShowCategory = "Tamil Primetime",
        progressPercent = 0.85f,
        language = "Tamil",
        isFeatured = true,
        description = "The heavyweight Tamil news channel from Sun TV Network with bureaus spanning Tamil Nadu."
    ),
    RamChannel(
        id = "puthiya_thalaimurai",
        serialNumber = 446,
        name = "Puthiya Thalaimurai (ପୁଥିୟା ଥାଲାଇମୁରାଇ)",
        logoText = "PTH",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "118.5K",
        resolution = "1080p FHD",
        currentShow = "Nerpada Pesu Debate (ତାମିଲ ବିତର୍କ)",
        currentShowCategory = "Tamil Debates",
        progressPercent = 0.80f,
        language = "Tamil",
        isFeatured = true,
        description = "Leading independent Tamil news channel known for objective primetime debates and journalism."
    ),
    RamChannel(
        id = "thanthi_tv",
        serialNumber = 447,
        name = "Thanthi TV (ଥାନ୍ଥି ଟିଭି)",
        logoText = "THT",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "95.2K",
        resolution = "1080p FHD",
        currentShow = "Makkal Kural & Ayutha Ezhuthu Debate",
        currentShowCategory = "Public Interest",
        progressPercent = 0.70f,
        language = "Tamil",
        isFeatured = false,
        description = "Dina Thanthi group's popular channel with grassroots reporting and street-level interviews."
    ),
    RamChannel(
        id = "news18_tamil_nadu",
        serialNumber = 448,
        name = "News18 Tamil Nadu (ନ୍ୟୁଜ୧୮ ତାମିଲନାଡୁ)",
        logoText = "N18T",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "83.7K",
        resolution = "1080p FHD",
        currentShow = "Kalam Kalamaga & Breaking Bulletins",
        currentShowCategory = "Tamil News",
        progressPercent = 0.65f,
        language = "Tamil",
        isFeatured = false,
        description = "Network18's rapid news network across all 38 districts of Tamil Nadu and Puducherry."
    ),
    RamChannel(
        id = "polimer_news",
        serialNumber = 449,
        name = "Polimer News (ପଲିମର ନ୍ୟୁଜ)",
        logoText = "PLM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.4K",
        resolution = "720p HD",
        currentShow = "Polimer Speed Headlines & Investigative Special",
        currentShowCategory = "Fast News",
        progressPercent = 0.60f,
        language = "Tamil",
        isFeatured = false,
        description = "Fast, straight-to-the-point Tamil news bulletins focusing on social causes and justice."
    ),
    RamChannel(
        id = "kalaignar_tv",
        serialNumber = 450,
        name = "Kalaignar TV (କାଲାଇଞ୍ଜର ଟିଭି)",
        logoText = "KLG",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.1K",
        resolution = "1080p FHD",
        currentShow = "Maanada Mayilada & Kollywood Movie Hits",
        currentShowCategory = "Tamil Entertainment",
        progressPercent = 0.75f,
        language = "Tamil",
        isFeatured = false,
        description = "Prestigious Tamil general entertainment channel broadcasting legendary dance shows and cinema."
    ),
    RamChannel(
        id = "raj_tv_tamil",
        serialNumber = 451,
        name = "Raj TV (ରାଜ ଟିଭି ତାମିଲ)",
        logoText = "RAJ",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.3K",
        resolution = "720p HD",
        currentShow = "Retro Raj Geethangal & Tamil Serial Classics",
        currentShowCategory = "Tamil Classics",
        progressPercent = 0.55f,
        language = "Tamil",
        isFeatured = false,
        description = "Evergreen Tamil cinema classics from Sivaji Ganesan, MGR, and Kamal Haasan."
    ),
    // Malayalam (452 - 458)
    RamChannel(
        id = "asianet_news",
        serialNumber = 452,
        name = "Asianet News (ଏସିଆନେଟ ନ୍ୟୁଜ ମାଲାୟାଲମ)",
        logoText = "ASN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "154.2K",
        resolution = "1080p FHD",
        currentShow = "News Hour with Vinu V John (କେରଳ ପ୍ରାଇମଟାଇମ)",
        currentShowCategory = "Malayalam Primetime",
        progressPercent = 0.90f,
        language = "Malayalam",
        isFeatured = true,
        description = "The undisputed flagship news channel of Kerala with unmatched Gulf Malayali viewership."
    ),
    RamChannel(
        id = "twentyfour_news_kerala",
        serialNumber = 453,
        name = "24 News Kerala (୨୪ ନ୍ୟୁଜ କେରଳ)",
        logoText = "24K",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "121.7K",
        resolution = "1080p FHD",
        currentShow = "Janakeeya Kodathi with Sreekandan Nair (ଲୋକପ୍ରିୟ ବିତର୍କ)",
        currentShowCategory = "High Impact Debate",
        progressPercent = 0.85f,
        language = "Malayalam",
        isFeatured = true,
        description = "Kerala's dynamic news channel featuring augmented reality studios and Sreekandan Nair's debates."
    ),
    RamChannel(
        id = "manorama_news",
        serialNumber = 454,
        name = "Manorama News (ମନୋରମା ନ୍ୟୁଜ)",
        logoText = "MNR",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "108.9K",
        resolution = "1080p FHD",
        currentShow = "Counter Point with Shani Prabhakaran",
        currentShowCategory = "Malayalam Analysis",
        progressPercent = 0.80f,
        language = "Malayalam",
        isFeatured = true,
        description = "Malayala Manorama group's trusted 24-hour news channel with journalistic credibility."
    ),
    RamChannel(
        id = "mathrubhumi_news",
        serialNumber = 455,
        name = "Mathrubhumi News (ମାତୃଭୂମି ନ୍ୟୁଜ)",
        logoText = "MBM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "87.4K",
        resolution = "1080p FHD",
        currentShow = "Super Prime Time with Venu Balakrishnan",
        currentShowCategory = "Kerala Politics",
        progressPercent = 0.75f,
        language = "Malayalam",
        isFeatured = false,
        description = "Centenary newspaper brand's news channel delivering in-depth political discourse."
    ),
    RamChannel(
        id = "media_one_tv",
        serialNumber = 456,
        name = "MediaOne TV (ମିଡିଆ ୱାନ୍ ମାଲାୟାଲମ)",
        logoText = "MD1",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "79.1K",
        resolution = "1080p FHD",
        currentShow = "Special Edition & Middle East Malayalam Watch",
        currentShowCategory = "Kerala & Gulf Affairs",
        progressPercent = 0.70f,
        language = "Malayalam",
        isFeatured = false,
        description = "Broadcasting human rights, environmental issues, and large Malayali diaspora news in GCC."
    ),
    RamChannel(
        id = "jaihind_tv_kerala",
        serialNumber = 457,
        name = "Jaihind TV (ଜୟହିନ୍ଦ ଟିଭି)",
        logoText = "JHD",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.3K",
        resolution = "720p HD",
        currentShow = "Keralam Unarunnu & Morning Bulletins",
        currentShowCategory = "Kerala News",
        progressPercent = 0.55f,
        language = "Malayalam",
        isFeatured = false,
        description = "Regional political news, assembly debates, and socio-economic features across Kerala."
    ),
    RamChannel(
        id = "kairali_tv",
        serialNumber = 458,
        name = "Kairali TV (କୈରଳୀ ଟିଭି)",
        logoText = "KRL",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.5K",
        resolution = "1080p FHD",
        currentShow = "Mammootty Special Cinema & J.B. Junction",
        currentShowCategory = "Malayalam Cinema & Talk",
        progressPercent = 0.65f,
        language = "Malayalam",
        isFeatured = false,
        description = "Chaired by superstar Mammootty, blending left intellectual thought with Malayalam art and cinema."
    ),
    // Kannada (459 - 464)
    RamChannel(
        id = "tv9_kannada",
        serialNumber = 459,
        name = "TV9 Kannada (ଟିଭି୯ କନ୍ନଡ଼)",
        logoText = "TV9K",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "126.8K",
        resolution = "1080p FHD",
        currentShow = "News Cafe & Karnataka Headlines with Ranganath",
        currentShowCategory = "Kannada Primetime",
        progressPercent = 0.85f,
        language = "Kannada",
        isFeatured = true,
        description = "Karnataka's undisputed news leader bringing relentless investigative reporting from Bengaluru."
    ),
    RamChannel(
        id = "public_tv_kannada",
        serialNumber = 460,
        name = "Public TV (ପବ୍ଲିକ ଟିଭି କନ୍ନଡ଼)",
        logoText = "PUB",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "119.3K",
        resolution = "1080p FHD",
        currentShow = "Nanna Dani & Big Bulletin with HR Ranganath",
        currentShowCategory = "Kannada Big Bulletin",
        progressPercent = 0.90f,
        language = "Kannada",
        isFeatured = true,
        description = "HR Ranganath's iconic Big Bulletin questioning politicians fearlessly for public good."
    ),
    RamChannel(
        id = "news18_kannada",
        serialNumber = 461,
        name = "News18 Kannada (ନ୍ୟୁଜ୧୮ କନ୍ନଡ଼)",
        logoText = "N18K",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "78.4K",
        resolution = "1080p FHD",
        currentShow = "Nanna Ooru Nanna Suddi & State Bulletins",
        currentShowCategory = "Karnataka District News",
        progressPercent = 0.70f,
        language = "Kannada",
        isFeatured = false,
        description = "Network18's high standard Kannada news network reporting from coastal to northern Karnataka."
    ),
    RamChannel(
        id = "suvarna_news",
        serialNumber = 462,
        name = "Asianet Suvarna News (ସୁବର୍ଣ୍ଣ ନ୍ୟୁଜ)",
        logoText = "SVN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "92.1K",
        resolution = "1080p FHD",
        currentShow = "Straight Hit with Ajit Hanumakkanavar",
        currentShowCategory = "Kannada Debates",
        progressPercent = 0.80f,
        language = "Kannada",
        isFeatured = true,
        description = "Hard-hitting journalism with Ajit Hanumakkanavar's unsparing primetime cross-examinations."
    ),
    RamChannel(
        id = "dighvijay_news_kannada",
        serialNumber = 463,
        name = "Dighvijay 24x7 (ଦିଗ୍ବିଜୟ କନ୍ନଡ଼)",
        logoText = "DGV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "51.6K",
        resolution = "720p HD",
        currentShow = "Karnatakada Kathe & Crime Dairies",
        currentShowCategory = "Crime & Politics",
        progressPercent = 0.60f,
        language = "Kannada",
        isFeatured = false,
        description = "Vijayavani newspaper group's channel delivering fast updates and civic investigative reports."
    ),
    RamChannel(
        id = "kasthuri_tv",
        serialNumber = 464,
        name = "Kasthuri TV (କସ୍ତୁରୀ ଟିଭି କନ୍ନଡ଼)",
        logoText = "KST",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "45.9K",
        resolution = "720p HD",
        currentShow = "Kannada Nadina Vaibhava & Family Serials",
        currentShowCategory = "Kannada Culture",
        progressPercent = 0.55f,
        language = "Kannada",
        isFeatured = false,
        description = "Celebration of Karnataka's glorious heritage, Yakshagana arts, and wholesome serials."
    ),
    // Marathi (465 - 470)
    RamChannel(
        id = "abp_majha",
        serialNumber = 465,
        name = "ABP Majha (ଏବିପି ମାଝା ମରାଠୀ)",
        logoText = "MJH",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "136.4K",
        resolution = "1080p FHD",
        currentShow = "ମାଝା ବିଶେଷ ଓ କଥା ମହାରାଷ୍ଟ୍ରାଚୀ (Majha Vishesh)",
        currentShowCategory = "Maharashtra Primetime",
        progressPercent = 0.85f,
        language = "Marathi",
        isFeatured = true,
        description = "Maharashtra's leading Marathi news channel with authoritative political analysis from Mantralaya."
    ),
    RamChannel(
        id = "zee_24_taas",
        serialNumber = 466,
        name = "Zee 24 Taas (ଜୀ ୨୪ ତାସ ମରାଠୀ)",
        logoText = "24T",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "114.2K",
        resolution = "1080p FHD",
        currentShow = "୨୪ ତାସ ମୁମ୍ବାଇ-ପୁଣେ ଲାଇଭ ଓ ଖବର ମହାରାଷ୍ଟ୍ର",
        currentShowCategory = "Marathi News",
        progressPercent = 0.75f,
        language = "Marathi",
        isFeatured = true,
        description = "First 24-hour Marathi news channel broadcasting grassroots issues from Vidarbha to Konkan."
    ),
    RamChannel(
        id = "tv9_marathi",
        serialNumber = 467,
        name = "TV9 Marathi (ଟିଭି୯ ମରାଠୀ)",
        logoText = "TV9M",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.7K",
        resolution = "1080p FHD",
        currentShow = "ମହାରାଷ୍ଟ୍ର ଲାଇଭ ଓ ଫାଷ୍ଟ ନ୍ୟୁଜ ବୁଲେଟିନ",
        currentShowCategory = "Fast Marathi News",
        progressPercent = 0.70f,
        language = "Marathi",
        isFeatured = false,
        description = "High energy news presentation covering Mumbai local train updates, farmers' issues, and state politics."
    ),
    RamChannel(
        id = "news18_lokmat",
        serialNumber = 468,
        name = "News18 Lokmat (ନ୍ୟୁଜ୧୮ ଲୋକମତ)",
        logoText = "N18L",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "82.5K",
        resolution = "1080p FHD",
        currentShow = "ଆଜଚା ମୁଦ୍ଦା ଓ ଦେଶ-ବିଦେଶ ସମାଚାର",
        currentShowCategory = "Maharashtra Debates",
        progressPercent = 0.65f,
        language = "Marathi",
        isFeatured = false,
        description = "Joint venture between Network18 and Lokmat Media delivering balanced political perspectives."
    ),
    RamChannel(
        id = "saam_tv_marathi",
        serialNumber = 469,
        name = "Saam TV (ସାମ ଟିଭି ମରାଠୀ)",
        logoText = "SAM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.1K",
        resolution = "720p HD",
        currentShow = "ସକାଳ ସମାଚାର ଓ ଶେତକରୀ ଆୱାଜ (Farmers Voice)",
        currentShowCategory = "Agrarian & Rural",
        progressPercent = 0.60f,
        language = "Marathi",
        isFeatured = false,
        description = "Sakal Media Group channel focusing on agrarian distress, sugarcane mills, and cooperative banks."
    ),
    RamChannel(
        id = "jai_maharashtra_news",
        serialNumber = 470,
        name = "Jai Maharashtra News (ଜୟ ମହାରାଷ୍ଟ୍ର)",
        logoText = "JMH",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.8K",
        resolution = "720p HD",
        currentShow = "ମୁମ୍ବାଇ ମେଟ୍ରୋ ଓ କ୍ରାଇମ ରିପୋର୍ଟ",
        currentShowCategory = "Urban Mumbai",
        progressPercent = 0.50f,
        language = "Marathi",
        isFeatured = false,
        description = "Dedicated reporting on Mumbai municipal corporation (BMC) and Thane urban issues."
    ),
    // Gujarati (471 - 475)
    RamChannel(
        id = "abp_asmita",
        serialNumber = 471,
        name = "ABP Asmita (ଏବିପି ଅସ୍ମିତା ଗୁଜରାଟୀ)",
        logoText = "ASM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "98.4K",
        resolution = "1080p FHD",
        currentShow = "ମୋହତାଜ ନଥୀ ଓ ଗୁଜରାଟ ନା ମୁଦ୍ଦା (Gujarat Debates)",
        currentShowCategory = "Gujarati Primetime",
        progressPercent = 0.80f,
        language = "Gujarati",
        isFeatured = true,
        description = "Gujarat's premier news channel with massive following in Ahmedabad, Surat, Rajkot, and Vadodara."
    ),
    RamChannel(
        id = "tv9_gujarati",
        serialNumber = 472,
        name = "TV9 Gujarati (ଟିଭି୯ ଗୁଜରାଟୀ)",
        logoText = "TV9G",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "94.2K",
        resolution = "1080p FHD",
        currentShow = "ଗୁଜରାଟ ଏକ୍ସପ୍ରେସ୍ ଓ କୃଷି ସମାଚାର (Garvi Gujarat)",
        currentShowCategory = "Gujarat Bulletins",
        progressPercent = 0.75f,
        language = "Gujarati",
        isFeatured = true,
        description = "High speed regional updates covering trade, diamond industry, textiles, and state governance."
    ),
    RamChannel(
        id = "sandesh_news_gujarati",
        serialNumber = 473,
        name = "Sandesh News (ସନ୍ଦେଶ ନ୍ୟୁଜ ଗୁଜରାଟୀ)",
        logoText = "SND",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.6K",
        resolution = "1080p FHD",
        currentShow = "ସନ୍ଦେଶ ବିଶେଷ ଓ ବ୍ୟାପାର ସମାଚାର",
        currentShowCategory = "Business & News",
        progressPercent = 0.65f,
        language = "Gujarati",
        isFeatured = false,
        description = "One of Gujarat's most respected media houses providing trustworthy daily news and business coverage."
    ),
    RamChannel(
        id = "zee_24_kalak",
        serialNumber = 474,
        name = "Zee 24 Kalak (ଜୀ ୨୪ କଳାକ ଗୁଜରାଟୀ)",
        logoText = "24K",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.3K",
        resolution = "1080p FHD",
        currentShow = "ଏକ ବାତ ଚୌପାଲ ପର ଓ ଗୁଜରାଟ ବିଶ୍ଳେଷଣ",
        currentShowCategory = "State Analysis",
        progressPercent = 0.70f,
        language = "Gujarati",
        isFeatured = false,
        description = "Zee Media's dedicated channel for 60 million Gujaratis worldwide."
    ),
    RamChannel(
        id = "vtv_gujarati",
        serialNumber = 475,
        name = "VTV Gujarati (ଭିଟିଭି ଗୁଜରାଟୀ)",
        logoText = "VTV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.9K",
        resolution = "720p HD",
        currentShow = "ଭିଟିଭି ପଞ୍ଚାୟତ ଓ ମନ୍ତବ୍ୟ ଲାଇଭ",
        currentShowCategory = "Opinion & Politics",
        progressPercent = 0.60f,
        language = "Gujarati",
        isFeatured = false,
        description = "Innovative Gujarati digital and television channel with lively debates on civic governance."
    ),
    // Punjabi (476 - 480)
    RamChannel(
        id = "ptc_news_punjabi",
        serialNumber = 476,
        name = "PTC News (ପିଟିସି ନ୍ୟୁଜ ପଞ୍ଜାବୀ)",
        logoText = "PTC",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "118.2K",
        resolution = "1080p FHD",
        currentShow = "ବିଚାର ତକ୍ରାର ଓ ପଞ୍ଜାବ ବୁଲେଟିନ (PTC Primetime)",
        currentShowCategory = "Punjabi Primetime",
        progressPercent = 0.85f,
        language = "Punjabi",
        isFeatured = true,
        description = "Global Punjabi television giant connecting Punjabis across India, Canada, the US, and UK."
    ),
    RamChannel(
        id = "zee_punjab_haryana",
        serialNumber = 477,
        name = "Zee Punjab Haryana HP (ଜୀ ପଞ୍ଜାବ)",
        logoText = "ZPH",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.5K",
        resolution = "1080p FHD",
        currentShow = "ମୁଦ୍ଦା ଆପଣା ଓ କିସାନ ସମାଚାର (Farmer Issues)",
        currentShowCategory = "North Regional",
        progressPercent = 0.70f,
        language = "Punjabi / Hindi",
        isFeatured = false,
        description = "Extensive reporting on agriculture, mandi MSP rates, sports, and state politics."
    ),
    RamChannel(
        id = "living_india_news",
        serialNumber = 478,
        name = "Living India News (ଲିଭିଙ୍ଗ ଇଣ୍ଡିଆ ପଞ୍ଜାବ)",
        logoText = "LIN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.7K",
        resolution = "720p HD",
        currentShow = "ପଞ୍ଜାବ କା ମାହୋଲ ଓ କାନାଡ଼ା ଇମିଗ୍ରେସନ ନ୍ୟୁଜ",
        currentShowCategory = "NRI & Punjab",
        progressPercent = 0.60f,
        language = "Punjabi",
        isFeatured = false,
        description = "Dedicated coverage of NRI youth immigration, student visas, and local youth issues."
    ),
    RamChannel(
        id = "mh_one_news",
        serialNumber = 479,
        name = "MH ONE News (ଏମଏଚ ୱାନ ନ୍ୟୁଜ)",
        logoText = "MH1",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "48.1K",
        resolution = "720p HD",
        currentShow = "ଚଣ୍ଡିଗଡ଼ ଡାଏରୀ ଓ ପଞ୍ଜାବ ବିଶେଷ",
        currentShowCategory = "State Bulletins",
        progressPercent = 0.50f,
        language = "Punjabi",
        isFeatured = false,
        description = "Popular channel for Punjab, Haryana, Himachal Pradesh with lively cultural reporting."
    ),
    RamChannel(
        id = "chardikla_time_tv",
        serialNumber = 480,
        name = "Chardikla Time TV (ଚଢ଼ଦୀକଳା ଟାଇମ)",
        logoText = "CKT",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.6K",
        resolution = "1080p FHD",
        currentShow = "ଗୁରୁମତ ବିଚାର ଓ ପଞ୍ଜାବୀ ସମାଚାର",
        currentShowCategory = "Sikh Heritage & News",
        progressPercent = 0.75f,
        language = "Punjabi",
        isFeatured = false,
        description = "Sikh philosophy, gurbani discourse, and historic events of Punjab."
    ),
    // Assamese & North East (481 - 487)
    RamChannel(
        id = "pratidin_time_assam",
        serialNumber = 481,
        name = "Pratidin Time (ପ୍ରତିଦିନ ଟାଇମ ଆସାମ)",
        logoText = "PRT",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "89.2K",
        resolution = "1080p FHD",
        currentShow = "ଆସାମ ପ୍ରାଇମ ବୁଲେଟିନ ଓ ବ୍ରହ୍ମପୁତ୍ର ଉପତ୍ୟକା ଖବର",
        currentShowCategory = "Assam Primetime",
        progressPercent = 0.85f,
        language = "Assamese",
        isFeatured = true,
        description = "Assam's top independent news channel with courageous investigations and cultural specials."
    ),
    RamChannel(
        id = "news_live_assam",
        serialNumber = 482,
        name = "News Live Assam (ନ୍ୟୁଜ ଲାଇଭ ଗୁଆହାଟି)",
        logoText = "NLV",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "81.4K",
        resolution = "1080p FHD",
        currentShow = "ପ୍ରୀତୀର ଡାଏରୀ ଓ ଉତ୍ତର-ପୂର୍ବାଞ୍ଚଳ ମହାସମର",
        currentShowCategory = "Northeast News",
        progressPercent = 0.80f,
        language = "Assamese",
        isFeatured = true,
        description = "Pioneer 24x7 satellite news channel in the Northeast based in Guwahati."
    ),
    RamChannel(
        id = "dy_365_assam",
        serialNumber = 483,
        name = "DY 365 (ଡିୱାଇ ୩୬୫ ଆସାମ)",
        logoText = "DY3",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "68.7K",
        resolution = "1080p FHD",
        currentShow = "କାଜିରଙ୍ଗା ବନ୍ୟପ୍ରାଣୀ ଓ ଆସାମ ଚାହା ବଗିଚା ଖବର",
        currentShowCategory = "Assamese Culture",
        progressPercent = 0.70f,
        language = "Assamese",
        isFeatured = false,
        description = "Voice of the masses highlighting tea garden workers, Kaziranga wildlife, and Bihu traditions."
    ),
    RamChannel(
        id = "prag_news_assam",
        serialNumber = 484,
        name = "Prag News (ପ୍ରାଗ ନ୍ୟୁଜ)",
        logoText = "PRG",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.3K",
        resolution = "720p HD",
        currentShow = "ମୁକ୍ତ ସମ୍ବାଦ ଓ ଆଲୋଚନା",
        currentShowCategory = "Assam News",
        progressPercent = 0.65f,
        language = "Assamese",
        isFeatured = false,
        description = "Longest standing satellite channel in Assam with wide grassroots reach in upper Assam."
    ),
    RamChannel(
        id = "assam_talks",
        serialNumber = 485,
        name = "Assam Talks (ଆସାମ ଟକସ୍)",
        logoText = "AST",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "46.5K",
        resolution = "720p HD",
        currentShow = "ସତ୍ୟ ବାର୍ତ୍ତା ଓ ଅଖଣ୍ଡ ଆସାମ ନ୍ୟୁଜ",
        currentShowCategory = "Local Bulletins",
        progressPercent = 0.50f,
        language = "Assamese",
        isFeatured = false,
        description = "Fast-paced news channel focusing on youth unemployment and infrastructure in Assam."
    ),
    RamChannel(
        id = "news18_assam_ne",
        serialNumber = 486,
        name = "News18 Assam-NE (ନ୍ୟୁଜ୧୮ ଆସାମ)",
        logoText = "N18A",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "73.2K",
        resolution = "1080p FHD",
        currentShow = "ଅଷ୍ଟଲକ୍ଷ୍ମୀ ଉତ୍ତର-ପୂର୍ବାଞ୍ଚଳ ନ୍ୟୁଜ ରାଉଣ୍ଡଅପ",
        currentShowCategory = "8 Sister States",
        progressPercent = 0.75f,
        language = "Assamese / English",
        isFeatured = false,
        description = "Network18 coverage across all 8 Northeastern states: Arunachal, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Tripura."
    ),
    RamChannel(
        id = "hornbill_tv_nagaland",
        serialNumber = 487,
        name = "Hornbill TV Nagaland (ହର୍ଣ୍ଣବିଲ ଟିଭି)",
        logoText = "HNB",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.8K",
        resolution = "1080p FHD",
        currentShow = "Kohima Live & Naga Hornbill Festival Specials",
        currentShowCategory = "Naga Culture & News",
        progressPercent = 0.65f,
        language = "English / Nagamese",
        isFeatured = true,
        description = "Premier English channel from Kohima showcasing vibrant tribal heritage and development."
    ),
    // Kashmiri, Urdu, Bhojpuri & Others (488 - 495)
    RamChannel(
        id = "dd_kashir_live",
        serialNumber = 488,
        name = "DD Kashir (ଡିଡି କାଶ୍ମୀର ଲାଇଭ)",
        logoText = "DDK",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "56.4K",
        resolution = "1080p FHD",
        currentShow = "ଡାଲ ହ୍ରଦ ସୌନ୍ଦର୍ଯ୍ୟ, ସୁଫିଆନା କଲାମ ଓ ଶ୍ରୀନଗର ସମାଚାର",
        currentShowCategory = "Kashmir Valley",
        progressPercent = 0.70f,
        language = "Kashmiri / Urdu",
        isFeatured = false,
        description = "Doordarshan's special channel celebrating Kashmir valley crafts, saffron valleys and shikara tourism."
    ),
    RamChannel(
        id = "gulistan_news_jk",
        serialNumber = 489,
        name = "Gulistan News J&K (ଗୁଲିସ୍ତାନ ନ୍ୟୁଜ)",
        logoText = "GLS",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "62.8K",
        resolution = "1080p FHD",
        currentShow = "ଜମ୍ମୁ-କାଶ୍ମୀର ଲାଇଭ ଡିବେଟ ଓ ପାହାଡ଼ି ସମାଚାର",
        currentShowCategory = "J&K Governance",
        progressPercent = 0.75f,
        language = "Urdu / Kashmiri",
        isFeatured = false,
        description = "Leading private news channel in Jammu, Kashmir and Ladakh with hyper-local district reporters."
    ),
    RamChannel(
        id = "zee_salaam_urdu",
        serialNumber = 490,
        name = "Zee Salaam (ଜୀ ସଲାମ ଉର୍ଦ୍ଦୁ)",
        logoText = "ZSL",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "71.3K",
        resolution = "1080p FHD",
        currentShow = "ମୁସାଏରା, ସୁଫି ରଙ୍ଗ ଓ ଉର୍ଦ୍ଦୁ ସମାଚାର ବୁଲେଟିନ",
        currentShowCategory = "Urdu Culture",
        progressPercent = 0.80f,
        language = "Urdu",
        isFeatured = false,
        description = "India's premier 24x7 Urdu language channel broadcasting mushairas, literature, and news."
    ),
    RamChannel(
        id = "tahzeeb_tv",
        serialNumber = 491,
        name = "Tahzeeb TV (ତହଜିବ ଟିଭି ଉର୍ଦ୍ଦୁ)",
        logoText = "THZ",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "45.1K",
        resolution = "720p HD",
        currentShow = "ଇସଲାମିକ୍ ଇତିହାସ ଓ ଗାଲିବ ଶାୟରୀ ଆଲୋଚନା",
        currentShowCategory = "Urdu Poetry",
        progressPercent = 0.60f,
        language = "Urdu",
        isFeatured = false,
        description = "Rich cultural heritage, classic Urdu poetry, Mirza Ghalib recitations, and harmony discourses."
    ),
    RamChannel(
        id = "big_ganga_bhojpuri",
        serialNumber = 492,
        name = "Big Ganga (ବିଗ୍ ଗଙ୍ଗା ଭୋଜପୁରୀ)",
        logoText = "BGG",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "88.6K",
        resolution = "1080p FHD",
        currentShow = "ଛଠ ପୂଜା ସ୍ପେସିଆଲ ଓ ଭୋଜପୁରୀ ମନୋରଞ୍ଜନ ଧାରାବାହିକ",
        currentShowCategory = "Bhojpuri Culture",
        progressPercent = 0.85f,
        language = "Bhojpuri",
        isFeatured = true,
        description = "Zee's leading Bhojpuri GEC delivering mega festivals like Chhath Puja, folk reality shows and serials."
    ),
    RamChannel(
        id = "dd_tripura_live",
        serialNumber = 493,
        name = "DD Tripura (ଡିଡି ତ୍ରିପୁରା ଲାଇଭ)",
        logoText = "DDT",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "38.2K",
        resolution = "1080p FHD",
        currentShow = "ଉଜ୍ଜୟନ୍ତ ପ୍ରାସାଦ ଓ କୋକବୋରୋକ ସାଂସ୍କୃତିକ କାର୍ଯ୍ୟକ୍ରମ",
        currentShowCategory = "Kokborok & Bengali",
        progressPercent = 0.60f,
        language = "Kokborok / Bengali",
        isFeatured = false,
        description = "Public broadcaster for Tripura representing Kokborok tribal music and Agartala updates."
    ),
    RamChannel(
        id = "dd_meghalaya_shillong",
        serialNumber = 494,
        name = "DD Meghalaya Shillong (ଡିଡି ମେଘାଳୟ)",
        logoText = "DDM",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "34.7K",
        resolution = "1080p FHD",
        currentShow = "ଚେରାପୁଞ୍ଜି ଜଳପ୍ରପାତ ଓ ଖାସି-ଗାରୋ ସଙ୍ଗୀତ (Scotland of East)",
        currentShowCategory = "Khasi & Garo Lore",
        progressPercent = 0.55f,
        language = "Khasi / Garo / English",
        isFeatured = false,
        description = "Shillong music festivals, living root bridges, and matrilineal community lifestyles in Meghalaya."
    ),
    RamChannel(
        id = "dd_manipur_imphal",
        serialNumber = 495,
        name = "DD Manipur Imphal (ଡିଡି ମଣିପୁର)",
        logoText = "DDMN",
        category = ChannelCategory.REGIONAL,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "39.1K",
        resolution = "1080p FHD",
        currentShow = "ମଣିପୁରୀ ଶାସ୍ତ୍ରୀୟ ରାସଲୀଳା ଓ ଲୋକତାକ ହ୍ରଦ",
        currentShowCategory = "Manipuri Dance & News",
        progressPercent = 0.65f,
        language = "Manipuri (Meiteilon)",
        isFeatured = false,
        description = "Graceful Manipuri Raas Leela dance, polo origins, and Keibul Lamjao floating national park."
    )
)
