package com.example.model

/**
 * 25 Live Sports & Athletic Channels (Serial 291 - 315)
 * Covers:
 * - DD Sports HD, Sports 18 Khel, Red Bull TV Sports, Olympic Channel,
 *   World Cricket 24x7, Pro Kabaddi Arena, Football World TV, Extreme Sports,
 *   Fight Sports Live, Motor Racing TV, Hockey India Live, Badminton World,
 *   World Athletics TV, Extreme Adventure, Fitness & Yoga Arena,
 *   Eurosport India FTA, World Wrestling Arena, Table Tennis Live, Golf Live India,
 *   Chess World Championships, Cycling World TV, World Snooker & Billiards,
 *   Archery World Cup, Shooting Sports India, Swimming & Aquatics TV.
 */
fun buildSportsChannels(): List<RamChannel> = listOf(
    RamChannel(
        id = "dd_sports_hd",
        serialNumber = 291,
        name = "DD Sports HD (ଡିଡି ସ୍ପୋର୍ଟସ)",
        logoText = "DDS",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/40492a64c1db4a1385ba1a397d357d3a/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "138.4K",
        resolution = "1080p 60FPS",
        currentShow = "India International Cricket & Khelo India Games Live",
        currentShowCategory = "Live Cricket & Games",
        progressPercent = 0.85f,
        language = "Hindi / English",
        isFeatured = true,
        description = "India's premier public service sports channel broadcasting India bilateral cricket, Olympics, and Asian Games."
    ),
    RamChannel(
        id = "sports_18_khel",
        serialNumber = 292,
        name = "Sports 18 Khel (ସ୍ପୋର୍ଟସ ୧୮ ଖେଳ)",
        logoText = "S18",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "115.6K",
        resolution = "1080p 60FPS",
        currentShow = "ଇଣ୍ଡିଆନ୍ ପ୍ରିମିୟର ଲିଗ୍ ଓ ଫୁଟବଲ ହାଇଲାଇଟ୍ସ (IPL & ISL)",
        currentShowCategory = "Cricket & Football",
        progressPercent = 0.70f,
        language = "Hindi",
        isFeatured = true,
        description = "Viacom18's FTA sports channel offering live cricket, football, NBA highlights, and road safety series."
    ),
    RamChannel(
        id = "red_bull_tv",
        serialNumber = 293,
        name = "Red Bull TV Sports (ରେଡ୍ ବୁଲ୍ ଟିଭି)",
        logoText = "RBT",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://rbmn-live.akamaized.net/hls/live/590964/flDisable/l畏live/master.m3u8",
        backupStreamUrls = listOf(
            "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
            "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
        ),
        viewersCount = "92.1K",
        resolution = "1080p 60FPS",
        currentShow = "Formula 1 Racing, Cliff Diving & Extreme Mountain Biking",
        currentShowCategory = "Extreme Sports",
        progressPercent = 0.75f,
        language = "English",
        isFeatured = true,
        description = "Worldwide extreme sports, Formula 1 behind-the-scenes, motocross, skiing, and high altitude athletics."
    ),
    RamChannel(
        id = "olympic_channel",
        serialNumber = 294,
        name = "Olympic Channel Live (ଅଲିମ୍ପିକ ଟିଭି)",
        logoText = "OLY",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://olympic-channel.akamaized.net/hls/live/2014498/olympic_live/master.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "73.5K",
        resolution = "1080p 60FPS",
        currentShow = "Olympic Games Legends, Neeraj Chopra Golden Javelin",
        currentShowCategory = "Olympic Games",
        progressPercent = 0.65f,
        language = "English",
        isFeatured = true,
        description = "Official IOC 24x7 channel celebrating Olympic games records, gold medal moments, and athlete stories."
    ),
    RamChannel(
        id = "world_cricket_live",
        serialNumber = 295,
        name = "World Cricket 24x7 (କ୍ରିକେଟ ଲାଇଭ)",
        logoText = "CRK",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "128.9K",
        resolution = "1080p 60FPS",
        currentShow = "India World Cup Epic Victories & T20 Thrillers",
        currentShowCategory = "Cricket Specials",
        progressPercent = 0.90f,
        language = "Hindi / English",
        isFeatured = true,
        description = "Non-stop cricket action, iconic centuries of Sachin, Kohli, Rohit, and unforgettable thrilling finishes."
    ),
    RamChannel(
        id = "pro_kabaddi_arena",
        serialNumber = 296,
        name = "Pro Kabaddi Arena (କବାଡି ଲାଇଭ)",
        logoText = "KBD",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "84.2K",
        resolution = "1080p 60FPS",
        currentShow = "Pro Kabaddi League Raids, Super Tackles & Highlights",
        currentShowCategory = "Pro Kabaddi",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = false,
        description = "High energy Indian indigenous sport broadcasting intense matches, super tackles, and mat battles."
    ),
    RamChannel(
        id = "football_world_tv",
        serialNumber = 297,
        name = "Football World TV (ଫୁଟବଲ ଟିଭି)",
        logoText = "FTB",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "67.4K",
        resolution = "1080p 60FPS",
        currentShow = "FIFA World Cup Legends, Messi vs Ronaldo Classic Goals",
        currentShowCategory = "Global Football",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "World football channel covering international leagues, unforgettable goals, and tactical analyses."
    ),
    RamChannel(
        id = "fight_sports_live",
        serialNumber = 298,
        name = "Fight Sports Arena (କୁସ୍ତି ଓ ବକ୍ସିଂ)",
        logoText = "FGT",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "59.1K",
        resolution = "1080p FHD",
        currentShow = "World Boxing Championship & MMA Heavyweight Title",
        currentShowCategory = "Combat Sports",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Championship boxing, MMA, kickboxing, and traditional Indian Kushti wrestling."
    ),
    RamChannel(
        id = "motor_racing_tv",
        serialNumber = 299,
        name = "Motor Racing Speed TV (ମୋଟର ରେସିଂ)",
        logoText = "SPD",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "52.8K",
        resolution = "1080p 60FPS",
        currentShow = "MotoGP & Superbike World Championship Highlights",
        currentShowCategory = "Motorsport",
        progressPercent = 0.65f,
        language = "English",
        isFeatured = false,
        description = "Pure speed, high-revving engines, drift competitions, and motorcycle Grand Prix."
    ),
    RamChannel(
        id = "hockey_india_live",
        serialNumber = 300,
        name = "Hockey India Live (ଭାରତ ହକି ଲାଇଭ)",
        logoText = "HCK",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "76.3K",
        resolution = "1080p 60FPS",
        currentShow = "FIH Hockey Pro League & Odisha Hockey World Cup Specials",
        currentShowCategory = "Field Hockey",
        progressPercent = 0.85f,
        language = "Hindi / English",
        isFeatured = true,
        description = "India's national sport in high definition from Rourkela and Bhubaneswar turf stadiums."
    ),
    RamChannel(
        id = "badminton_world_live",
        serialNumber = 301,
        name = "Badminton World TV (ବ୍ୟାଡମିଣ୍ଟନ)",
        logoText = "BDM",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "54.7K",
        resolution = "1080p 60FPS",
        currentShow = "BWF World Tour, PV Sindhu & Lakshya Sen Smash Highlights",
        currentShowCategory = "Badminton Tour",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Fast-paced rallies, smashes, and tournament showdowns of world badminton championships."
    ),
    RamChannel(
        id = "world_athletics_tv",
        serialNumber = 302,
        name = "World Athletics TV (ଆଥଲେଟିକ୍ସ)",
        logoText = "ATH",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "41.9K",
        resolution = "1080p FHD",
        currentShow = "Diamond League Track & Field Javelin, Sprints",
        currentShowCategory = "Track & Field",
        progressPercent = 0.55f,
        language = "English",
        isFeatured = false,
        description = "Track and field events, marathons, 100m sprint championships, and field throwing sports."
    ),
    RamChannel(
        id = "extreme_adventure_tv",
        serialNumber = 303,
        name = "Extreme Adventure TV (ସାହସିକ ଖେଳ)",
        logoText = "ADV",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "45.3K",
        resolution = "1080p FHD",
        currentShow = "Himalayan Mountaineering & Whitewater Rafting",
        currentShowCategory = "Adventure Sports",
        progressPercent = 0.50f,
        language = "English / Hindi",
        isFeatured = false,
        description = "High altitude mountaineering, rock climbing, skydiving, and white water rapid navigation."
    ),
    RamChannel(
        id = "fitness_and_yoga_live",
        serialNumber = 304,
        name = "Fitness & Yoga Arena (ଫିଟନେସ ଟିଭି)",
        logoText = "FIT",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "38.6K",
        resolution = "1080p FHD",
        currentShow = "Daily Power Yoga & Calisthenics Strength Training",
        currentShowCategory = "Fitness & Health",
        progressPercent = 0.60f,
        language = "Hindi / English",
        isFeatured = false,
        description = "Daily morning fitness workouts, cardio circuits, yoga asanas, and healthy athletic lifestyle guides."
    ),
    // Additional 11 Sports & Games Channels (305 - 315)
    RamChannel(
        id = "eurosport_india_fta",
        serialNumber = 305,
        name = "Eurosport India FTA (ୟୁରୋସ୍ପୋର୍ଟସ)",
        logoText = "ESP",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "61.3K",
        resolution = "1080p 60FPS",
        currentShow = "European Cycling, Tennis Grand Slams & Winter Sports",
        currentShowCategory = "Global Championships",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Live coverage of European track cycling, ski jumping, motorsports and Grand Slam tennis."
    ),
    RamChannel(
        id = "world_wrestling_arena",
        serialNumber = 306,
        name = "World Wrestling Arena (କୁସ୍ତି ଆଖଡ଼ା)",
        logoText = "WRA",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "72.4K",
        resolution = "1080p FHD",
        currentShow = "ଦଙ୍ଗଲ କୁସ୍ତି ଓ ଭାରତୀୟ ମଲ୍ଲଯୁଦ୍ଧ (Dangal Arena)",
        currentShowCategory = "Traditional Kushti",
        progressPercent = 0.80f,
        language = "Hindi",
        isFeatured = true,
        description = "Traditional Indian mud akharas, Olympic freestyle wrestling and Pehlwani championships."
    ),
    RamChannel(
        id = "table_tennis_live",
        serialNumber = 307,
        name = "Table Tennis Live (ଟେବୁଲ ଟେନିସ)",
        logoText = "TTN",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "32.1K",
        resolution = "1080p 60FPS",
        currentShow = "WTT Champions & Manika Batra Top Spin Rallies",
        currentShowCategory = "Table Tennis Tour",
        progressPercent = 0.65f,
        language = "English",
        isFeatured = false,
        description = "Lightning-fast table tennis rallies, world championship tour, and Indian national tournaments."
    ),
    RamChannel(
        id = "golf_live_india",
        serialNumber = 308,
        name = "Golf Live India (ଗଲ୍ଫ ଟିଭି)",
        logoText = "GLF",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "26.5K",
        resolution = "1080p FHD",
        currentShow = "PGA Tour, Indian Open & Master Strokes",
        currentShowCategory = "Golf Championships",
        progressPercent = 0.50f,
        language = "English",
        isFeatured = false,
        description = "Prestigious greens, PGA tour drives, putting precision, and Indian professional golf circuit."
    ),
    RamChannel(
        id = "chess_world_live",
        serialNumber = 309,
        name = "Chess World TV (ଚେସ୍ ଗ୍ରାଣ୍ଡମାଷ୍ଟର)",
        logoText = "CHS",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "58.9K",
        resolution = "1080p FHD",
        currentShow = "Gukesh, Praggnanandhaa & Anand Masterclasses",
        currentShowCategory = "Intellectual Sports",
        progressPercent = 0.75f,
        language = "English / Hindi",
        isFeatured = true,
        description = "FIDE World Chess Championships, Candidates tournament, and analysis by Indian prodigies."
    ),
    RamChannel(
        id = "cycling_world_tv",
        serialNumber = 310,
        name = "Cycling World TV (ସାଇକେଲ ରେସିଂ)",
        logoText = "CYC",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "29.4K",
        resolution = "1080p 60FPS",
        currentShow = "Tour de France, Giro d'Italia & Mountain Trails",
        currentShowCategory = "Road & Mountain Cycling",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "Grueling mountain stages of Tour de France, velodrome sprint tracks, and downhill trails."
    ),
    RamChannel(
        id = "snooker_billiards_tv",
        serialNumber = 311,
        name = "Snooker & Billiards TV (ସ୍ନୁକର ଲାଇଭ)",
        logoText = "SNK",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "27.8K",
        resolution = "1080p FHD",
        currentShow = "World Snooker Championship & Pankaj Advani Hits",
        currentShowCategory = "Cue Sports",
        progressPercent = 0.55f,
        language = "English",
        isFeatured = false,
        description = "Masterful cue control, 147 maximum breaks, and Pankaj Advani's world championship games."
    ),
    RamChannel(
        id = "archery_world_cup",
        serialNumber = 312,
        name = "Archery World TV (ତୀରନ୍ଦାଜୀ ଲାଇଭ)",
        logoText = "ARC",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.argusnews.in/hls/argustv.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "31.2K",
        resolution = "1080p FHD",
        currentShow = "World Archery Cup Bullseye Finals Live",
        currentShowCategory = "Precision Sports",
        progressPercent = 0.70f,
        language = "English",
        isFeatured = false,
        description = "Pinpoint target archery, Deepika Kumari's Olympic shoots, and compound bow world finals."
    ),
    RamChannel(
        id = "shooting_sports_india",
        serialNumber = 313,
        name = "Shooting Sports India (ସୁଟିଂ ଚାମ୍ପିୟନସିପ)",
        logoText = "SHT",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "36.5K",
        resolution = "1080p FHD",
        currentShow = "ISSF World Cup 10m Air Pistol & Rifle Finals",
        currentShowCategory = "Shooting Championships",
        progressPercent = 0.65f,
        language = "English / Hindi",
        isFeatured = false,
        description = "Manu Bhaker, Abhinav Bindra legacy, and Indian gold-winning shooters in international cups."
    ),
    RamChannel(
        id = "equestrian_polo_tv",
        serialNumber = 314,
        name = "Equestrian & Polo TV (ଘୋଡ଼ା ଦୌଡ଼ ଓ ପୋଲୋ)",
        logoText = "PLO",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://live.kanaknews.com:4443/live/stream/playlist.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "21.9K",
        resolution = "1080p FHD",
        currentShow = "Indian Royal Polo Cup & Show Jumping",
        currentShowCategory = "Equestrian Sports",
        progressPercent = 0.45f,
        language = "English",
        isFeatured = false,
        description = "Royal Indian polo tournaments from Jaipur, show jumping hurdles, and thoroughbred races."
    ),
    RamChannel(
        id = "swimming_aquatics_tv",
        serialNumber = 315,
        name = "Swimming & Aquatics TV (ସନ୍ତରଣ ଲାଇଭ)",
        logoText = "SWM",
        category = ChannelCategory.SPORTS,
        streamUrl = "https://mumbai-edge.smartplaytv.in/ddodiya/index.m3u8",
        backupStreamUrls = listOf("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"),
        viewersCount = "28.3K",
        resolution = "1080p 60FPS",
        currentShow = "World Aquatics Championships Freestyle & Butterfly",
        currentShowCategory = "Water Sports",
        progressPercent = 0.60f,
        language = "English",
        isFeatured = false,
        description = "High speed 50m and 100m freestyle, backstroke, diving board flips and water polo matches."
    )
)
